- scripts/cust-photon-v2.sh
Permissions changed from 766 to 0644. 766 allowed any user to write to the file
so an unprivileged user with local access could modify the service file to
get privileged execution. 0644 gives owner read/write access, and other users
read access
Signed-off-by: Andrew Ni <niandrew7@gmail.com>
@sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/103)
> Restrict service permissions in ubuntu-k8s customization script

- container_service_extension/broker.py
- container_service_extension/config.py
SHA1 is considered unsafe, so ova file verification has been updated
to use SHA256
Tested installation, cluster commands, node commands, and system commands
to make sure nothing broke
Note: we still use SHA1 hashing in utils.get_thumbprint(). However, this
function appears to be old and is never referenced.
@sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/105)
> Update ova file hashing to use SHA256 instead of SHA1

- container_service_extension/config.py
Originally, client.get_org_list() returned an lxml object, but
was since updated (in pyvcloud) to return a list, so this change
is necessary.
Tested with all CSE commands
@sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/106)
> Fix for loop to iterate over a list

- scripts/cust-ubuntu-16.04.sh
`apt-get -q dist-upgrade -y` will (most of the time) result in
a grub update that presents a selection menu, which will hang
and result in failed customization. These commands are not
vital to CSE functionality, but will be looked into further.
Tested with all CSE commands.
@sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/107)
> Comment out problematic lines in Ubuntu customization script

- setup.cfg
Currently ``python setup.py sdist bdist_wheel`` fails on windows
setup.cfg has data paths that uses / which windows will treat as \ only if they are not absolute path.
As a fix converted all / to ./
This fix is similar to https://github.com/vmware/pyvcloud/commit/5c7fdefcd9a7555b19327189e6386dd3e7ec668c#diff-380c6a8ebbbce17d55d50ef17d3cf906
and 
https://github.com/vmware/vcd-cli/commit/00769daf4403e2687b0a1ed60cefea8dcf65db14#diff-380c6a8ebbbce17d55d50ef17d3cf906
Signed-off-by: Aritra Sen <aritra.iitkgp@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/125)
> Fix paths in data section of setup.cfg for windows

- docs/README.md
- Documentation fix for viewing node info on a node with given cluster name
-  The usage example for cse node info is corrected. Verified in the installation that the command usage appears correctly and the usage works fine when gets executed in the local setup.
-  @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/127)
> [VCD-743] Documentation fix on incorrect command usage example

- container_service_extension/broker.py
- container_service_extension/config.py
Before, data and functionality regarding `cse sample` was split
between **broker.py** and **config.py**. It makes more sense to have this
functionality in one place (**config.py**)
Minor code cleanup, no logic changes
Tested `cse sample` command
@sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/118)
> Refactor sample config responsibilities

- container_service_extension/config.py
The final line of help text after creating a cluster is missing the --config switch from it's example starting command, this change just adds the switch to avoid confusion.
> Updated help text during cluster creation

- container_service_extension/client/cluster.py
- Returns the response status code when there is empty response content.
- Command example: vcd cse node info cluster1 node-4ji\\\\0
In case of node/cluster name with the special character in vcd cse node info <cluster-name> 
<node-name>,  VCD server returns 500 with empty body. It does not reach CSE server.
This fix returns the server status code to the client to let the user know server error happened.
- @rocknes @sahithi @harshneelmore @andrew-ni @sompa 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/130)
> [VCDA-695] Returns the server status code when there is no server response content

- container_service_extension/client/cse.py
- container_service_extension/cse.py
Moved docstring examples to their respective command subgroup.
Added/Cleaned up docstring examples for commands in both `cse.py` files
Tested `-h` commands to see that docstrings are displayed nicely
@sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/133)
> [VCDA-520] Docstring Examples for Commands

- container_service_extension/cluster.py
- container_service_extension/config.py
- container_service_extension/utils.py
Before, get_data_file() only searched in global site packages,
user site packages, current working directory, and a 'scripts'
directory in cwd. This means that if someone pip installs CSE
using a virtual environment, and runs `cse install` or other
commands while outside of the project directory, CSE would fail
to find any scripts.
This change fixes that issue, and as long as CSE was setup
correctly (pip install or python setup.py develop), get_data_file
will be able to find the script to execute.
Tested!
@sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/123)
> Improve how get_data_file() searches for data files

- container_service_extension/client/cse.py
- This fix will display help commands with no user login required. Manually tested help commands for various users[admininstrator, vappAuthor].
- @rocknes @sompa @sahithi @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/137)
> [VCDA-799] Remove login requirement from all vcd cse help commands

- container_service_extension/utils.py
I caused a bug when merging in two PRs at once. PR #146 removed the **os** import from **utils.py**, which PR #136 requires. Both PRs worked as expected, but after merging the first, I should have updated the second to be equal to **vmware:master**.
Tested to make sure nothing else was affected. config file processing/data file searching/cse installation all work as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/155)
> Add os import back to utils.py

- container_service_extension/config.py
- container_service_extension/consumer.py
- container_service_extension/cse.py
- container_service_extension/utils.py
Generalized AMQP configuration and CSE registration
- `install_cse()` uses `should_configure_amqp()` and `should_register_cse()` to decide whether or not to configure amqp settings or register extension based on existing settings and user input
Cleaned up `config.py` and `utils.py`
- `config.py` should only include code specific to the config file and cse installation
- `utils.py` should include general use code
- General functions `get_sha256()`, `bool_to_msg()`, `configure_vcd_amqp()`, `create_amqp_exchange()`, `register_extension()` have all been moved to `utils.py`
- AMQP configuration and CSE registration has been moved to occur before template creation, since template creation takes the longest and is most prone to failure. This way, CSE installation can just finish after template …
> [VCDA-789] Refactor CSE Installation - AMQP, registration, catalog

- container_service_extension/broker.py
- The user can successfully delete nodes not registered with CSE.
- Tested manually by creating a faulty node and using cse node delete CLUSTER-NAME NODE-NAME
- @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/173)
> [VCDA-833] Delete faulty/unregistered node from cse

- container_service_extension/broker.py
- container_service_extension/client/cse.py
- container_service_extension/cluster.py
- container_service_extension/config.py
- container_service_extension/consumer.py
- container_service_extension/cse.py
- container_service_extension/logger.py
- container_service_extension/processor.py
- container_service_extension/service.py
- container_service_extension/task.py
- container_service_extension/utils.py
**logger.py** contains all code for instantiating and configuring
loggers. Check **logger.py** for specific logger details
If logging is needed somewhere, import the specific logger,
and use it as you would normally.
```python
from container_service_extension.logging import SERVER_LOGGER as LOGGER
LOGGER.info('hi')
```
CSE will output these log files:
`cse-logs/cse-install_yr-mo-day_hr-min-sec.log`
`cse-logs/cse-server-info.log`
`cse-logs/cse-server-debug.log`
api requests made by CSE are still logged to:
`vcd.log`
Client actions do not have logging yet associated with them, but 
once they do, will output to:
`cse-logs/cse-client-info.log`
`cse-logs/cse-client-debug.log`
CSE server and client logs have a max size of 8mb, and a 10 file backup count
For example: …
> [VCDA-813] Implement centralized logging system

- container_service_extension/broker.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- By default, rollback is enabled to disable rollback user can add the flag **--disable-rollback** to cluster/node creation.
- Tested the implementation as follows:
Created faulty clusters/nodes and allowing rollback to trigger cleanup.
Created faulty clusters/nodes with rollback disabled to not trigger cleanup.
- @sakthisunda @andrew-ni @sahithi @hodgesrm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/178)
> [VCDA-834] Implement flag to disable rollback for troubleshooting

- container_service_extension/config.py
- container_service_extension/system_test_framework/environment.py
- container_service_extension/system_test_framework/utils.py
- container_service_extension/utils.py
- system_tests/cse_server_install_test.py
- system_tests/scripts/CUST-PHOTON.sh
- system_tests/scripts/CUST-UBUNTU.sh
- test-requirements.txt
Added testing to ssh into customized VMs and validate installed software versions.
Uses 'paramiko' library (added as a dependency to test-requirements).
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/180)
> [VCDA-835] Add VM customization tests to installation test suite

- docs/NFS_STATIC_PV.md
- docs/_data/navigation.yml
Edited the NFS persistent volume document to make it easier for
newcomers to understand.  Added a soup-to-nuts tutorial on NFS
management that demonstrates creating a cluster with NFS enabled,
adding storage and creating file shares, allocating persistent
volumes, and testing that everything works.
(Rendered documentation is available at https://hodgesrm.github.io/container-service-extension/INTRO.html.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/188)
> [VCDA-820] Improve documentation on NFS persistent volumes

- container_service_extension/broker.py
-  Update the task with stacktrace information
-  Pyvcloud new commit supports task update with stacktrace. To keep in sync, update the task from 
client (caller).  
with stacktrace.
-  Manually tested and verified
@rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/192)
> Client side changes - Task update with stacktrace

- container_service_extension/ovdc_cache.py
- container_service_extension/utils.py
- Persist ovdc metadata in Vcd
- For given ovdc name and/or with org, get the backing pvdc information with associated pks
information from pvdc cache and save it Vcd. Also, providing getter of the metadata for the given
ovdc name and/or org-name. Tested the code manually
@sahithi @sompa @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/202)
> [VCDA 853] Construct ovdc metada and persist in Vcd

- container_service_extension/authorization.py
- container_service_extension/cluster.py
- container_service_extension/server_constants.py
- setup.py
Flake8 has been updated to v3.7.2 on pypi .
The updated version of flake8 is stricter than v3.6.0. This PR fixes all the new validation errors found in CSE barring errors like D401, W605.
Testing done:
Ran flake8 on the affected files and made sure the reported errors were fixed.
> Fixed new validation error after updating flake8 to v3.7.2

- container_service_extension/configure_cse.py
- container_service_extension/logger.py
pyvcloud client fails silently if the log file path param points to a directory which doesn't exist. The current fix makes sure the CSE creates the log directories prior to creating the vCD client.
> Fix to make sure the logger directories are created before using logging utils

- container_service_extension/configure_cse.py
- container_service_extension/cse.py
- Fixes bug related to cse check command and refactors get_validated_config to accommodate removal of pks_config file param from cse check command.
Tested CSE server up is up and running with both with or without pks config file and that cse check command no longer has an option for providing pks-config file.
- @andrew-ni @sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/226)
> Fixing bug with `cse check` commands and get_validated_config

- container_service_extension/broker.py
PR 208 (https://github.com/vmware/container-service-extension/pull/208) missed few instances of self.config in broker.py. These leftover references to self.config is the cause behind broken vcd cse cluster config command and failures seen during node rollback.
As a fix, replaced the instances of self.config with server config obtained from Service class.
Testing done:
1. With the fix in, deployed a cluster and ran vcd cse cluster config 'cluster name' to check that the configuration of the K8 cluster is being returned properly by CSE.
2. Tried to add a node with >1TB memory requirement. The operation failed as expected. Checked server debug logs to make sure that node-rollback was launched on the above failure and no additional failures were observed during the node rollback operation. …
> Fix cluster config command and node rollback

- container_service_extension/configure_cse.py
`cse sample` command now always returns the sample string (prints cse sample config to console)
This bug was caused by click<7.0 not being able to handle `click.echo(None)` properly, resulting in an error.
Also updated formatting to comply with flake8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/236)
> Fix 'cse sample' bug if user had click<7.0

- scripts/cust-photon-v2.sh
- scripts/cust-ubuntu-16.04.sh
- system_tests/scripts/CUST-PHOTON.sh
- system_tests/scripts/CUST-UBUNTU.sh
Ubuntu template has been upgraded to use Docker 18.06.2 (from Docker 18.03.0)
Photon template has been upgraded to use Docker 17.06.0-9 (from default Photon2 Docker version. 17.06.0-?)
Both Docker versions have been validated to fix CVE-2019-5736
Testing done:
- Server and client system tests
- Manually deployed Kubernetes applications onto clusters using kubectl
- *CUST-PHOTON.sh* and *CUST-UBUNTU.sh* are static files used by our system tests that are copies of the actual customization scripts we use
---
Relevant links:
- Secure Docker versions for Photon: <https://github.com/vmware/photon/wiki/Security-Updates-2-129>
- Vulnerability info: <https://seclists.org/oss-sec/2019/q1/119>
- Docker release notes: <https://github.com/docker/docker-ce/releases>
Closes #231
--- …
> Fix CVE-2019-5736 (runc vulnerability) for Ubuntu and Photon vApp templates

- docs/CSE_ADMIN.md
- docs/RBAC.md
Currently when CSE installation shares the catalog, it just shares with org-admins of all orgs. Non org admin users don't have access to the catalog yet. To grant them access, sys admin needs to share the catalog explicitly with them. This PR documents the action item on sys admin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/235)
> [VCDA-904] Document action on sys admin to share catalog to non admin users

- container_service_extension/abstract_broker.py
- container_service_extension/broker.py
- container_service_extension/broker_selector.py
- container_service_extension/pksbroker.py
- container_service_extension/pksclient/api/cluster_api.py
- container_service_extension/pksclient/api/plans_api.py
- container_service_extension/pksclient/api/profile_api.py
- container_service_extension/pksclient/api/users_api.py
- container_service_extension/pksclient/api_client.py
Broker instance abstraction for cluster CRUD operations
- Changes that are required to select the right broker instance based on container-provider that is part of ovdc metadata.
- Currently, supported container-providers: 'pks' and 'vcd'.
- Manually tested cluster commands for the already existing vcd broker.
- Partially tested to check, if the container provider is 'pks', the broker selection and execution happens on PKSBroker.
- This pull request also has fixes for the pksclient and api_client code to unblock the testing.
@sahithi @sompa @rocknes @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/233)
> [VCDA-875] Broker instance selection based on container-provider

- docs/CSE_ADMIN.md
- docs/RELEASE_NOTES.md
Adds missing documentation for 'enforce_authorization' key in config file, as well as more details on how to update config file when a new CSE version is released.
Also fixed some formatting in affected markdown files.
Closes #241
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/244)
> [VCDA-911] Add documentation for config file update procedure

- container_service_extension/configure_cse.py
- container_service_extension/pks_cache.py
- container_service_extension/utils.py
-  Implementation of  CPI id, developer-mode, removal of rp-paths
- This PR implements logic to include CPI (Cloud Provider Id) associated with each datacenter in VC, in the new PKS configs. Removes the resource pool path field from pvdcs and adds datacenter and cluster field instead. Also adds logic to include a developer mode field 'pks_proxy_ip' to work with PKS dev set up where the PKS and VC reside in a different network than vCD's.
- @sahithi @sakthisunda @rocknes @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/252)
> VCDA-902 : Implementation of CPI id, developer-mode, removal of rp-paths

- container_service_extension/pks_cache.py
- container_service_extension/service.py
- Adds another method in pks_cache to get PKS information per org
- This PR adds a new utility method for pks_cache to get information related to all pks accounts associated per organization. Tested manually.
- @sahithi @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/255)
> VCDA-917: Add another method in pks_cache to get PKS information per org

- container_service_extension/configure_cse.py
- container_service_extension/cse.py
- container_service_extension/system_test_framework/environment.py
- docs/CSE_ADMIN.md
- docs/RELEASE_NOTES.md
- system_tests/test_cse_server.py
- Adjusted CSE installation to not use `--ext-install` option. Now CSE always registers or updates the extension info on vCD
- Removed testing for the option in `system_tests/test_cse_server.py`
- Removed mention of the option in documentation
Tested against server and client test suite
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/251)
> [VCDA-893] Remove '--ext-install' option from CSE installation

- container_service_extension/ovdc_cache.py
- container_service_extension/utils.py
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com
- Fix for extracting pvdc id from ProviderVdcReference
- ProviderVdcReference element in VDC object does not have 'id' attribute in VCD 9.1. But it is present in VCD 9.5. This fix extracts 'id' from 'href' attribute, if 'id' attribute is not found in VCD providerVdcReference.
- @sahithi @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/259)
> Fix enablek8s failure on VCD-9.1

- container_service_extension/configure_cse.py
- container_service_extension/utils.py
- system_tests/test_cse_server.py
- This PR relaxes the validation checks for additional config keys in CSE.
Current CSE implementation mandates the check for both missing and invalid keys and fails if either of the keys are missing or there is presence of additional keys other than what is expected in the configs.
Since we anyway safe load the config file contents at the start of any other operation relating to configs, simply removing the invalid keys from  `check_keys_and_value_types` serves our purpose and relaxes the check for `pks_config` or developer/test mode keys like `proxy` or `test`.
- Manually tested the get_validated_config method to see that the check_keys_and_value_types skip additional keys added to the config (example in case : pks_config, proxy)
- …
> VCDA-912: Revisit config validation checks to relax checks for additional keys

- container_service_extension/configure_cse.py
- container_service_extension/cse.py
- container_service_extension/utils.py
- requirements.txt
- system_tests/test_cse_server.py
Instead of printing a full stacktrace and exception, we now swallow
any exceptions related to improper config file values or
vCD setup. The invalid setting is then printed to console, without
any stacktrace or exception details.
Made changes to install and check in cse.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/256)
> [VCDA-896] Beautify vCD setup/config file errors during installation

- container_service_extension/client/cse.py
- Default org-name set for info/enable/disable ovdc
- This fixes the failing ovdc metada for k8s on not providing --org-name even though there is a
valid org set using vcs org use <org-name>. Manual testing done.
@sahithi @sompa @rocknes @harshneelmore @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/265)
> [VCDA-930] Set default org name for ovdc metadata operations for k8s

- container_service_extension/configure_cse.py
During CSE installation we always try to add the CSE/PKS rights and if the operation fails we look for a specific error message in the response body to infer that the right already exists in vCD. However the specific error message we are looking for is in English, which means any non English vCD installation will send us a response that will not match our criteria and the exception will leak out causing CSE installation to fail.
As a fix, we will get away from inferring the existence of the right via string matching on error messages, rather we will invoke vCD REST api to look for it directly. If the result comes back positive, we don't register the new rights, else we register them.
Also, it can be possible that the right is present in vCD but not granted to System org. Added logic to …
> [VCDA-946] Updated logic to check for presence of PKS/CSE right in vCD/System org.

- container_service_extension/ovdc_cache.py
- Extract pvdc id based on vcd api version
- Fixes the logic around extracting pvdc id from providerVdcReference depending on vCD
api versions. Older versions do not have pvdc id present; higher version have pvdc id present
as urn resource. Manual testing done. flake8 errors fixed
@sahithi @rocknes @sompa @harshneelmore @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/271)
> [VCDA-930] Extract pvdc-id correctly among different vcd-api versions

- container_service_extension/broker_manager.py
- container_service_extension/pksbroker.py
- container_service_extension/vcdbroker.py
-  Retains user level cluster context in PKS cluster management
-  PKS cluster management allows multiple users to manage clusters with same service account. This
by default, allow an user to see other users's cluster information who are sharing the 
service account.
In this pull request, changes are made to allow user level isolation of cluster management by doing
pre and post processing of cluster information to make them unique to the user doing the cluster 
operation. Manual testing completed for CRUD operations 
@sahithi @rocknes @sompa @andrew-ni @harsh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-ext …
> [VCDA-877] Vcd-User-Context-In-Pks-Cluster-Management

- container_service_extension/broker_manager.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
-  List cluster enhancements
-  List cluster supports --vdc that lists the clusters based on container provider of vdc. 
If it is set to 'pks', it gets only pks cluster list.
If it is set to 'vcd', it get only vcd cluster list.
'vdc' column of the result now gets populated with vdc name
'status' column of pks gets populated with last action + status
Testing: Manual testing completed with and without --vdc option.
@sahithi @sompa @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/279)
> [VCDA-869] Enhance-List-Cluster

- container_service_extension/abstract_broker.py
- container_service_extension/broker_manager.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/exceptions.py
- container_service_extension/ovdc_cache.py
- container_service_extension/pksbroker.py
- container_service_extension/processor.py
- container_service_extension/vcdbroker.py
This change-set has below:
1. Both client and server side implementation of resize command.
2. Exception handling for PksBroker.
3. Refactored the way we pass/leak HTTP request body to brokers. I modified the code in processor.py to deepcopy the request before we pass it to rest of the CSE engine(brokers), so that contents of the request is protected from any unexpected modifications by brokers (or) CSE engine. I had to do this as part of this change because "resize" implementation requires modification of the "body[node_count]".
The idea or design here is that we construct and pass the "request_spec" instead of "body" to broker_manager. Then broker_manager either updates or uses the "request_spec" as-is depending on certain factors. The responsibility of broker_manager also includes …
> vCDA-927: Resize cluster command; Exception handling of PksBroker; Refactoring

- container_service_extension/broker_manager.py
- container_service_extension/ovdc_cache.py
- container_service_extension/pksbroker.py
- container_service_extension/processor.py
- container_service_extension/vcdbroker.py
- PKS compute profile creation while enabling ovdc for k8s
- When container provider is 'pks', creating compute profile is also required as part of enabling ovdc for k8s. This commit includes all the changes that are necessary to create compute profile. Manual testing completed a) create new profile b) create the same profile when it already exists; this should not stop enabling ovdc parameters. 
@sahithi  @sompa @rocknes @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/274)
> [VCDA-930] Create-compute-profile-while-enabling-ovdc

- container_service_extension/broker_manager.py
- container_service_extension/client/cse.py
- container_service_extension/cluster.py
- container_service_extension/configure_cse.py
- container_service_extension/consumer.py
- container_service_extension/logger.py
- container_service_extension/ovdc_cache.py
- container_service_extension/pksbroker.py
- container_service_extension/processor.py
- container_service_extension/security.py
- container_service_extension/service.py
- container_service_extension/utils.py
- container_service_extension/vcdbroker.py
* Added a new logFilter to redact all log messages.
* Standardized all log messages in CSE to use f-strings and "
* Fixed flake8 errors in the editted files.
* Added some unit tests for the regex matcher
Testing done:
* Ran CSE commands and verified that server wire logs are getting redacted properly
2019-03-26 10:29:07,163 | DEBUG | cse-logs/cse-se | client          | _log_request | Response headers: {'Date': 'Tue, 26 Mar 2019 17:29:07 GMT', 'X-VMWARE-VCLOUD-REQUEST-ID': 'efdfb252-50c0-45f2-a1c3-373eb9ffeaf0', 'X-VMWARE-VCLOUD-CEIP-ID': '176ee7a0-7e79-45d1-a1a8-9d27c1a75930', 'X-VMWARE-VCLOUD-ACCESS-TOKEN': '[REDACTED]', 'X-VMWARE-VCLOUD-TOKEN-TYPE': 'Bearer', 'x-vcloud-authorization': '[REDACTED]', 'Content-Type': 'application/vnd.vmware.vcloud.session+xml;version=31.0', …
> [VCDA-906] Redact sensitive information in CSE logs

- scripts/cust-ubuntu-16.04.sh
- scripts/mstr-ubuntu-16.04.sh
Upgrade Kubernetes from v1.10.11 to v1.13.5 for Ubuntu 16.04
-Tested manually by doing a fresh installation of CSE and created a cluster with master and slave nodes.
-Tested using system_tests framework for CSE
- Tested by deploying a Kubernetes guestbook application on the cluster 
- @sahithi @andrew-ni @rocknes @yilmi-vmw
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/276)
> [VCDA-903] Upgrade Kubernetes templates from v1.10.11 to v1.13.5

- container_service_extension/broker_manager.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- Fixes the failing cluster creation as system administrator
- Creating cluster as sysadmin using System org would always fail. To handle this use case, new option --org-name is included as part of this command. If no org-name provided, org-in-use from the profiles gets used to find the ovdc. Also, fixed delete cluster not having named argument cluster-name before calling the broker.delete_cluster()
- Testing completed for create and delete cluster as sys-admin with and with no --org. flake8 errors fixed.
@sahithi @rocknes @sompa @harshneelmore
--- …
> [VCDA-964] Create-Cluster-As-SysAdmin-Fails

- container_service_extension/pksbroker.py
- Add rbac/authorization aspect to PKS broker
Only a user with PKS DEPLOY RIGHT will be able to create, delete or resize cluster. 
A user with no  PKS DEPLOY RIGHT can still view the cluster info, list clusters or get the cluster config.
- This PR adds RBAC to CSE PKS. The following scenario were tested:
1. PKS DEPLOY RIGHT was added to org    `vcd right add -o cse-org "{cse}:PKS DEPLOY RIGHT"`
2. Created two new users(admin and vappauthor clone) with custom roles with PKS DEPLOY RIGHT.
3. Login with the new users and create clusters on PKS.
4. Remove PKS DEPLOY RIGHT from the org.
5. Successfully list clusters created by the users 
- @sahithi @andrew-ni @sakthisunda @rocknes
--- …
> VCDA-876: Add rbac/authorization aspect to PKS broker

- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
Currently, the org name is not passed to list clusters for sysadmin, the command fails by addition of org name to the command parameter enables the sysadmins to list clusters successfully if the org name is not passed the current org in context is used.
- Tested manually with sysadmin user and non-sysadmin user.
- Successfully ran client system test.
- @rocknes @sahithi @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/295)
> [VCDA-965] List clusters as sysadmin fails if org name is not passed 

- container_service_extension/pksclient/api/v1/cluster_api.py
- container_service_extension/pksclient/api/v1beta/cluster_api.py
- container_service_extension/pksclient/api/v1beta/profile_api.py
- container_service_extension/pksclient/client/v1/api_client.py
- container_service_extension/pksclient/client/v1/rest.py
- container_service_extension/pksclient/client/v1beta/api_client.py
- container_service_extension/pksclient/client/v1beta/rest.py
-  Syntax error fixes in pks client code.
-  Async is a keyword in Python 3.7.x. long data type is no more supported and all are int in python 3.7.x. All the syntax errors related to these are fixed in this commit
@sahithi @sompa @rocknes @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/300)
> Fixed errors in new auto generated PSK client code

- container_service_extension/broker_manager.py
- Fixes broken ovdc-enable command when enabling unqualified ovdc for k8s deployment
- Unqualified ovdc that fails to find the supporting pvdc from pks config, command breaks. This fix raises proper exception and prints appropriate message to the console for the system administrator
@sahithi @sompa @rocknes @harshneelmore @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/299)
> [VCDA-930] Fix broken ovdc-enable command when enabling k8s for unqualified ovdc

- container_service_extension/broker_manager.py
- Fixes broken ovdc-enable command when enabling unqualified ovdc for k8s deployment
- Unqualified ovdc that fails to find the supporting pvdc from pks config, command breaks. This fix raises proper exception and prints appropriate message to the console for the system administrator. Debug statements included.
> [VCDA-930] Fixed broken ovdc-enable command when enabling for unqualified ovdc

- container_service_extension/broker_manager.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/client/ovdc.py
- container_service_extension/ovdc_cache.py
- container_service_extension/pks_cache.py
- container_service_extension/pksbroker.py
- container_service_extension/pksclient/client/v1/__init__.py
- container_service_extension/pksclient/client/v1beta/__init__.py
1. For create-cluster operation on PKS, user no longer has to input pks-plan and pks-ext-host-name
2. For enablek8s, admins have to input new param called "pks-cluster-domain". For each subsequent cluster deployments in that ovdc, "pks-external-host-name" will be dynamically constructed by CSE using "pks-cluster-domain" set on the ovdc. For example, if name of the cluster is "mycluster" and pks-cluster-domain set on the ovdc is "pepsi.com", then external host name of the cluster would be "mycluster.pepsi.com"
3. List-clusters is broken with new pks bits (compute-profile-name is no longer part of the cluster object returned by PKS server). As a temporary fix from CSE side (until PKS provides the actual fix), we are making an extra get_cluster_info() call for each cluster to get what we …
> [VCDA-977] Redesign create-cluster, enablek8s, list-clusters; Fix broken exception handling from new pks bits.

- container_service_extension/configure_cse.py
- container_service_extension/cse.py
- container_service_extension/nsxt/nsxt_client.py
- container_service_extension/pks_cache.py
- container_service_extension/service.py
- container_service_extension/utils.py
* Removed the optional section 'orgs' from sample pks.yaml
* Renamed the key 'pks_server' in pks.yaml to 'pks_api_server'
* Added stricter data validation for pks.yaml
* Added documentation for pks.yaml
* Small bug fix in nsx-t client to avoid failures while testing connection to a nsxt server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/303)
> [VCDA-976] Refactor pks.yaml to get rid of optional orgs section from sample.

- container_service_extension/broker_manager.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/client/ovdc.py
- container_service_extension/client/system.py
- container_service_extension/cse.py
- container_service_extension/ovdc_cache.py
- container_service_extension/server_constants.py
- system_tests/test_cse_client.py
- Required and optional parameters for different Kubernetes
providers has been more clearly highlighted
- Renamed 'container_provider' to 'k8s_provider'
- Renamed 'vcd' to 'native'
- Renamed 'pks' to 'enterprise-pks'
- Renamed enablek8s, disablek8s, infok8s to
enable-k8s, disable-k8s, info-k8s
- Revamped documentation for consistency, clarity, and usability
All system tests passed
Waiting on incoming changes for a few commands (create cluster, enablek8s)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/296)
> [VCDA-975] Beautify CLI documentation

- container_service_extension/pksbroker.py
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com
- Exclude administrator level details of cluster information output for tenant users 
- This fix excludes uuid, plan-name, compute-profile-name, compute-profile, nsxt-profile-name, network-profile from cluster information for tenant users 
- Completed manual testing
@rocknes @sompa @sahithi @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/312)
> [VCDA-1002] Exclude admin level details on cluster information for tenant users

- container_service_extension/pksbroker.py
- Fixes the missing vdc in the console output of vcd cse cluster list for PKS clusters
- vcd cse cluster list extracts vdc name from pks compute profile name. This was excluded in cluster information in the previous commit (VCDA-966). By bringing it back in cluster information, this works fine now.
- Verified thru manual testing
@sahithi @sompa @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/316)
> PR - vcd cse cluster list has missing vdc for PKS clusters

- scripts/cust-photon-v2.sh
- scripts/mstr-photon-v2.sh
- system_tests/scripts/CUST-PHOTON.sh
- system_tests/scripts/cust-photon-v2.sh
Upgrade Kubernetes from v1.10.11 to v1.12.7 for Photon OS 2.0
-Tested manually by doing a fresh installation of CSE and created a cluster with master and slave nodes.
-Tested using system_tests framework for CSE
- Tested by deploying a Kubernetes guestbook application on the cluster
@andrew-ni @sahithi @yilmi-vmw @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/290)
> [VCDA-924] Upgrade Photon OS 2.0 from Kubernetes from v1.10.11 to v1.12.7

- container_service_extension/broker_manager.py
- container_service_extension/exceptions.py
- container_service_extension/pksbroker.py
- PKS cluster name and exceptions should not expose vcd user id
- Currently, PKS cluster name and exceptions as console output exposes vcd user-id. This is fixed in this commit. Tested manually and also completed system tests.
@sahithi @rocknes @sompa @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/304)
> [VCDA-966] Remove vcd user id from console output and exceptions

- container_service_extension/broker_manager.py
- container_service_extension/client/cse.py
- container_service_extension/client/ovdc.py
- container_service_extension/pksbroker.py
PR implements code for listing PKS Plan information available for the vdcs in the system.
This PR adds the following:
Added an option to vcd cse ovdc list command to include plan information. This does not show pks server information as the above command and that is intended to be that way.
vcd cse ovdc list -p
org name k8s_provider available pks plans
cse-org cseVdc1 native ['Plan 1', 'multi-master']
cse-org NoContainerVdc none ['Plan 1', 'multi-master']
Tested as both system and org admin.
- @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/329)
> VCDA-897: Implementation of PKS plans command in CSE

- container_service_extension/broker_manager.py
Added org_name column to be displayed in vcd cse cluster list command.
-Tested manually with native-vcd and pks-ent
-Tested with different personas - Sysadmin, org-admin and vappauthor
> [VCDA-974] List clusters needs to have org column

- container_service_extension/client/cse.py
- container_service_extension/vcdbroker.py
- system_tests/test_cse_client.py
This change makes create_cluster_thread recognize the `--org` option, by sourcing the org from the request spec instead of from the currently logged-in org
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/330)
> [VCDA-1006] Update org source to request spec in create_cluster_thread

- container_service_extension/broker_manager.py
- container_service_extension/client/cse.py
- container_service_extension/exceptions.py
Avail plans to only sys admins and removing the org vdc in use to be passed as a param to resize clusters.
- This PR fixes the pks plans command option added to `vcd cse ovdc list` to be only available to system administrators. Also removes the org vdc in use from profiles to be passed as a param for vdc, if user does not specify a vdc as an option explicitly. 
- Tested `vcd cse ovdc list -p` as sys admin, org admin and vappauthor. Plan information is available only to system administrators.
- @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/conta …
> Avail plans to only sys admins and removing the org vdc in use to be passed as a param for vdc to resize clusters.

- container_service_extension/broker_manager.py
- container_service_extension/exceptions.py
- container_service_extension/nsxt/cluster_network_isolater.py
- container_service_extension/nsxt/dfw_manager.py
- container_service_extension/pksbroker.py
If cluster network isolation fails during creation of the cluster, we should ideally delete such clusters. However due to lack of post-creation hook from PKS, we are choosing to restrict access to the affected clusters, these clusters should be manually removed as soon as possible.
* Added new method to determine cluster network isolation is present or not.
* cluster config and cluster resize will now throw relevant exceptions if invoked on a cluster that isn't isolated at network layer.
Testing done:
1. Ran all CRUD operation on a healthy cluster to check for regressions. No regressions were found.
2. Failed network isolation of a cluster (via code) during creation. Checked all CRUD operation on it and validated that config and resize are the only operations that are failing with proper …
> [VCDA-1005] Restrict access to clusters with failed network isolation

- container_service_extension/authorization.py
- container_service_extension/broker_manager.py
- container_service_extension/exceptions.py
- container_service_extension/ovdc_cache.py
- container_service_extension/pksbroker.py
- container_service_extension/pyvcloud_utils.py
- container_service_extension/utils.py
Support for org admin to do CRUD on PKS cluster
- New method for checking if the logged-in user is an Org admin ( General Administrator Control, Administrator View )
- Changes to check if the cluster belongs to the given organization
- Changes related to PKS CRUD handing of org admin
- PKS Clusters with duplicate-name by tenant-users get prevented at the point of creation 
Testing completed:
1. System tests passed
2. Org admin can do all CRUD on clusters created by himself and other users of the Org
3. Org admin cannot do CRUD clusters of other org
4. Org user can do CRUD on their clusters
5. Org users cannot see clusters of other users of the same organization
6. Org users cannot see clusters of other users of different organization
7. Cluster with duplicate name is prevented at the time …
> [VCDA-960] org admin support for pks crud operations

- container_service_extension/client/cse.py
System Admin trying to create cluster should display the correct error message. If org is specified and vdc is missing it will display the correct error message.
- Tested the creation manually.
- @rocknes @sahithi @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/338)
> [VCDA-1032] System admin create cluster show appropriate error message

- container_service_extension/cse.py
- container_service_extension/utils.py
Vulnerability : https://nvd.nist.gov/vuln/detail/CVE-2019-9636
Score: 9.8
Impacted methods : urllib.parse.urlsplit or urllib.parse.urlparse when run on python versions prior to 3.7.3.
CSE server code uses the method urllib.parse.urlparse to parse vCenter url. Since the behavior is contained server side, we have decided to bump up the minimum version of python requiremed to run CSE server to 3.7.3.
With this PR, any attempt to run, install, generate sample off, check configuration file of, CSE server on a system running python versions prior to 3.7.3 will fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/339)
> Address CVE-2019-9636

- container_service_extension/vcdbroker.py
- This PR provides a check for missing network name param for the cluster creation command and provides a proper error message that conveys about the missing network name. 
- @sahithi @rocknes @sakthisunda @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/343)
> VCDA-1033: Proper message for missing network name error in cluster creation command

- container_service_extension/configure_cse.py
- docs/CSE_ADMIN.md
- system_tests/base_config.yaml
Update Kubernetes version for Photon OS
- @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/344)
> Change doc string to fix Photon OS Kubernetes version from 1.10.11 to 1.12.7

- container_service_extension/pksbroker.py
- Improved cluster list filtering that are visible to org-admin
- When filtering the cluster list for org-admin, first lookup for clusters that are created/owned by org-admin ; if not, then check if the cluster belong to organization of org-admin using compute-profile. This optimizes the filtering. Also, correctly detects the resized-clusters that are created by org-admin.
Manual testing done for the following
- CRUD operations on clusters as org-admin. Specific tests to check if resized clusters that are created by org-admin show up in cluster list operation. 
- CRUD operation on clusters as other personas (sys admin, tenant user) works as expected.
System test completed
@sahithi @rocknes @sompa @harshneelmore @andrew-ni
---
This …
> [VCDA-1049] Improve generation of cluster list visible to org-admin 

- container_service_extension/broker_manager.py
- container_service_extension/cluster.py
- container_service_extension/pksbroker.py
- container_service_extension/utils.py
- container_service_extension/vcdbroker.py
- Fixed filtering options --vdc, --org for vcd cse cluster list sysadmin, org admin and tenant users
- Enhancements done to support --vdc option for sysadmin, org-admin, tenant users, --org option for sysadmin  
- System test completed
- Manually tested and verified vcd cse cluster list for sysadmin, orgadmin and others
--org with --vdc that is container provider for vDC only for sysadmin
--org with --vdc that is container provider for PKS only for sysadmin
--org with --vdc that has container provider(s) for both vDC and PKS for sysadmin
--vdc for org-admin for multiple vdc(s) within the organization
--vdc for tenant users who owns clusters backed by different vdc(s) 
@sahithi @rocknes @sompa @harshneelmore @andrew-ni
---
This change …
> [VCDA-1042] Fix for filtering options vdc, org for vcd cse cluster list

- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/vcdbroker.py
- Fixes the filtering options for system administrator and org admins for getting the cluster config correctly using the --vdc and --org options in cluster config command.
- Tested both namesake clusters of type vcd and pks with the filtering options and verified that the correct config for the cluster gets retrieved. Please refer to the JIRA task for details on the bug : https://jira.eng.vmware.com/browse/VCDA-999
- @sahithi @sakthisunda @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/361)
> VCDA-999: Unable to get the correct cluster config as sys admin

- container_service_extension/broker_manager.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/exceptions.py
- container_service_extension/pksbroker.py
- container_service_extension/vcdbroker.py
- Cluster delete support for vdc, org options
- With vdc and org option sys admin can pick and delete for a given org and vdc. This also work for other personas.
- Manual testing completed
- Tested for --vdc, --org separately as well as together
- Tested for duplicate cluster names with exception message
- System tests passed
NOTE: Dependency on VCDA-1042 commit. Sanity tests will be done again after merging VCDA-1042
@sahithi @rocknes @sompa @harshneelmore @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/357)
> [VCDA-1043] Fix filtering options vdc,org for vcd cse cluster delete 

- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- Supports --org and --vcd option. Fixed the missing --org option
-  Enhancement completed for for system administrator to know the cluster info on given org and vdc. Right error message if open ended cluster info detects duplicate cluster names across organizations.
- Manual testing completed. 
- System administrator to get the cluster info based on the org and vdc
- Org admin to get the cluster info of the cluster in the organization
- Tenant user to get the cluster info that is owned.
- System tests completed
Depends on VCDA-1043 as server side changes and duplicate detection got done in this task.
- @sahithi @rocknes @sompa @harshneelmore @andrew-ni
---
This change …
> [VCDA-1055] Fix filtering options 'vdc' and 'org' for cse cluster info (for sysadmin users)

- container_service_extension/broker_manager.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/processor.py
- container_service_extension/vcdbroker.py
Added the param to include ORGVDC in use to the request parameters for node info.
- Tested the above change with native for Org Admin user.
- Tested the changes after enabling PKS for Org Admin user.
@sakthisunda @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/350)
> [VCDA-1037] vcd cse node info command broken after enabling PKS

- container_service_extension/broker_manager.py
- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/processor.py
- container_service_extension/vcdbroker.py
- Fixed handling of org and vdc options of cluster resize, node create, node delete, node list. Also fixed full stack trace on console. 
-  This is an enhancement for cluster resize where system administrator can pick and choose to resize cluster by providing which organization and vdc. Proper error message on choosing cluster with same name across organizations. Full stack trace on console fixed by moving the exception handler and related logic to broker manager from processor. 
- All system tests passed. 
Completed manual tests as system administrator and others.
Duplicate cluster testing, no more stack trace on the console.  
@rocknes @sahithi @sompa @harshneelmore @andrew-ni
--- …
> [VCDA-1044] Fix filtering options 'vdc' and 'org' for cse cluster resize (for sysadmin users)

- container_service_extension/broker_manager.py
- container_service_extension/vcdbroker.py
Signed-off-by: Sakthi Sundaram <sakthisunda@yahoo.com
- Fixed stack trace of error message on executing vcd cse node info
- Changes made to stop the entire stack trace on any error message while executing vcd cse node info
- Manually tested 
- Existing node
- Non existing node
- Existing cluster, duplicate cluster, non-existing cluster
@rocknes @harshneelmore @sompa @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/366)
> [PR] Fixed stack trace of error displayed on console when executing vcd cse node info

- container_service_extension/cluster.py
While adding a node to a native K8 cluster, 
1. CSE assumes that the node vms admin password is always set.
2. CSE assumes the password is same as the one in the source template.
Both these assumptions can be wrong. The correct behavior in this case should be to auto generate a password while deploying the vm from template, read the password from the deployed VM instead of the template and update it to the user provided password.
Testing done:
* Used catalog external publish/subscribe model to create a copy of the CSE template in org1
* Manually checked that the subscribed catalog templates didn't have the vm password section.
* Deployed two K8 clusters (1 based on ubuntu template and 1 based on photon template) along with nfs servers, both deployments were successful.
* Also ran server …
> Change how admin passwords are generated and read for K8 cluster vms

- docs/ENT-PKS.md
Changed the wrong command 'cse config' to the correct command 'cse sample'
> Fix doc error - wrong command to generate sample config files in enterprise PKS doc.

- container_service_extension/system_test_framework/utils.py
- system_tests/test_cse_client.py
- system_tests/test_cse_server.py
When debugging our CICD builds, we ran into many user/environment specific errors that we would have caught earlier had we captured all output from the failed commands.
This fix adds: command, command exit code, and command output to the AssertionError message
Jenkins build for this PR was successful: https://sp-taas-vcd-butler.svc.eng.vmware.com/job/CTOT4-CSE/83/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/369)
>  Update assert failures to print useful debugging info

- container_service_extension/configure_cse.py
- container_service_extension/cse.py
- container_service_extension/processor.py
- container_service_extension/sample_generator.py
- scripts/cust-photon-v2.sh
- scripts/cust-ubuntu-16.04.sh
- test-requirements.txt
- tox.ini
Removed vApp reboot step after template customization
Once we reboot the VM, the machine gets assigned a machine-id,
and once we capture this VM, all future VMs deployed from
this template will have the same machine-id. This breaks
Kubernetes functionality
Updated customization scripts to properly prepare **machine-id** files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/382)
> Fix bugs preventing proper Kubernetes app deployment on clusters

- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/cluster.py
- container_service_extension/config_validator.py
- container_service_extension/configure_cse.py
- container_service_extension/pyvcloud_utils.py
- container_service_extension/request_handlers/cluster_handler.py
- container_service_extension/request_handlers/template_handler.py
- container_service_extension/sample_generator.py
- container_service_extension/server_constants.py
- container_service_extension/service.py
- container_service_extension/shared_constants.py
- container_service_extension/vcdbroker.py
- system_tests/base_config.yaml
- system_tests/test_cse_client.py
* Updated vcd cse cluster create, vcd cse node create commands to expose template revision as a param.
* Propagated the concept of template revision through relevant backed methods in cluster.py
* Store/Retrieve template revision to/from cluster metadata.
* Relaxed requirement of Org name in most of cluster related operations. This change is required for sys admin cli commands to be less verbose.
* Cleaned up cluster.py to get rid of dependency on server run-time config.
* Made wire logging optional via a config flag service->log_wire, which is false by default.
Testing done:
* Both system tests passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/393 …
> [VCDA-1113] Expose template revision as cli command options

- container_service_extension/vcdbroker.py
With vCD 9.8+ CSE is sending the wrong href_value while creating and updating tasks for long-running operations. This update will fix the href_value with cluster owner href_value and update owner type to 'application/vnd.vmware.vcloud.org+xml'.
- Manually tested p vCD 9.8 and 9.7
- @rocknes @andrew-ni @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/391)
> [VCDA-1105] Fix task based CSE operation for vCD 9.8

- container_service_extension/cloudapi/cloudapi_client.py
- container_service_extension/cloudapi/compute_policy_manager.py
- container_service_extension/cloudapi/constants.py
- Support added to do list/create/delete/update compute policy on cloudapi
- Assigning compute policy to vdc and vms need a valid compute policy id and href. This change provides methods to support CRUD on /cloudapi for vdcComputePolicy.
In addition, support methods added to assign compute policy to vdc and vms of vapp template. (VCDA-1121)
- Testing done and verified using script and postman REST client for the following operations 
- Add, update, delete, get, list compute policy from/to /cloudapi
- Add, remove compute policies from/to vdc
- Assign, remove compute policies from/to vms of vapp template
@rocknes @andrew-ni @harshneelmore
--- …
> [VCDA-1082, VCDA-1121] Support for list/create/delete/update vdc compute policy 

- container_service_extension/cloudapi/compute_policy_manager.py
- Fixed missing vcd client argument 
- get_vdc from given org-name and vdc-name requires vcd client. This PR fixed the missing client in get_vdc().
- Tested and verified
@rocknes @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/403)
> [VCDA-1121] Fix a bug in add_compute_policy_to_vdc method, missing vcd client argument

- container_service_extension/system_test_framework/environment.py
- system_tests/test_cse_client.py
Add support to delete clusters by using different personas - Vapp Author, Org admin. 
This test will delete the cluster created by cse create cluster command.
Tested manually waiting to test on Jenkins
@rocknes @andrew-ni @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/402)
> [VCDA-1094] Add persona support for delete clusters

- container_service_extension/ovdc_utils.py
My last tech debt PR introduced a bug in `ovdc list` where there was a misplaced index into a dictionary. This PR removes that misplaced index
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/405)
> Fix ovdc list bug

- container_service_extension/ovdc_utils.py
`ovdc list --pks-plans` needs to get the name of the vCenter backing the org VDC. Before, we relied on the `<ComputeProviderScope ... />` element in the `<Vdc ... />` or `<AdminVdc ... />` XML resource. This is wrong because this tag only exists if VMware's vCD smoke tests are run on the vCD.
This PR replaces that vCenter name fetching mechanism with Pyvcloud's `client.get_typed_query()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/408)
> [VCDA-1108] Fix how `ovdc list --pks-plans` gets vCenter name

- container_service_extension/cloudapi/cloudapi_client.py
- container_service_extension/cloudapi/compute_policy_manager.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/service.py
- container_service_extension/template_rule.py
Templates have metadata that is derived from remote cookbook recipe and represents the template's default state. However the state can be modified during CSE server startup via template rules. This PR makes sure that once the changes are made via rules, the template is made compliant to those changed values. This PR specifically makes sure that the compute policy that is specified in the template run-time definition is actually applied to the vms in the template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/410)
> [VCDA-1120] Making templates complaint with the compute policy

- container_service_extension/vcdbroker.py
- Fixed failing get cluster config on older CSE versions.
- Getting cluster config requires the password for the individual vms.  Because of new template naming conventions,  getting the password for older vm(s) using the template fails as the lookup by new template name (in future CSE) won't work. This is fixed by getting the password from the vapp and use that for getting the cluster configuration.
@rocknes @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/416)
> [VCDA-1134] Fix-Get-Cluster-Config-Backward-Compatibility

- container_service_extension/client/cse.py
- container_service_extension/client/ovdc.py
- container_service_extension/client/response_processor.py
- container_service_extension/cloudapi/cloudapi_client.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/request_handlers/system_handler.py
- container_service_extension/request_processor.py
- container_service_extension/server_constants.py
- container_service_extension/service.py
- container_service_extension/shared_constants.py
Implemented:
- `ovdc compute-policy add org_name ovdc_name policy_name`
- `ovdc compute-policy remove org_name ovdc_name policy_name`
- Known issue: cannot remove a compute policy from an org VDC if vApp templates or VMs contain the compute policy reference in their XML resource
- `ovdc compute-policy list org_name ovdc_name`
Cleaned up some code and updated docstrings
!!! Dependent on pyvcloud PR: https://github.com/vmware/pyvcloud/pull/607
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/414)
> [VCDA-1136] Implement ovdc compute policy operations

- container_service_extension/cluster.py
- container_service_extension/sample_generator.py
- container_service_extension/server_cli.py
- container_service_extension/server_constants.py
- container_service_extension/template_rule.py
- container_service_extension/vcdbroker.py
Currently CSE doesn't lean on admin password defined in config file to interact with k8s clusters. Each cluster vm 's admin password is determined by the template that was used to create them. And the admin password is part of the vm XML representation. This change in password mechanism has rendered old clusters deployed by CSE 2.0.0 and below, unmanageable by current CSE. To fix this issue a new command viz. _cse convert-cluster_ has been exposed in cse server cli, that targets clusters and resets each vm's admin password to an auto generated password via guest customization. The command also formats the metadata on the cluster to suit the new CSE's cluster metadata structure.
Testing done:
Created a photon and ubuntu cluster using CSE 1.2.7
Upgraded CSE to the latest commit of this PR. …
> [VCDA-1155] Expose command to migrate clusters deployed by CSE 2.0.0 and below to current CSE.

- requirements.txt
pyvcloud 20.1.1dev97 contains the fixes for list_vdcs and get_vdc as well as the functionality to swap out compute policies from deployed vms.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/431)
> Update pyvcloud requirement to v20.1.1dev97

- container_service_extension/client/cse.py
- container_service_extension/cluster.py
- container_service_extension/local_template_manager.py
- container_service_extension/request_handlers/cluster_handler.py
- container_service_extension/vcdbroker.py
When we query vCD for listing clusters, vCD sends back metadata on those vApps too as  part of the result. One of the metadata viz. template_name can be parsed to deduce the k8s version that's installed in the master node. This PR parses the name of the template of which the master node was created and appends it to the result of the call to list all clusters. If for any reason the name parsing fails, the value "Unknown" is returned.
This change only affects native clusters! To retrieve Enterprise PKS cluster's K8s version we need a separate REST call. Currently for Enterprise PKS clusters, the output of the REST call /api/clusters will have the k8s_version field set to None , while the field will be completely missing for /api/cluster/{name} calls
Testing done:
Created a native cluster. …
> [VCDA-1199] Add K8s_version field to output of /api/cse/clusters and /api/cse/cluster/{name}

- container_service_extension/client/cse.py
- container_service_extension/client/ovdc.py
- container_service_extension/cloudapi/cloudapi_client.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/pyvcloud_utils.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/shared_constants.py
- container_service_extension/vcdbroker.py
- system_tests/test_cse_client.py
- Implemented get_all_vapps_in_ovdc()
- Bugfix: cluster create would create the same number of masters as workers. Fixed to only create 1 master node
- Bugfix: 'None' template name and revision during cluster create 
- Implemented replacing specified compute policy on VMs with 'System Default' compute policy
- Updated CSE client to expose force removal of compute policy from ovdc
**Important notes regarding this change:**
- 'System Default' compute policy must be assigned to the ovdc, but 'System Default' does not have to be the default compute policy.
- vCD extension timeout must be extended or else this operation will get a timeout error
--- …
> [VCDA-1175] Replace existing VMs compute policy with 'System Default' during forced ovdc compute policy removal

- docs/RELEASE_NOTES.md
Fixed GA release date of CSE 1.1.0 in RELEASE_NOTES.md. 
Verified to match the date in  https://pypi.org/project/container-service-extension/#history
@rocknes  @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/440)
> [VCDA-1213] Fixed GA Release Date For CSE 1.1.0

- docs/_data/navigation.yml
- Updated Left Side Navigation Menu to include link for Enterprise PKS Limitations info.
- This link helps in landing directly into Enterprise PKS limitations section.
@goelaashima @rocknes @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/445)
> [VCDA-1233] Navigation link added for Enterprise PKS Limitations

- docs/_data/navigation.yml
Following changes are made on https://vmware.github.io/container-service-extension/CSE_ADMIN.htm
-  VM Templates replaced with Kubernetes Templates
- Removed CSE Server Versions Topic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/441)
> [VCDA-1223] CSE SERVER MANAGEMENT - Left Side Navigation Changes

- container_service_extension/cluster.py
- container_service_extension/pyvcloud_utils.py
- container_service_extension/system_test_framework/environment.py
- container_service_extension/template_builder.py
In vcd api v33.0, due to a change in the way how non admin users find href of a catalog that is shared from another org, they are unable to access such catalogs and deploy k8s clusters. To fix this issue, sys admin gets the href of the catalog for these affected users.
Additional fix:
Trap exceptions raised by pyvmomi and convert them to CSE exception to patch the workflow where cluster rollback on error was being skipped.
Testing done:
With the fix in, a vapp_author is able to deploy cluster from shared catalogs (server is running on api v33.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/442)
> [VCDA-1210] Fix cluster deployment for non admin cross org users with api v33.0

- container_service_extension/remote_template_manager.py
- Set permissions on template script files that is downloaded to the local folder
- As part of the security requirement the template scripts that gets downloaded to the 
local folder needs to have read/write permissions only for the owner. This fix sets those 
permissions as soon the completion of the script download.
- Tests done:
- cse install
- cse template 
- vcd cse cluster create
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/448)
> [VCDA-1237] Set permission of downloaded script as 600

- container_service_extension/cloudapi/constants.py
- container_service_extension/compute_policy_manager.py
ComputePolicyManager's `get_all_cse_policies()` function now returns a generator that will yield all CSE compute policies in vCD, making multiple requests when necessary.
This is implemented with a generator because cloudapi paginates the `GET /vdcComputePolicies` endpoint.
Tested and working in vCD 10.0 and 9.7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/437)
> [VCDA-1203] Refactor `get_all_cse_policies()` to return a generator 

- container_service_extension/sample_generator.py
Changed sample values from ubuntu (k8s 1.15) to a non existent template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/449)
> [VCDA-12326] Change default template name and revision values to sample values.

- container_service_extension/client/cse.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/utils.py
- container_service_extension/vcdbroker.py
Implement asynchronous processing for setting compute policies to 'System Default' for deployed VMs during 'force ovdc compute policy removal' operation.
This change creates a new thread to handle the VM compute policy updates that must be done during forced ovdc compute policy removal. For each affected VM, CSE server makes a call to vCD to update the compute policy to 'System Default', and then waits for task success before initiating the next call.
Notes:
- Due to a limitation on vCD, CSE server can not initiate several server-side calls to update multiple VMs and then wait for all of them at once. Doing this results in a `BusyEntity` error with vCD's networking.
- Investigated using **asyncio** library to make the process fully asynchronous (send all VM update requests and wait for …
> [VCDA-1211] Modify VM compute policy update to be asynchronous

- container_service_extension/compute_policy_manager.py
- container_service_extension/service.py
- Fix broken cloudapi vdcComputePolicy check
- During template processing, /cloudapi/vdcComputePolicies endpoint is used to get the policies. 
This endpoint is not supported in vCD 9.1 and caused error. This fix check the existence of this 
endpoint before accessing that.
- Tested and verified manually by adding and removing template rule
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/452)
> [PR] Fix error handling for cloudapi existence for vCD 9.1

- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/request_processor.py
- container_service_extension/vcdbroker.py
Server previously replaced all default values with the request data values,
even if the request data values were 'None'
Now, request processor strips out 'None' values from the request data, so
that non-None default values are properly preserved in the final validated
data
Testing in progress
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/459)
> Fix how server handles default data values

- container_service_extension/compute_policy_manager.py
- container_service_extension/service.py
- system_tests/test_cse_client.py
An instance of get_policy() raising an exception was not
being handled. This prevents CSE from creating new
compute policies and starting up the server when a new
compute policy is specified in template rules
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/461)
> Fix bug blocking new compute policy creation and server startup

- system_tests/test_cse_client.py
-  Fix to handle plain-text configuration file for client system tests
-  Tested and verified that the current tests pass thru the install and run with the base_config.yaml as before.
@andrew-ni @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/479)
> [VCDA-1277] Client tests changes to handle plain-text configuration

- container_service_extension/config_validator.py
- container_service_extension/configure_cse.py
- container_service_extension/sample_generator.py
- container_service_extension/server_cli.py
- container_service_extension/service.py
- cse.sh
- docs/CSE_CONFIG.md
- system_tests/test_cse_client.py
- system_tests/test_cse_server.py
- Changes that decouple PKS config file from CSE config file
- All server side commands now accept pks config file an an option in addition to mandatory CSE configuration.
- Config file has become mandatory argument
- No more PKS specific information in CSE configuration
- Support for optional PKS config file
- Test case fixes 
- Test cases:
- Executed updated system test cases to complete all tests successfully.
- CSE sample, check, install, template list, install, run, convert cluster.
- Client tests updated to run CSE server with --config removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/480)
> [VCDA-1269] Decouple PKS config from CSE config

- container_service_extension/pksbroker.py
Fixes the KeyError that shows up when creating PKS cluster without providing num_workers.
With this change, PKS cluster creation without specifying num_workers will deploy the plan's specified number of worker nodes instead of failing.
```
Error: <RequestKey.NUM_WORKERS: 'num_workers'>
```
Fixes #483
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/486)
> [VCDA-1274] Change num_workers to be an optional parameter for PKS cluster creation

- container_service_extension/telemetry/vac_client.py
- Client code that can upload CSE metrics to Vmware Cloud Analytics Server (VAC)
- Using this client, CSE can ingest CSE usage data to VAC. The uploaded data can be used for
CSE product analytics.
Testing:
- Tested the code by posting data to VAC staging with the sample collector id and instance id. 
- Verified the posted data which can be viewed using SQL
@andrew-ni @rocknes @sahithi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/482)
> [VCDA-1281] VAC client for CSE

- container_service_extension/config_validator.py
- container_service_extension/telemetry/constants.py
- container_service_extension/telemetry/telemetry_utils.py
- Included Vmware analytics url, instance id and collector id as part of runtime config
- At CSE server startup, vmware analytics url, collector id and instance id are required to post
analytics data. This PR stores url, instance id and collector id in runtime config under 
service --> telemetry 
- Tested and verified manually these values are available in config dictionary.
@andrew-ni @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/490)
> [VCDA-1319] Add vac url, collector id in config at CSE server startup

- container_service_extension/server_cli.py
- system_tests/test_cse_server.py
- Remove password option from Server CLI commands
- As part of security requirement, password should not be provided either as option or argument.
- In this PR, code that accepts password from `CLI option` is removed.
- Password can be provided thru environment variable. In that case, password provided by the environment variable will be used.
- If there is no environment variable set, password from STDIN will be used.
- Server side test cases added to provide password thru both STDIN and environment variable
@andrew-ni @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/491)
> [VCDA-1328] Remove --password option from server CLI commands

- container_service_extension/configure_cse.py
- container_service_extension/request_handlers/cluster_handler.py
- container_service_extension/telemetry/constants.py
- container_service_extension/telemetry/payload_generator.py
- container_service_extension/telemetry/telemetry_handler.py
- container_service_extension/telemetry/telemetry_utils.py
- container_service_extension/telemetry/vac_client.py
- container_service_extension/vcdbroker.py
- Telemetry support for CSE operations 
- Implemented the following
- Framwork code with one decorator for all USER operations
- Framework support  individual CSE commands
- Payload generation and workflow hook for cse install 
- Payload generation and workflow hook for cse cluster list
- Tested the following
- End to End test for cse install ( Both user action table and supplement table)
- End to End test for cse cluster list ( Both user action adn supplement table )
@andrew-ni @rocknes @sahithi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/494)
> [VCDA-1321] Telemetry framework with support for server install and cluster list CSE operations 

- container_service_extension/abstract_broker.py
- container_service_extension/broker_manager.py
- container_service_extension/cloudapi/cloudapi_client.py
- container_service_extension/cloudapi/constants.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/ovdc_utils.py
- container_service_extension/pksbroker.py
- container_service_extension/pksbroker_manager.py
- container_service_extension/pyvcloud_utils.py
- container_service_extension/request_handlers/cluster_handler.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/request_handlers/system_handler.py
- container_service_extension/request_handlers/template_handler.py
- container_service_extension/request_processor.py
- container_service_extension/security.py
- container_service_extension/service.py
- container_service_extension/vcdbroker.py
- requirements.txt
x-vcloud-authorization token has been deprecated for few vCD releases now. It's desirable to use JWT token based authorization instead. This PR adds the capability to parse JWT token from Authorization header in AMQP message, and use the token to create pyvcloud vcd clients which are JWT token based.
Also the cloudapi client has been cleaned up.
Testing done :  
Against a vCD 10.0.0.1 server,
* CSE server starts up normally with api v33.0 (JWT token based) as well as v32.0 (x-vcloud-authorization based). 
* Tested few CSE client commands and they were successful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/496)
> [VCDA - 1340, 1342] Adding support for JWT token for authorization in CSE

- system_tests/test_cse_server.py
As a means of fixing failing system test, disabling the check for the command `cse check [config file] -i `
The test execution looks wrong to me, will need to discuss with team to figure out what to do with this test.
> Disabling cse check install test.

- cse.service
- cse.sh
Added clear security recommendations in `cse.sh` to run CSE using an encrypted config file, where the password is provided as an environment variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/505)
> [VCDA-1362] Edit cse.service and cse.sh to consider config encryption

- container_service_extension/client/cse.py
- container_service_extension/config_validator.py
- container_service_extension/remote_template_manager.py
- container_service_extension/server_cli.py
- container_service_extension/vcdbroker.py
- Update invalid 'k8s_version' cluster key to correct 'kubernetes_version' cluster key in get_all_clusters()
- Update download_file_into_memory() to raise exception on bad status. Fixes vague error messages related to template repository URL errors
- Update convert-cluster and template install help strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/507)
> Fix how Kubernetes version is fetched in get_all_clusters()

- container_service_extension/request_handlers/template_handler.py
- container_service_extension/server_cli.py
Sort `cse template list` command's output in reverse order to group template and their revision together with the latest templates being on top. Also minor change to value in columns local, default, remote, deprecated from True/False to yes/No.
Testing done:
Checked that the output of the concerned commands are sorted correctly and the fields have proper value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/508)
> Sort `cse template list` command's output

- container_service_extension/client/cse.py
- container_service_extension/server_cli.py
- system_tests/base_config.yaml
- system_tests/test_cse_client.py
- system_tests/test_cse_server.py
Change context positional arguments for config file, org name, ovdc name to be required keyword options. This helps with CLI consistency, and allows users flexibility in positioning the necessary context for commands
Testing in progress
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/510)
> Change CLI context arguments to required options

- cse_ui/1.0.0.0b1/manage_plugin.py
Placed ignore rule in the file itself so later we don't have to change the tox.ini when manage_plugin.py is removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/520)
> Add flake8 ignore to manage_plugin.py

- container_service_extension/cloudapi/cloudapi_client.py
- container_service_extension/cloudapi/constants.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/server_cli.py
- container_service_extension/utils.py
Added the following CLI commands to CSE server CLI
* cse ui-plugin register
* cse ui-plugin list
* cse ui-plugin deregister
Additional changes:
* Updated cloudapi client to support Accept header, multiple payload type and arbitrary target url.
* Refactored server cli commands to remove redundant code.
* Updated compute policy manager to accommodate the changes in cloud api
* Added logging support for server cli commands.
Testing Done :
Ran the server cli commands under various scenarios and got the expected results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/524)
> [VCDA-1382] Expose CSE server CLI commands to manage life-cycle of CSE UI plugin

- container_service_extension/server_cli.py
- container_service_extension/service.py
- container_service_extension/telemetry/telemetry_handler.py
- container_service_extension/telemetry/vac_client.py
- Record telemetry data in a separate thread
- Currently, telemetry record data action blocks the main logic of all CSE functions. This PR makes all telemetry related operations non-blocking. This is required to handle the bad latency in case of vac service.
Testing done:
- Verified with working vac url
- Verified with vac_url that times out
- Verified with url that does not exist
@andrew-ni @rocknes @sahithi 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/528)
> [VCDA-1400] Post the telemetry data in a separate async thread

- container_service_extension/vcdbroker.py
This change is required for photon k8s upgrades. Photon allows for differences between the same semantic version of kubernetes, so this allows upgrades from 1.14.6-2 -> 1.14.6-3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/521)
> Change cluster upgrade k8s version check to >=

- container_service_extension/client/cse.py
- container_service_extension/request_handlers/cluster_handler.py
Commands like 
vcd cse cluster upgrade / upgrade-plan
vcd cse node create / delete / info
if invoked on non native clusters would result in an error message 'Cluster not found', which is not very helpful.
This PR fixes the error messages to explicitly state the cause of failure.
Testing done:
Created a Enterprise PKS cluster and ran the commands mentioned above to make sure that the error messages are descriptive and as expected.
(cse) C:\code\container-service-extension>vcd cse cluster upgrade-plan pks_test_cluster
Usage: vcd cse cluster upgrade-plan [OPTIONS] CLUSTER_NAME
Try "vcd cse cluster upgrade-plan -h" for help.
Error: 'cluster upgrade-plan' operation is not supported by non native clusters.
--- …
> [VCDA-1381] Fix error message on triggering invalid operation on non native clusters

- NOTICE.txt
- open_source_license_container-service-extension_2.6_GA.txt
- setup.py
Updated
* LICENSE
* NOTICE
* OSL 
for CSE 2.6.0 GA release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/526)
> [VCDA-1365] Update OSL files of 2.6.0 GA

- container_service_extension/sample_generator.py
- system_tests/base_config.yaml
- For CSE 2.6.1, `cse sample` should set the value of `remote_template_cookbook_url` with master branch url of container-service-extension repository, in sample configuration output. ( broker -->   remote_template_cookbook_url)
- Tested and verified the command output
@andrew-ni  @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/523)
> [VCDA-1377] remote template url set to master template repo

- container_service_extension/telemetry/constants.py
Signed-off-by: Sakthi Sundaram sakthisunda@yahoo.com
Changed the default telemetry endpoint to production VAC url
Tests done
- Manually tested with production url with successful POST
- Tested with staging end point as override url thru configuration
@rocknes @andrew-ni @Anirudh9794 @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/547)
> [VCDA-1424]Change default Telemetry end point to VAC Production

- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/vcdbroker.py
Following changes for `vcd cse cluster resize` command
- Added --cpu / -c option
- Added --memory / -m option
- Added --ssh-key / -k option
Testing done:
- `vcd cse cluster resize -N 4 -c 4 -m 4096 -k ~/.ssh/id_rsa.pub -n mynet mycluster `
- `vcd cse cluster resize -N 4 -n mynet clust1`
- `vcd cse cluster resize -c 4 -N 5 -n mynet clust1`
- `vcd cse cluster resize -m 4096 -N 5 -n mynet clust1`  (Adding 2 nodes)
- `vcd cse cluster resize -k ~/.ssh/id_rsa.pub -N 6 -n mynet clust1`
@rocknes @andrew-ni @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/548)
> Add cpu, memory and ssh keys option for cluster resize

- container_service_extension/client/cluster.py
- container_service_extension/client/cse.py
- container_service_extension/vcdbroker.py
Following changes for `vcd cse cluster resize` command
- Added --cpu / -c option
- Added --memory / -m option
- Added --ssh-key / -k option
Testing done:
- `vcd cse cluster resize -N 4 -c 4 -m 4096 -k ~/.ssh/id_rsa.pub -n mynet mycluster `
- `vcd cse cluster resize -N 4 -n mynet clust1`
- `vcd cse cluster resize -c 4 -N 5 -n mynet clust1`
- `vcd cse cluster resize -m 4096 -N 5 -n mynet clust1`  (Adding 2 nodes)
- `vcd cse cluster resize -k ~/.ssh/id_rsa.pub -N 6 -n mynet clust1`
@rocknes @andrew-ni @sakthisunda
> [VCDA-1257] Add cpu, memory and ssh keys option for cluster resize

- container_service_extension/vcdbroker.py
- Template values for memory were recorded in cluster create and node create operations instead of user supplied ones
- Made changes to use validated_data values instead of template values when recording telemetry details
added a debug statement to check 'cse_params' for
- vcd cse cluster create -o myorg -v myorgvdc -n mynet -t ubuntu-16.04_k8-1.15_weave-2.5.2 -r 3 -c 3 -m 4096 clus6
- vcd cse node create -c 4 -m 4096 -t photon-v2_k8-1.14_weave-2.5.2 -r 2 -n mynet clus1
@rocknes @andrew-ni @sakthisunda @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/555)
> [VCDA-1432] fix for recording incorrect telemetry details

- requirements.txt
Bumped up pyvcloud requirement to 22.0.1
Testing done:
Created a whl file from the top of cse.2.6.0_ga branch, installed it and verified that pip is pulling the latest pyvcloud build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/556)
> Update pyvcloud requirement to 22.0.1 for 2.6.0 GA

- requirements.txt
Update pyvcloud requirement to 22.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/559)
> Update pyvcloud requirement to 22.0.1

- container_service_extension/client/cse.py
- container_service_extension/pksbroker.py
- container_service_extension/request_handlers/cluster_handler.py
- container_service_extension/vcdbroker.py
- Fixed bug in pksbroker._get_token() error handling where `requests.code` was used instead of `requests.codes`. This issue would appear if the user's CSE-PKS integration was set up incorrectly
- Updated cluster list API to send back 'k8s_type' data
- Updated CLI cluster list to display cluster's Kubernetes and display more user friendly headers
Before this change:
After this change:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/557)
> [VCDA-1451] Update cluster list to show Kubernetes info

- container_service_extension/abstract_broker.py
- container_service_extension/broker_manager.py
- container_service_extension/pksbroker.py
- container_service_extension/request_handlers/cluster_handler.py
- container_service_extension/server_constants.py
- container_service_extension/telemetry/payload_generator.py
- container_service_extension/vcdbroker.py
- - Avoid multiple calls to record telemetry details. Happens because the following functions which are supposed to be only by the request_processor are used in other functions as well:
- get_cluster_info
- create_nodes
- get_cluster_upgrade_plan
- broker functions will now accept kwargs which can have data along with telemetry flag.
- record telemetry details only if telemetry flag is set
- testing done:
added debug statements to check if multiple calls to record telemetry are being made
`vcd cse cluster resize -N 3 -n mynet clus3`
`vcd cse cluster list`
`vcd cse cluster info clus3`
`vcd cse node info clus3 mstr-xkfv`
@rocknes @andrew-ni @sakthisunda @sahithi …
> [VCDA-1431] resolve multiple telemetry calls

- system_tests/test_cse_client.py
- client tests did not include tests for resizing the cluster
- Added tests for resize cluster for the following cases:
- if number of workers is increased by 1 (command should execute)
- if zero workers are given (command should fail with an error)
- if N is number of currently existing workers (command should fail with an error)
Testing done:
- `pytest --disable-warnings -x -v -s test_cse_client.py > testlog`
- @rocknes @andrew-ni @sakthisunda @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/560)
> [VCDA-1457] Add tests for cluster resize

- container_service_extension/local_template_manager.py
- container_service_extension/server_cli.py
- container_service_extension/vcdbroker.py
- Fixed cluster metadata with right docker and k8 version after convert cluster operation
- Clusters created with CSE 2.5.1 or earlier versions require `cse convert-cluster` to get the
right metadata during upgrade of CSE 2.6.9.  In this fix, the converted cluster gets 
updated metadata with correct docker version and k8 version.
Before this fix, k8 version got wrongly set to 0.0.0.
- Tested and verified by manually : created ubuntu cluster with CSE 2.5.1, 
then upgrade to CSE 2.6.0, applied `cse convert-cluster` on the cluster and verified the fix.
Itempotency on cluster convert tested
Cluster convert now updates cluster k8 and docker version with corresponding values from template metadata. Else fallback to default values.
> [VCDA-1486] Fix convert cluster showing incorrect kubernetes version

- container_service_extension/client/cse.py
- Split cluster list 'Kubernetes' column into 'K8s Runtime' and 'K8s Version'. This allows us to display PKS cluster Kubernetes version
- Previously, since PKS get cluster payload did not give us a Kubernetes runtime or Kubernetes version, we just displayed 'N/A' for the entire 'Kubernetes' column.
Cluster list:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/575)
> Fix cluster list to show PKS cluster k8s version

- container_service_extension/client/cse.py
- container_service_extension/client/pks.py
- container_service_extension/request_handlers/ovdc_handler.py
- system_tests/test_cse_client.py
- Ovdc enable for Ent-PKS moved to PKS command group 
- New command for ovdc enable Ent-PKS separated from `vcd cse ovdc enable`
vcd cse pks ovdc ( set K8 provider to be Ent-PKS)
vcd cse pks cluster [config|create|delete|info|list|resize]
Removed option --k8s_provider
Updated help and doc string 
Exception on setting Ent-PKS k8 provider to ovdc already enabled for native k8 provider
Test case update
- Tests Done
Automated System tests
`vcd cse pks ovdc` command on that is none, already enabled for native K8
`vcd cse ovdc enable` commands
Cluster tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/576)
> [VCDA-1488] Separate ovdc enable for Ent-PKS

- system_tests/base_config.yaml
Update base_config.yaml to lay down the foundation of running tests in a separate org from the org that hosts the native templates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/579)
> Update base_config.yaml to lay down the foundation of running tests in a separate org

- container_service_extension/telemetry/constants.py
Change default Telemetry end point to VAC Production
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/582)
> Change default Telemetry end point to VAC Production

- container_service_extension/compute_policy_manager.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/request_handlers/pks_cluster_handler.py
- Missing admin client on ovdc setttings for PKS. 
- Manually tested and verified ovdc enable/disable on PKS and cluster operations
@andrew-ni @Anirudh9794 @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/585)
> Fix for missing admin client on ovdc update

- container_service_extension/config_validator.py
- container_service_extension/server_cli.py
- container_service_extension/server_constants.py
Added logic in CSE config validator to validate that the vCD api version specified in the configuration file under `vcd` section is supported by CSE. For CSE 3.0, the values will be '33.0', '34.0' and '35.0'
Testing Done:
Ran the command `cse check` with various values of the vCD api version and made sure that the error messages are correct
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/604)
> [VCDA 1528] Added vCD api version check to CSE config validator

- container_service_extension/service.py
Template rules will be deprecated from CSE 3.0. As a result we should not process them if vCD api version 35.0 or above is specified in the config file.
Testing Done:
Tried to start up CSE server with api v33.0 and v35.0 and made sure that the template rules are not process in case api v35.0 was used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/605)
> [VCDA-1536] Suppress template rule checking for api v35 and above

- docs/RELEASE_NOTES.md
Updated release notes to include the update/patch releases of supported vCD versions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/607)
> Update CSE-vCD compatibility matrix to add patch/update releases of supported vCD versions

- container_service_extension/configure_cse.py
- container_service_extension/exceptions.py
- container_service_extension/server_cli.py
- container_service_extension/service.py
- container_service_extension/telemetry/constants.py
This PR is coded on top of my existing PR that I cannot merge in yet because it would break our system tests. This means that code from that PR is also shown as new code in this PR. Once the existing PR is merged in, i’ll fix any merge conflicts and merge this PR in as well.
I’ve only implemented the staple behaviors that every CSE upgrade would have, such as config/clients fetching, checking version compatibility, re-registering CSE to VCD (to update things like url pattern changes), and telemetry.
I’ve added a TODO where the arbitrary upgrade steps should be “plugged-in”, such as:
- Update existing Kubernetes cluster representation on VCD
- Update existing placement and sizing policies used by CSE
- Register defined entities schema to VCD
- Install templates from template repository …
> [VCDA-1516] Add base code for CSE upgrade

- container_service_extension/template_builder.py
- container_service_extension/vcdbroker.py
vCD recently consumed VC 7.0 imgcust build. The new imgcust build has a severe bug in it, and as a result guest customization(GC) is in broken in vCD. CSE uses GC to create k8s templates as well k8s clusters. This bug impacts CSE directly and hampers most basic workflows in CSE. To counter this issue, this PR removes all usage of GC in CSE and replaces them with vanilla script execution in vm via vCenter.
Testing done:
Created kubernetes 1.17 template - result : template creation successful
Created a cluster off the same template - result : cluster creation successful
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/618)
> Workaround for GC bug in vCD leading to template creation failure

- container_service_extension/sample_generator.py
- system_tests/base_config.yaml
- remote_template_cookbook_url changed to upgrades branch copy
- sample_generator.py and base_config.yaml
@andrew-ni @rocknes @andrew-ni @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/620)
> [PR] Remote template url change

- container_service_extension/def_/cluster_service.py
- container_service_extension/def_/entity_service.py
- container_service_extension/service.py
- container_service_extension/shared_constants.py
Make use of existing sizing policy for creation of master and worker nodes instead of the old way of specifying num_cpu and memory.
- Change `add_nodes()` in `def_/cluster_svc.py` to support sizing policy and remove memory and cpu parameters
Testing done:
- created sizing policies and published to ovdcs in the UI
- created cluster from Postman using the sizing policies and made sure sizing policies were used for creation of cluster nodes
@sahithi @rocknes @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension …
> [VCDA-1518] Use sizing_class for creation of VMs in the cluster

- system_tests/base_config.yaml
- system_tests/test_cse_client.py
- system_tests/test_cse_server.py
* Change _remove_cse_artifacts() to skip photon
* Skip tests   test_0100_install_force_update
* Modified test_0090_install_retain_temp_vapp
* Change pytest fixture cse_server() : Skip installation of templates and manually install only the default template
*  change default template from photon template to an ubuntu template in 
@rocknes @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/627)
> Skip Photon template installation during system tests

- container_service_extension/client/cluster.py
- container_service_extension/client/command_filter.py
- container_service_extension/client/cse.py
- container_service_extension/client/pks.py
- container_service_extension/client/utils.py
- container_service_extension/service.py
- container_service_extension/shared_constants.py
- CSE has own restore session that replaces vcd_client with server side api version (utils.py)
- Separate module - command_filter.py for client side CSE commands,options filtering
- service.py to also return server api version
- cse.py, pks.py changes to use new restore session.
- Fixed cluster_create() missing 2 required positional arguments: 'cpu' and 'memory'
- Manually tested the commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/623)
> [VCDA-1572] CLI-To-Use-CSE-Server-Api-Version

- container_service_extension/configure_cse.py
- container_service_extension/server_cli.py
- container_service_extension/server_constants.py
- container_service_extension/service.py
- container_service_extension/utils.py
- requirements.txt
Introduced new `cse upgrade` command. Henceforth, 'cse install' will only serve fresh installations.
Upgrade will take into account the version of CSE that is already installed, along with the vCD api version that was used to install it. Depending on the starting configuration, the upgrade command will branch out into different logic families to bring CSE upto it's latest version.
Testing:
Tested basic use cases of mismatched upgrade versions and code flow.
Todo - Complete testing of all use cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/624)
> [VCDA-1544, 1546] CSE upgrade command

- container_service_extension/def_/cluster_service.py
- container_service_extension/request_handlers/v35/def_cluster_handler.py
- container_service_extension/request_processor.py
- container_service_extension/shared_constants.py
1. Implemented Delete cluster operation for new v35 endpoint.
Other fixes:
1. Replaced compute-intensive _get_cluster()_ with _get_native_entity_by_name()_ to check if cluster already exists in _create_cluster_ operation.
2. Fixed index out of range exception in _request_processor.py_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/636)
> VCDA-1589 Implemennt cluster-delete new endpoint.

- container_service_extension/compute_policy_manager.py
- container_service_extension/request_handlers/ovdc_handler.py
- Having operation context in compute policy manager reduces flexibility of use.
- Ovdc_handler will follow the task that compute policy manager create (for removing compute policy from vdc) and ends operation context in a separate thread.
@rocknes @sahithi @andrew-ni @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/637)
> Remove operation context from compute policy manager

- container_service_extension/def_/cluster_service.py
- container_service_extension/request_handlers/v35/def_cluster_handler.py
Change upgrade cluster to update defined entities.
- Change cluster handler to parse in cluster spec for update-cluster and upgrade plan
- Use defined entity in the update operation
Testing done:
- create a cluster using postman for api v 35 and 10.2 vcd. Update the cluster using the endpoint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/635)
> [Vcda 1541] upgrade cluster workflow

- container_service_extension/configure_cse.py
- container_service_extension/def_/entity_service.py
- container_service_extension/def_/models.py
- container_service_extension/def_/utils.py
- container_service_extension/service.py
Make use of built in kubernetes interface for creating native cluster defined entity type
Testing done:
`cse upgrade -c config -st`
checked to see if kubernetes interface was loaded on `cse run`
@sahithi @sakthisunda @rocknes @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/641)
> [VCDA-1580] Move to pre-defined kubernetes interface

- system_tests/test_cse_client.py
Remove enabling ovdc in system test as ovdc enable / disable is not supported for API version < 35.
@sahithi @sakthisunda @rocknes @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/645)
> Fix ovdc enable bug in system tests

- container_service_extension/client/cse.py
- container_service_extension/client/native_cluster.py
- CLI implementation for generating sample cluster config and resize for apply command
- Usage: vcd cse cluster apply [OPTIONS]
Example:vcd cse cluster apply input_spec.yaml
Example:vcd cse cluster apply --sample
Example:vcd cse cluster apply -s -o output.yaml
------
Options:
-s, --sample                   generate sample cluster configuration file;
This flag can't be used together with -f
-o, --output OUTPUT_FILE_NAME  Filepath to write sample configuration file
to; This flag can only be used with -s
-h, --help                     Show this message and exit.
-----
- Manual testing completed
- Dependency on [VCDA1590] Cluster create and resize support to handle 0 worker nodes
------
--- …
> [VCDA 1595,1603] apply - generate sample file, resize cluster CLI implementation

- system_tests/test_cse_client.py
- Fixed failing cluster resize with no worker node
-  `vcd cse cluster resize -N 0` is a valid test case. Changes made to check proper exit code. Also, removed redundant test case of scale down as -N 0 takes care of scale down as well.
-   Also updated test case to support `vcd cse cluster create -N 0` 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/656)
> [PR] CTOT Fix - cluster resize with no worker node is a positive test case

- container_service_extension/vcdbroker.py
- system_tests/test_cse_client.py
Some of the client tests were modified recently that broke other tests that were depending on the first set of tests viz. resizing cluster to 0 worker nodes. The following PR fixes the test dependencies.
Testing Done:
Verified that a manual CToT run with the fix is stable and green.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/662)
> Fix failing CToT

- container_service_extension/client/command_filter.py
- Hide ovdc info command as it doesn't display any more information than list
- Add a command filter for ovdc info for v33, v34 and v35
checked if `vcd cse ovdc -h` doesn't show info as a subcommand
checked if `vcd cse ovdc info` will give command not found
@sakthisunda @sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/663)
> [VCDA-1596] Hide ovdc info command as it doesnt display any more info than list

- container_service_extension/client/command_filter.py
- container_service_extension/client/cse.py
- Ignore `vcd cse node ...` commands for api version >= 35
- Created command level filter for cse and ignored the  `node` command for apiVersion >= 35
Sample output:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/672)
> [VCDA-1517] Ignore cse node commands for api version 35

- container_service_extension/client/cse.py
- container_service_extension/client/def_entity_cluster_api.py
- container_service_extension/def_/models.py
-  Include owner name cluster list CLI
-  `vcd cse cluster list` has included owner of def entity 
- removed enable_nfs from cluster_entity->settings
- type hints added dataclass for successful instance creation with all properties
- Manually tested 
-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/679)
> [VCDA-1671] Def entity owner as part of console display on cluster list CLI

- container_service_extension/compute_policy_manager.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/def_/ovdc_service.py
- container_service_extension/service.py
- container_service_extension/template_builder.py
- requirements.txt
* Mark the templates with placement policy as non modifiable
- Set the flag `placement_policy_final` to True when assigning placement policies to the templates.
* Server config cache in the placement policy href for the kubernetes runtimes available
* Specify the respective placement policy which is obtained from the server runtime config during cluster creation
- spec for vapp.add_vm() should also specify the placement policy
* Ovdc disable to set sizing policy when only placement policy is present in the VM (Cannot remove placement policy directly if it is the only policy present in the VM)
- check if the vm has a sizing policy before removing the placement policy. If not present, set the sizing policy to default sizing …
> [VCDA-1681] cluster restriction with placement policies fixed

- container_service_extension/client/legacy_native_cluster_api.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/def_/models.py
- container_service_extension/vcdbroker.py
Once DEF entities are created corresponding to existing native CSE k8s clusters, the owners of the cluster should be assigned appropriate DEF RBAC rights so that they can continue to interact with the clusters with CSE 3.0. Added a new section in the upgrade process that lists users per org who needs the new rights.
Also the following changes were made in this PR
* Display cluster owner information in output of `vcd cse cluster list` for api version 33.0 and 34.0
* Get rid of the default values in Distribution class that were dependent on CSE server being running.
Testing Done:
Ran upgrade and verified the list of user is printed at the end of upgrade process.
--- …
> [VCDA-1515] Report users at the end of CSE upgrade who needs to be assigned DEF entity RBAC rights

- container_service_extension/request_handlers/request_utils.py
- container_service_extension/request_handlers/v35/def_cluster_handler.py
- container_service_extension/shared_constants.py
- container_service_extension/utils.py
-  Validate the defined entity payload PUT requests
-  Process the PUT requests payload and raise error on encountering invalid value with reference to current state of the cluster.
- Currently generates generic error message with key->value that fails first in the validation (screenshot below)
- Tested with `vcd cse cluster apply` and `vcd cse cluster upgrade` with incorrect payloads 
----------------
Most recent console output after all review comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/671)
> [VCDA-1645] Validate PUT Def Entity Payload

- container_service_extension/utils.py
-  Fixed the broken input validation
-  Error reproduced. Fixed passing the parent key while flattening  
- Tested again using `vcd cse cluster apply`
@Anirudh9794 @sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/687)
> [VCDA-1731-TestFest]  Input-validation-error-for-cluster-resize 

- setup.py
Currently if a whl package is created for CSE and installed, `cse install` command will fail because the CSE DEF schema file is not packaged in the whl file. This PR fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/688)
> Add cse def schema to CSE whl package

- container_service_extension/client/command_filter.py
- container_service_extension/client/constants.py
- container_service_extension/client/cse.py
- container_service_extension/client/tkg_cluster_api.py
- container_service_extension/client/utils.py
- container_service_extension/exceptions.py
- container_service_extension/shared_constants.py
Decisions made:
* When run for the first time, the cse cli tries to contact cse server. If the server is not running, it will set the flag `cse_server_running` in profiles.yaml
* Subsequent calls will first check two keys `cse_server_running` and `cse_server_api_version` in the profiles yaml
* If CSE server is not running, all the cli calls will land to `tkg_cluster_api.yaml`
* If the CSE server starts running after the flag `cse_server_running` is set, the user has to log out
Screenshot:
--- …
> [VCDA-1704] Default down to tkg only operations when cse server is not running

- container_service_extension/client/cse.py
This PR fixes an error where no value is passed to the flag parameter enable-tkg-plus and disable-tkg-plus for ovdc_enable() and ovdc_disable() functions in cse.py.
Testing done:
checked if `vcd cse ovdc enable` and `vcd cse ovdc disable` commands are 
* showing correct options with and witout `CSE_TKG_PLUS_ENABLED` environment variable set
* no error is thrown when the commands are executed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/695)
> Set default values for hidden tkg-plus options

- container_service_extension/configure_cse.py
- container_service_extension/utils.py
TKG PLUS is not available to CSE users by default. As a result, any reference to it should not show up on console. The two major operations where TKG PLUS related messages are dumped onto console are 1. CSE install, 2. CSE upgrade. In this PR both these workflows have been modified to suppress the messages unless a particular flag is found in the config file.
Testing done:
Ran the workflows with and without the flag in the config file and verified that the messages are showing up on the console only if the flag is set to True.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/693)
> [VCDA-1695] Hide references to TKG PLUS unless opt-ed in

- container_service_extension/client/constants.py
- container_service_extension/client/def_entity_cluster_api.py
- container_service_extension/client/tkg_cluster_api.py
- container_service_extension/client/tkgclient/api/tkg_cluster_api.py
CLI changes to get TKG cluster config
* Added a method in TKG client for creating task for TKG kubeconfig
* Handle fetching the kubeconfig from the task in tkg_cluster_api.py
NOTE: only sys admin can create the task for creating th kubeconfig. So as of now, this changes only works for sysadmin user
Testing Done:
Fetch kubeconfig of a TKG cluster
@sahithi @rocknes @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/702)
> [VCDA-1622] TKG cluster get config operation from CLI

- container_service_extension/consumer.py
- container_service_extension/request_processor.py
CSE currently expects only a single value in the Accept header. Multiple values result in a 406. This behavior is not in line with HTTP standard. This PR adds support in CSE to handle multiple values for Accept header and pick the one that is serviceable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/705)
> Add support for handling multiple Accept headers in incoming requests

- container_service_extension/client/cse.py
- container_service_extension/request_handlers/template_handler.py
Currently template list endpoint only returns a handful of fields to describe a template. This info is not enough for UI plugin. This PR improves the template list endpoint to return complete template definition.
Testing done:
Ran vcd cse template list to make sure regression hasn't been introduced
Made GET /api/cse/3.0/templates call using POSTman to verify that template definitions are now complete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/707)
> Modify the template list endpoint to return entire template definition

- container_service_extension/client/command_filter.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/request_handlers/v35/def_cluster_handler.py
- container_service_extension/telemetry/constants.py
- container_service_extension/telemetry/payload_generator.py
- container_service_extension/telemetry/telemetry_handler.py
- Record telemetry data for defined entities
- Record telemetry data for CLI that uses server side DEF entity operations when CSE server is up and running.
- Tested manually using Super Collider Staging SQL workbench
- Tested with postman for telemetry on cluster list, info, node delete
- Tested for telemetry on api version 33/34 to make sure that they are recorded with existing VAC tables
with collector id CSE.3_0. 
- Hide 'resize' subcommand from `vcd cse cluster` for api version 35.
- Few screen shots of recorded data in table format ( actions and details)
-----------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/699)
> [VCDA-1564] Telemetry for defined entities

- container_service_extension/def_/cluster_service.py
-  Fix for exceptions displayed on server console
-  Fixed root cause of the exception on server console. Resolve the defined entity only when rollback is false. 
-  Issue was sucessfully reproduced and tested
- Verified the fix worked with no exception displayed on server console.
- Tested with all cluster operations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/711)
> [VCDA-1771] Fix async operations printing exceptions onto console

- container_service_extension/configure_cse.py
Currently sys admin creates the defined entities for existing k8s clusters during cse upgrade. This PR transfers the ownership of these newly created defined entities to the cluster owner.
Testing done:
Created cluster as org_admin
Ran cse upgrade
Verified that the defined entity created as part of cse upgrade process belongs to org_admin and not administrator (sys admin)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/710)
> [VCDA-1652] Transfer ownership of defined entity to cluster owner during cse upgrade

- container_service_extension/configure_cse.py
- container_service_extension/service.py
Few of the previous PRs has caused regressions in cse install/upgrade/run functionallity. This PR fixes those issues.
1. Wrong constant used during CSE install/upgrade to create/read placement policies
2. During CSE server startup, missing TKG PLUS placement policy is not handled.
Testing done:
With the fixes, cse install/upgrade/run works correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/713)
> Fix regression related to cse install/upgrade/run

- container_service_extension/compute_policy_manager.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/def_/ovdc_service.py
- container_service_extension/request_handlers/ovdc_handler.py
* Users could not associate system default sizing policy to sizing classes because filters used with the compute policies endpoint is not working for System default policy.
* Solution: iterate over all the sizing policies and avoid the name filter.
Testing done:
Created a cluster with system default sizing policy as sizing class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/717)
> Filx for enabling cluster creation with system default policy

- container_service_extension/client/def_entity_cluster_api.py
- container_service_extension/client/native_cluster_api.py
- container_service_extension/client/tkg_cluster_api.py
- container_service_extension/client/tkgclient/api_client.py
- container_service_extension/client/utils.py
Fixes for the following included:
* Exception with message "User cannot access native or TKG clusters. Please contact administrator" raised when user doesnt have native or tkg rights (helps in cluster list and info)
* Console output for cluster write operations (upgrade, apply and delete) will print a task_href on the console instead of the whole cluster entity
* TKG cluster info output used to return snake case. The output from defined entities should be shown as is (which is in camel case)
- There is no need for additional data parameter which was introduced to send in tkg defined entity details. Have removed it from the tkg client
Testing done:
TKG cluster:
* list, cluster info , delete and apply commands to see if the …
> [VCDA-1772, VCDA-1734, fix snake case output] Exception when no rights, fix write operation task output

- container_service_extension/client/cse.py
- container_service_extension/client/legacy_ovdc.py
- container_service_extension/client/ovdc_policy.py
- container_service_extension/client/pks.py
- container_service_extension/client/pks_ovdc.py
- container_service_extension/request_processor.py
* Currently, with api version 35, legacy ovdc commands wont work because the request will be rejected by the server. The legacy ovdc enablement is required for enabling PKS in the ovdc.
* updated CLI and Server code so that pks commands can enable and disable the ovdc
* Testing done: Executed pks ovdc commands and checked if the server is working fine with pks/ovdc API calls from postman
@rocknes @sahithi @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/719)
> Enable pks ovdc commands for v35

- container_service_extension/sample_generator.py
- container_service_extension/system_test_framework/environment.py
- system_tests/base_config.yaml
Enabling an user via PUT /api/admin/user/{id} causes their vm quota to be set as 0. This is a bug in vCD. Until the vCD bug is fixed, CSE system test will avoid enabling the user as a separate step.This change should fix the failing system tests against vCD 10.2
> Fix failing CToT against vCD 10.2

- container_service_extension/client/cse.py
- container_service_extension/client/native_cluster_api.py
- container_service_extension/client/tkg_cluster_api.py
* Sysadmins cannot deploy TKG clusters because they need to specify a non-system org context while deployment
* Introduce an --org flag to help sysadmins explicitly specify the deployment org, which is only useful for TKG cluster creation.
* Testing done:
Created a TKG cluster as an administrator by specifying an org through the --org flag.
Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/722)
> [VCDA-1775] Add --org option for cluster apply to help sysadmin specify deployment org for TKG

- container_service_extension/client/tkg_cluster_api.py
-  Change `tkgCluster` to `TanzuKubernetesCluster` in CLI output`vcd cse cluster list`
--------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/736)
> [VCDA-1811] Change tkgCluster to TanzuKubernetesCluster in CLI output

- container_service_extension/client/def_entity_cluster_api.py
- container_service_extension/cloudapi/cloudapi_client.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/def_/entity_service.py
Currently, defined entities for clusters which are created by system administrators are created in system org. This PR makes changes so that the defined entities are created in specific orgs instead of system org.
Testing done:
1. Verified that if cluster is created by system administrator, its corresponding defined entity doesn't get created in system org.
2. Tested if clusters are upgraded, its corresponding entities are not created in system org,
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/738)
> [VCDA-1793] Create defined entities in specific org when sysadmin creates a cluster

- container_service_extension/client/tkg_cluster_api.py
* Currently for all TKG cluster update operation, a new field `resourceVersion` should be added before `vcd cse cluster apply` is called. This PR removes the need for manually fetching the field and updating it.
* Testing done: Tested whether the update operation for TKG goes through successfully with different users.
@sakthisunda @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/730)
> [VCDA-1720] Add resource version to the request before update operation for TKG

- container_service_extension/client/cse.py
- container_service_extension/client/sample_generator.py
- Moved command examples at group level to respective subcommands
- Due to restrictive nature of command/subcommand support by API version and environment variable flags, subcommands may be hidden, unsupported. Moving the examples from group level to sub-command level ensures help option to display the examples wherever the command is supported.
- Fixed `vcd cse apply --sample` for offensive terminology
- Tested with API versions(34.0 and 35.0).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/737)
> [VCDA-1812] Move command examples from Group level to relevant subcommands

- container_service_extension/client/cse.py
- container_service_extension/client/ovdc_policy.py
- container_service_extension/client/utils.py
-  Fixed order of output columns on CLI tabular results wherever it is not handled
-  Fixed ovdc list and node list having wrong column formats. 
----------
---------------
Node list before fix:
Node list after fix:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/745)
> [VCDA-1794] Order-of-output-columns-fixed

- container_service_extension/client/pks.py
- Fixed broken `vcd cse pks ovdc disable` 
- k8_provider is not required as it is taken care by the ovdc_disable() handler.
---- Before fix
---- After fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/748)
> [VCDA-1831] Fixed broken vcd cse pks ovdc disable command

- container_service_extension/client/command_filter.py
- container_service_extension/client/cse.py
- container_service_extension/client/def_entity_cluster_api.py
- container_service_extension/client/legacy_native_cluster_api.py
- container_service_extension/client/native_cluster_api.py
- container_service_extension/client/tkg_cluster_api.py
- container_service_extension/def_/entity_service.py
* Commands affected:
* cluster apply
* cluster delete
* cluster config
* cluster info
* Testing done: Checked if the above commands with and without id are working fine
* Screenshot:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/749)
> [VCDA-1787] Add --id option for cluster commands

- requirements.txt
Update pyvcloud requirement to 22.0.2.dev31 to consume the changes to query api filter for api v35.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/754)
> Update pyvcloud requirement to 22.0.2.dev31

- container_service_extension/client/command_filter.py
* hiding `vcd cse ovdc list` command for vcd api version 33 and 34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/756)
> Hiding ovdc list command in api v 33 and 34

- container_service_extension/client/cse.py
- container_service_extension/client/native_cluster_api.py
- container_service_extension/client/tkg_cluster_api.py
* Fix incorrect error messages being shown
* Indicate that --id flag has more precedence than the cluster name
* Fix parameter for cluster upgrade in native_cluster_api.py
Testing done:
* Checked if correct error messages are shown in the CLI.
* Checked if cluster upgrade endpoint in cse server is being called with `--k8-runtime native` set.
@sakthisunda @sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/764)
> Fix error messages and upgrade command for native

- container_service_extension/cloudapi/cloudapi_client.py
- container_service_extension/cloudapi/constants.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/exceptions.py
- container_service_extension/right_bundle_manager.py
- container_service_extension/template_builder.py
* If `cse upgrade`is done with templates created with new metadata already present, CSE will contain templates which can be deployed even without enabling an OVDC. To prevent this, if the user skips template installation, tag the already existing templates with relevant placement policies.
* Testing done:
- created templates with current upgrades branch and ran cse upgrade with skip template creation option. Checked if the templates are being tagged with proper placement policies
- created a template after the upgrade to see if the newly created template is properly tagged with placement policies.
--- …
> [VCDA-1849] CSE upgrade to tag templates with placement policy when template creation is skipped

- container_service_extension/client/tkg_cluster_api.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/def_/entity_service.py
- container_service_extension/pyvcloud_utils.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/right_bundle_manager.py
- container_service_extension/utils.py
- container_service_extension/vcdbroker.py
- requirements.txt
CSE uses get_typed_query method of pyvcloud's client, however right now CSE is not url encoding the values of the query filter values. This PR fixes the gap in query filter usage in CSE.
Additionally all cloudapi calls that leverage queries have been updated to follow the same scheme.
Testing done:
Ran CSE commands including server side cli commands against vCD 10.0, 10.1 and 10.2 to make sure that no regression has been introduced.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/763)
> [VCDA-1858] Encode value for query filter expressions

- container_service_extension/sample_generator.py
Update sample config api version from 33.0 to 35.0.
Add note for template rule section support.
Testing Done:
Ran `cse sample` and confirmed sample api version is 35.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/762)
> [VCDA-1848] Update sample config api version to 35.0

- container_service_extension/configure_cse.py
- container_service_extension/def_/ovdc_service.py
- container_service_extension/local_template_manager.py
- container_service_extension/server_cli.py
- container_service_extension/service.py
* Some of the TKG+ operations can still be performed if the server is first installed with `enable_tkg_plus` option set to true and later disabled.
* Disable TKG+ operations from CSE server if TKG+ is not enabled in CSE server.
If TKG+ is not enabled
* Prevent loading of TKG+ template.
* Prevent TKG+ ovdc updates.
* Skip TKG+ in the output for OVDC list
Testing done:
* checked if ovdc list doesn't give TKG+ if there is already an OVDC enabled with TKG+ ( tkg+ disabled)
* checked if TKG+ templates are not being loaded during runtime (tkg+ disabled)
* checked if OVDC update operations throw exception if TKG+ policies are updated (tkg+ disabled)
* checked if the …
> [VCDA-1868] Server side changes to handle when TKG+ is swithced off

- container_service_extension/def_/cluster_service.py
- Prevent runtime error(s) on getting cluster config when the respective DEF entity is not in Resolved state
- This fix checks if the entity is resolved before getting the configuration else throw custom error
- Verified manually when cluster creation in progress, cluster not in resolved state.
------- Before fix---------
------------------------------After fix-------------------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/769)
> [PR] Get cluster configuration only on resolved DEF entity

- container_service_extension/def_/cluster_service.py
- container_service_extension/vcdbroker.py
* When defined entity create/update fails in the sync portion of cluster operations, the task will be left in Running state forever
* Fix by adding exception handling to update tasks if defined entity create/ update fails
Testing done:
* create (with and without rights)
* resize (with and without rights)
* delete (with and without rights)
* upgrade (with and without rights)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/774)
> Update task to error if defined enttiy update / create fails

- container_service_extension/def_/cluster_service.py
- container_service_extension/server_cli.py
- container_service_extension/telemetry/constants.py
- container_service_extension/telemetry/payload_generator.py
Update VAC url in CSE to use prod instead of staging.
Fix few bugs related to telemetry.
Testing done:
Ran all workflows at api v35.0 and made sure that telemetry data is ingesting in the prod tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/757)
> Move to VAC production for telemetry

- container_service_extension/client/sample_generator.py
- update default nfs count to 0 for output of `vcd cse cluster apply --sample --native` 
@Anirudh9794 @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/781)
> [PR] sample cluster configuration: nfs count default set to 0

- docs/cse2_6/TEMPLATE_ANNOUNCEMENTS.md
- docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md
* Add information in the doc that template ubuntu-16.04_k8-1.15_weave-2.5.2 will be deprecated in future update
@sahithi @rocknes @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/790)
> Add information about deprecation of templates

- requirements.txt
Consume pyvcoud 23.0.0 and vcd-cli 24.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/789)
> [VCDA-1825] Consume latest pyvcloud and vcd-cli

- container_service_extension/client/cse.py
- container_service_extension/client/def_entity_cluster_api.py
- container_service_extension/client/legacy_native_cluster_api.py
- container_service_extension/client/template.py
- container_service_extension/request_processor.py
- Getting template list is same for all vCD versions   
- Remove duplicate endpoint that is not used by plugin UI
- Removed redundant logic of handling template list from client side cluster code
- Removed processing url and related template handling logic from request processor
- Tests done for `vcd cse template list`:
vcd.api_version: 34.0
vcd.api_version: 35.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/804)
> [VCDA-1822] Remove duplicate code on template list cli

- container_service_extension/configure_cse.py
Enabling the upgrade path from CSE 3.0.x to 3.0.1
Testing Done:
Ran cse upgrade on a CSE 3.0.1 installation (api v35.0) and the upgrade went through fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/811)
> Allow upgrade from 3.0.x to 3.0.1

- container_service_extension/cloudapi/constants.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/def_/entity_service.py
- container_service_extension/def_/ovdc_service.py
- container_service_extension/def_/schema_service.py
- container_service_extension/mqtt_extension_manager.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/right_bundle_manager.py
- container_service_extension/service.py
- container_service_extension/template_builder.py
* Refactor compute policy manager to use cloudapi version 2.0.0
* separate out cse prefixing form compute policy manager
Testing done:
* Checked paths which were affected by the change:
- `cse run`
- `cse template install`
- `cse upgrade`
- `cse install` (TODO for api version < 35)
- `vcd cse ovdc list`
- `vcd cse ovdc enable/disable`
- `vcd cse ovdc compute-policy list` (TODO)
- `vcd cse ovdc compute-policy add/remove` (TODO)
@rocknes @sahithi @ltimothy7 @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/801)
> [VCDA-1696] Upgrade cloudapi endpoints and refactor compute policy manager

- container_service_extension/sample_generator.py
- container_service_extension/server_cli.py
Added MQTT section for sample generator.
The cse sample command now supports a version flag. For vcd API versions 33 and 34, the config file is unchanged. For version 35, there is a new MQTT section with the AMQP section commented out and a commend specifying that only one of the message protocol sections should be used.
I have checked the output sample configurations for api versions 33, 34, and 35 and the help string for `cse sample`.
- …
> [VCDA-1897] sample generator with  MQTT section

- container_service_extension/cloudapi/constants.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/entity_service.py
- container_service_extension/server_constants.py
During CSE install/upgrade operation, if we endup creating a Native
defined Entity, we also need to publish access to this defined entity to
other users in System Org. In order to get this done, we need to setup an ACL
entry allowing other users to access the native defined entity.
This patch takes care of above functionality.
Signed-off-by: Chintan Shah <schintan@vmware.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/823)
> [VCDA-1919] Add ACL to the System Org while registering the defined entity schema

- container_service_extension/cse_service_role_mgr.py
- container_service_extension/server_cli.py
Cosmetic issues CSE service role creation
- Added better switch to accept VCD Host arg.
- Corrected command name from cse-service-role to create-service-role
- Hide password while accepting input
- Display msg to show progress in task
- Hide urllib3 error messages
Signed-off-by: Chintan Shah <schintan@vmware.com>
--- …
> [VCDA-1917] CSE Service Role creation cosmetic issues

- docs/cse3_0/KNOWN_ISSUES.md
There is a known issue with ACL of CSE native defined entity schema viz. it being not accessible by members of System org except the user who registered the schema. This PR adds this issue to the list of Known issue and provides a simple REST based workaround.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/822)
> Update known issue for CSE 3.0.1

- container_service_extension/system_test_framework/environment.py
- system_tests/test_cse_client.py
- system_tests/test_cse_server.py
- Fixed broken catalog and vapp urls for server tests (Caused by [VCDA-1906] system-tests-in-test-org-context).  
- Make separate org and vdc href each for server and client tests
- Client tests use test org and vdc href
- Server tests use broker's org and href that hosts the catalog
- Server tests passed
- Client tests passed 
---------------
@Anirudh9794 @rocknes @andrew-ni 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/838)
> [PR] Fixed Broken server system tests

- container_service_extension/system_test_framework/environment.py
- container_service_extension/vcdbroker.py
- system_tests/conftest.py
- system_tests/test_cse_client.py
- Removed test org and test vdc creation as they are pre-created by jenkins
- Remove sharing CSE catalog using ACL rules for test organization to access the catalog
- Run client tests as k8 author role => cloned vApp author role + view : catalog shared from other org right
- change vcdbroker cluster creation/resize: 
-- removed accessing catalog via sys admin client during cluster creation/resize 
-- Use the client instantiated with logged in persona's credentials. 
- Tested cluster creation and resize thru CLI
- Completed client system tests successfully
------------------------------
@Anirudh9794 @rocknes @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-servic …
> [VCDA-1907] Run Client Tests As k8 author 

- container_service_extension/configure_cse.py
- container_service_extension/telemetry/telemetry_utils.py
During CSE installation, the extension is registered before any of the other installation steps are preformed (viz. catalog creation, right registration, policy registration etc.). As a result of this if the installation fails midway, we won't be able to run `cse install` again, and to make matter worse since the `cse install`-ation process didn't complete, the next run of `cse upgrade` can fail due to lacking infra e.g. catalog.
To fix this issue, we are moving registration of CSE extension to be the last step during CSE installation, thereby guaranteeing that upgrade will be possible only when a valid CSE installation is in place.
Testing done:
Interrupted CSE install midway and verified that 
1. `cse install` can be triggered again and that it runs to completion.
2. `cse upgrade` can't …
> [VCDA-1908] Reorder CSE installation steps, to make `creation of extension` the last step

- container_service_extension/client/policy_based_ovdc.py
- container_service_extension/def_/models.py
- container_service_extension/def_/ovdc_service.py
- container_service_extension/telemetry/constants.py
- Restore recording `was_org_specified ` column in ovdc enable/disable for v35 
- Since org_name is not passed to the backend, it always record a 'false' value for `was_org_specified ` in table : `cse_ovdc_enable` and `cse_ovdc_disable` . This fix passes `org_name` to the back end telemetry payload constuction.
- Tested with VAC(telemetry) staging database
****cse_ovdc_enable****
****cse_ovdc_disable****
@Anirudh9794 @rocknes @ltimothy7 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/844)
> [VCDA-1950] Fix missing value telemetry recording ovdc enable/disable (v35)

- container_service_extension/def_/cluster_service.py
* If sync defined entity fails, the cluster defined entity will be stuck in a busy state forever
Solution:
* Update defined entity with failed status before syncing with vapp
Testing done:
* cluster create
* cluster delete
* cluster resize
@rocknes @sakthisunda @ChintanShahVMware @arunmk @ltimothy7 @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/845)
> [VCDA-1955] Update and resolve entity with correct status before syncing def entity

- container_service_extension/config_validator.py
- container_service_extension/configure_cse.py
- container_service_extension/consumer/amqp_consumer.py
- container_service_extension/consumer/consumer.py
- container_service_extension/sample_generator.py
- docs/cse2_6/CSE_CONFIG.md
- requirements.txt
- Code works with pika==1.1.0. Changes are mainly limited to function signatures of callbacks.
- removed `ssl` and `ssl_accept_all` from the config
- Cleaned up a set of logging statements
This will not support ssl and there need to be more config parameters added to support it. I am not clear if the earlier version supported it. If it did, we can hold off this PR and merge it with SSL included. If it did not, we could take SSL support as a separate ticket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/847)
> [VCDE-986]: Migrate to pika 1.1.0

- container_service_extension/client/constants.py
- container_service_extension/client/cse_client/api_33/ovdc_api.py
- container_service_extension/client/cse_client/api_35/ovdc_api.py
- container_service_extension/client/cse_client/cse_client.py
- container_service_extension/client/cse_client/pks_ovdc_api.py
- container_service_extension/client/metadata_based_ovdc.py
- container_service_extension/client/ovdc_commands.py
- container_service_extension/client/pks.py
- container_service_extension/client/pks_ovdc.py
- container_service_extension/client/policy_based_ovdc.py
- container_service_extension/client/utils.py
- container_service_extension/cloudapi/constants.py
- container_service_extension/cloudapi_utils.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/cluster_service.py
- container_service_extension/def_/entity_service.py
- container_service_extension/def_/ovdc_service.py
- container_service_extension/operation_context.py
- container_service_extension/pyvcloud_utils.py
- container_service_extension/request_handlers/pks_ovdc_handler.py
- container_service_extension/request_handlers/v35/def_cluster_handler.py
- container_service_extension/request_handlers/v35/ovdc_handler.py
- container_service_extension/request_processor.py
- container_service_extension/server_constants.py
- container_service_extension/shared_constants.py
- container_service_extension/utils.py
- requirements.txt
Porting changes from master:
- Pagination of ovdc list to prevent the client from timing out. Cluster list changes made as of now for only the server side.
- vcd cse ovdc list (for api V 35)
- vcd cse pks ovdc list ( for api V 33)
- Default page size is set to 25 in the client
Sample output with default page size set to 3 (for convenience of displaying the functionality)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/863)
> [VCDA-1927] paginate ovdc list (apiV 33 & 35) and cluster list (api 35)

- container_service_extension/consumer/amqp_consumer.py
- container_service_extension/consumer/constants.py
- container_service_extension/consumer/utils.py
- requirements.txt
CSE today is incapable to handling redelivered messages. This can lead to situations where CSE reprocesses heavy incoming requests multiple times. To make CSE server resilient to redelivered message, in this PR we have added logic to detect duplicate requests and reject them.
Testing done:
As part of testing added an exception in the normal workflow to crash the consumer to guarantee a message redelivery. Checked the logs and made sure that on redelivery of the message it is rejected, as well as removed from the AMQP queue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/851)
> [VCDA-1909] Add logic in AMQP consumer to reject redelivered messages

- container_service_extension/client/cse_client/api_33/ovdc_api.py
- container_service_extension/client/cse_client/api_35/ovdc_api.py
- container_service_extension/client/cse_client/pks_ovdc_api.py
- container_service_extension/def_/ovdc_service.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/request_handlers/pks_ovdc_handler.py
- container_service_extension/request_handlers/v35/ovdc_handler.py
- container_service_extension/request_processor.py
- container_service_extension/server_constants.py
- container_service_extension/shared_constants.py
As paginated response cannot be read by older version of the clients, revert to non-paginated responses for the following api endpoints
- `/api/cse/ovdcs`
- `/api/cse/3.0/ovdcs`
- `/api/pks/ovdcs`
Create following new endpoints which return paginated responses
- `/api/cse/orgvdcs`
- `/api/cse/3.0/orgvdcs`
- `/api/pks/orgvdcs`
Make sure the older CSE CLI clients (3.0.x) are compatible with the responses
Testing done:
* Check if `/api/cse/ovdcs`, `/api/cse/3.0/ovdcs` and `/api/pks/ovdcs` return non-paginated responses
* Check if `/api/cse/orgvdcs`, `/api/cse/3.0/orgvdcs` and `/api/pks/orgvdcs` return paginated responses and can read pagination parameters …
> [VCDA-2035] Fix ovdc list operation to support backward compatibility

- container_service_extension/client/cse_client/api_35/ovdc_api.py
- container_service_extension/request_handlers/ovdc_handler.py
- container_service_extension/request_handlers/pks_ovdc_handler.py
- container_service_extension/request_handlers/v35/ovdc_handler.py
This PR fixes the API path returned in the responses (next and previous page urls) to have the new endpoints.
Testing done:
* OVDC list using CLI with OVDC count more than the page size
* OVDC list using postman (for version 33.0) to verify if previous and next page urls contain proper urls
@rocknes @ltimothy7 @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/876)
> Api path format fix for ovdc list operation

- container_service_extension/client/tkgclient/api/tkg_cluster_api.py
- container_service_extension/client/tkgclient/api_client.py
Currently, cluster list operation will fail because TKG client pagination changes were removed.
This PR Adds back the TKG client changes
The changes in TKG client for pagination are still needed if CSE server is not running (CLI will be enabled only for TKG clusters)
Testing done:
* `vcd cse cluster list` when CLI is enabled only for TKG clusters
@sahithi @sakthisunda @rocknes @ltimothy7 @ChintanShahVMware @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/872)
> Fix TKG cluster list operation when CLI is enabled only for TKG

- container_service_extension/mqtt_extension_manager.py
- container_service_extension/service.py
Updated service.py so that only one MQTT extension token is active at a time. Previously, there was a bug where an incorrect function was called, so a token was created each time `cse run` was called.
I have tested that now at most one extension token is active.
--- …
> mqtt maintains only one token- main branch

- container_service_extension/mqtt_extension_manager.py
- container_service_extension/service.py
Updated service.py so that only one MQTT extension token is active at a time. Previously, there was a bug where an incorrect function was called, so a token was created each time `cse run` was called.
I have tested that now at most one extension token is active.
--- …
> mqtt maintains only one token- updates branch

- container_service_extension/service.py
Added logic during server startup to determine the list of api versions supported by both CSE and vCD.
Testing Done:
Added a print statement during server startup to print the runtime server config that holds the api versions supported by both vCD and CSE.
{
'enforce_authorization': True,
'processors': 10,
'log_wire': True,
'telemetry': {
'enable': True,
'vac_url': 'https://vcsa.vmware.com/ph/api/hyper/send',
'collector_id': 'CSE.3_0',
'vcd_ceip_id': 'f89fd574-8f62-4b85-a2ac-329a2faf85b5',
'instance_id': 'bccae9c2-ee9c-4e35-8cfc-6a2ae346544f'
},
'supported_api_versions': ['33.0', '35.0', '34.0']
}
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/897)
> [VCDA-2061] Determine common api versions supported by CSE and VCD

- container_service_extension/client/response_processor.py
Raise exception on server busy response
Testing done:
Overloaded the CSE server by sending multiple requests. Checked if CLI doesn't throw any python error on Server busy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/901)
> Prevent returning response dict on server busy response

- container_service_extension/client/cse_client/api_33/ovdc_api.py
- container_service_extension/client/cse_client/api_35/ovdc_api.py
- container_service_extension/client/cse_client/pks_ovdc_api.py
- container_service_extension/common/constants/server_constants.py
- container_service_extension/rde/ovdc_service.py
- container_service_extension/server/request_handlers/ovdc_handler.py
- container_service_extension/server/request_handlers/pks_ovdc_handler.py
- container_service_extension/server/request_handlers/v35/ovdc_handler.py
- container_service_extension/server/request_processor.py
As paginated response cannot be read by older version of the clients, revert to non-paginated responses for the following api endpoints
- `/api/cse/ovdcs`
- `/api/cse/3.0/ovdcs`
- `/api/pks/ovdcs`
Create following new endpoints which return paginated responses
- `/api/cse/orgvdcs`
- `/api/cse/3.0/orgvdcs`
- `/api/pks/orgvdcs`
Make sure the older CSE CLI clients (3.0.x) are compatible with the responses
Testing done:
* Check if `/api/cse/ovdcs`, `/api/cse/3.0/ovdcs` and `/api/pks/ovdcs` return non-paginated responses
* Check if `/api/cse/orgvdcs`, `/api/cse/3.0/orgvdcs` and `/api/pks/orgvdcs` return paginated responses and can read pagination parameters …
> Port Fix ovdc list operation to support backward compatibility (#871) to master

- container_service_extension/client/cse_client/api_35/ovdc_api.py
- container_service_extension/compute_policy_manager.py
- container_service_extension/def_/ovdc_service.py
- call to /vdcComputePolicies is made every time computePolicyManager is initialized. This is an expensive call as computPolicy will be created for every ovdc created in VCD.
- Initialization of compute policy manager in ovdc list code should be done only once.
For 2000 ovdcs, an average of 20s is required for fetching 10 ovdcs per page.
@rocknes @sakthisunda @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/905)
> [VCDA-2128] Fix repetitive expensive calls to vdcComputePolicies

- container_service_extension/common/constants/shared_constants.py
- container_service_extension/server/request_dispatcher.py
Current CSE can only expose REST apis at one given api versions. To improve backward compatibility of CSE server, this PR introduces a new mechanism of request processing/dispatching that will let CSE expose api endpoints at multiple api versions concurrently. This PR also revamps the entire request processor logic, the new framework is state machine driven, as a result adding new endpoints would not need core code change but only change in the api endpoint - handler table.
Testing Done:
ToDo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/904)
> [VCDA-2062] Implement request dispatcher to expose CSE REST api at multiple api versions

- container_service_extension/installer/config_validator.py
- Use case: When there is more than one vcenter registered with vCD and CSE has properly configured for those.
- Issue: CSE server start/restart failure on any unavailable vCenter.
- Skip the vCenter that is not currently connected and continue CSE server start/restart. Display warning information about the server unavailability
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/912)
> [VCDA-1683] Skip unavailable vCenter registered in VCD on CSE server start/restart

- container_service_extension/rde/constants.py
- container_service_extension/rde/utils.py
- container_service_extension/server/service.py
Add mapping to get rde_schema_version to be used during CSE configuration
Add method to get currently used schema version when CSE is running
@sahithi @sakthisunda @rocknes @ltimothy7 @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/913)
> [VCDA-2122] Add utility methods for fetching rde_schema_version

- container_service_extension/rde/models/rde_2_0_0.py
- cse_def_schema/schema_2_0_0.json
- Schema and RDE change for 2.0.0  
- Requirement: To get the current state of the cluster from Cluster Status
- Update RDE Status to include template name and revision.   
- Tested manually using Postman
- Using cse install registered defined entity schema
- Created Defined Entity for the new schema with dummy values.
- Using `vcd cse cluster list `verfied the created defined entity appears with no deserialization issue
-------------------------------
----------
@Anirudh9794  @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/920)
> [VCDA-2175] Schema-change-for-RDE-Status-To-Reflect-Cluster-Current-state

- container_service_extension/rde/models/rde_2_0_0.py
- Added storage profile as part Node dataclass. This has been already added to schema. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/926)
> [VCDA-2175] Schema-change-for-Cluster-Status-To-Reflect-Cluster-Current-state 

- container_service_extension/common/utils/server_utils.py
- container_service_extension/rde/models/common_models.py
- container_service_extension/server/request_handlers/v35/def_cluster_handler.py
- container_service_extension/server/request_handlers/v36/def_cluster_handler.py
- container_service_extension/server/service.py
Use the rde_in_use to determine which cluster_service.py file needs to be used for handling the request.
Testing done:
Checked if the right cluster_service file is being invoked using debugger and log statements
@sahithi @sakthisunda @rocknes @arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/922)
> [VCDA-2150] Pick cluster_service file using rde in use

- container_service_extension/configure_cse.py
Enable the 3.0.2 -> 3.0.2 upgrade path.
Testing done:
Ran `cse upgrade` from CSE 3.0.1 and CSE 3.0.2.dev setups to make sure the upgrade is working fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/927)
> Allow upgrade from CSE 3.0.2 to CSE 3.0.2

- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/entity_service.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/utils.py
- cse_def_schema/schema_2_0_0.json
- Cluster operations get the current state from defined entity status  
- Change the rde usage to 2.0.0 in cluster_svc2.py
- Method to convert the status to Spec as part of Cluster Service (Logically more closer for this method to be here)
- Retrieves the current state from Status using Helper 
- Stops updating the spec while updating Status, 
- While updating the Status, update the newly added cloud_properties and storage_profile
- Sanity test done on cluster creation using rde 2.0.0 and cluster service 2_x
- Verified Status gets updated
- **TODO:** Get latest master code and do cluster operations
---------
---------------------------
--------------------------------------------------------
@Anirudh9794 @sahithi @rocknes
--- …
> [VCDA-2052] Get current state of cluster from Defined Entity Status

- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/constants.py
- cse_def_schema/api_v35/schema.json
- cse_def_schema/schema_1_0_0.json
Changes to use the dynamically computed `server_rde_version` to register and define interfaces
* Made changes to register array of interfaces
* Created placeholders for behavior code
* Remove the usage of MAP_API_VERSION_TO_KEYS dictionary.
* check for the presence of the required interface/ entity type before creation.
Testing done:
* Cse install to install RDE schema 1.0.0 and 2.0,0
* CSE run to dynamically load the registered schema
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/931)
> [VCDA-2151]  use server_rde_version to register rde schema in CSE install

- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/constants.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/utils.py
- container_service_extension/rde/validators/abstract_validator.py
- container_service_extension/rde/validators/validator_factory.py
- container_service_extension/rde/validators/validator_rde_1_x.py
- container_service_extension/rde/validators/validator_rde_2_x.py
- container_service_extension/server/request_handlers/request_utils.py
- container_service_extension/server/request_handlers/v36/def_cluster_handler.py
- Validator implementation by RDE version supported by API handler 
- Cluster spec validation 
- V36 cluster handler changes to use new validator
- Entity service, Cluster service fixes to get entity type 
- Tested on cluster creation and resize
- TODO: upgrade test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/934)
@Anirudh9794 @sahithi @rocknes
> [VCDA-2148] Input validator by RDE version 

- container_service_extension/def_/cluster_service.py
* Reduce situations where the cluster operation task is left stranded without erroring out
* Avoid resolving defined entitiy on every update call as it is not necessary to call resolve after updatie
Testing done:
* Create cluster
* add node to cluster
* delete node from cluster
* upgrade cluster
* Make sure errors in the above operations do not leave the task stranded (TODO)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/939)
> Port [VCDA-2002] Avoid resolving defined entities after every update (#877) to cse_3_0_updates

- container_service_extension/installer/config_validator.py
- container_service_extension/installer/sample_generator.py
- container_service_extension/server/request_dispatcher.py
- container_service_extension/server/service.py
- container_service_extension/server/vcdbroker.py
- system_tests/base_config.yaml
After the shift to request dispatcher, all available CSE apis are currently exposed simultaneously. This is a deviation from CSE 3.0.0 behavior where legacy (33.0, 34.0) cluster/node/ovdc apis and defined entity based (35.0) cluster, node, ovdc apis couldn't co-exists.
To solve this problem, this PR introduces the concept of feature flags in CSE configuration file. The request dispatcher map, will have a record of feature flags that will guard certain apis. During actual dispatch of the request to handlers, if feature flag requirements are not met, then the request will be failed and never reach the handler.
Additionally, a new entry in the service section has been introduced in this PR viz. 'legacy_mode' this automatically sets two feature flags in the config (viz. 'legacy_api' and …
> [VCDA-2064, VCDA-2065] Introduce support for feature flags and `legacy_mode` to protect apis

- container_service_extension/client/response_processor.py
Raise exception on server busy response
Testing done:
Overloaded the CSE server by sending multiple requests. Checked if CLI doesn't throw any python error on Server busy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/914)
> Port Prevent returning response dict on server busy response (#901) to master

- container_service_extension/client/cse_client/api_35/ovdc_api.py
- container_service_extension/rde/ovdc_service.py
- container_service_extension/server/compute_policy_manager.py
- call to /vdcComputePolicies is made every time computePolicyManager is initialized. This is an expensive call as computPolicy will be created for every ovdc created in VCD.
- Initialization of compute policy manager in ovdc list code should be done only once.
For 2000 ovdcs, an average of 20s is required for fetching 10 ovdcs per page.
@rocknes @sakthisunda @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/915)
> Port Fix repetitive expensive calls to vdcComputePolicies (#905) to master

- container_service_extension/client/command_filter.py
- container_service_extension/common/constants/server_constants.py
- container_service_extension/lib/telemetry/constants.py
- container_service_extension/lib/telemetry/payload_generator.py
- container_service_extension/lib/telemetry/telemetry_handler.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/utils.py
- container_service_extension/rde/validators/abstract_validator.py
- container_service_extension/rde/validators/validator_rde_1_x.py
- container_service_extension/rde/validators/validator_rde_2_x.py
- container_service_extension/server/request_dispatcher.py
- container_service_extension/server/request_handlers/request_utils.py
- container_service_extension/server/request_handlers/v35/def_cluster_handler.py
- container_service_extension/server/request_handlers/v35/ovdc_handler.py
- container_service_extension/server/request_handlers/v36/def_cluster_handler.py
- Implementation of CRUD handlers for api version v36
- Update request dispatcher to register v36 cluster handlers
- Update crud handlers  in v36 api handler
- Update validator to get entity as params
- Tested CRUD operations using server_api_version:36 in profiles.yaml
- Telemetry changes and testing completed
@Anirudh9794 @sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/947)
> [VCDA-2204] modify v36 cluster handler

- container_service_extension/def_/cluster_service.py
- container_service_extension/request_handlers/v35/def_cluster_handler.py
- container_service_extension/shared_constants.py
-The cluster resize workflow will now check if the cluster is exposed; if the user desires to unexpose the cluster, the associated dnat rule will be deleted, and the kubeconfig will have the external ip replaced with the internal ip.
@arunmk @rocknes @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/953)
> [VCDA-2007] Cluster resize with exposed cluster

- cluster_scripts/1_x/mstr.sh
- cluster_scripts/2_x/mstr.sh
- container_service_extension/common/constants/server_constants.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/sample_generator.py
- container_service_extension/installer/templates/remote_template_manager.py
- container_service_extension/server/service.py
Once the changes for https://reviewable.io/reviews/vmware/container-service-extension-templates/24#- is merged, CSE should download the cluster-scripts (mstr.sh and node.sh) only if legacy_mode is enabled.
This PR also adds logic for CSE to download from templateV2.yaml instead of template.yaml if legacy_mode is set to false.
Testing done:
* create CSE template with legacy_mode: true
* create CSE template with legacy_mode: false
@sahithi @rocknes @arunmk @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/952)
> Changes to use TemplateV2.yaml

- container_service_extension/installer/templates/remote_template_manager.py
- container_service_extension/system_test_framework/environment.py
- system_tests/base_config.yaml
add optional parameter `legacy_mode` to `download_all_scripts` function in remote template manager
(This is an interim fix, legacy_mode will be made a class attribute for remote_template_manager in my change set for updating install and upgrade workflows)
Testing done:
* create template in VCD using `cse template instlall command`
* run cse server test and check if right scripts are downloaded
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/960)
> Fix CTOT - add legacy_mode param to download all scripts

- container_service_extension/common/constants/server_constants.py
- container_service_extension/common/utils/server_utils.py
- container_service_extension/installer/config_validator.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/templates/local_template_manager.py
- container_service_extension/installer/templates/remote_template_manager.py
- container_service_extension/server/cli/server_cli.py
- container_service_extension/server/service.py
- container_service_extension/system_test_framework/environment.py
* Cache only the templates which are supported by the current CSE version if legacy_mode is false
* install and upgrade should only install templates supported by the currently running CSE.
* Template is supported if template['min_cse_version'] >= current_cse_version <= template['max_cse_version']
* Store template's min cse version and max cse version as part of template metadata
Testing done:
* Check if CSE install installs only the supported templates
* Check if correct error is thrown if user tries to install a template which is not supported.
Required:
* Should be merged after in-place tag 3.1 is created.
@rocknes @sahithi @sakthisunda @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [VCDA-2193] Change CSE install and upgrade workflow to install supported templates

- container_service_extension/common/constants/server_constants.py
- container_service_extension/installer/right_bundle_manager.py
- container_service_extension/server/cli/server_cli.py
CSE service account is missing the 'Edit' right for RightsBundles, as a result, it is unable to publish rights bundle to tenant orgs.
This workflow will break any upgrade from CSE 2.6 or prior to CSE 3.0/CSE 3.1.
Additionally there is a logic bug around how CSE publishes the right bundle to tenants. In the current implementation, CSE doesn't preserve the list of tenants who already has the right bundle published to them. This PR fixes the bug.
Additional small fixes to 
* improve flake8 compliance
* change the flag for cse create-service-role to follow standard key to ignore ssl certificate verification
Testing:
ToDo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service …
> [VCDA-2274] Fix upgrade issue related to missing rights in `cse service account`

- container_service_extension/installer/templates/local_template_manager.py
- container_service_extension/installer/templates/remote_template_manager.py
- container_service_extension/server/cli/server_cli.py
- container_service_extension/server/service.py
* Load only the templates which are supported during CSE run.
* Print message on the console if template (with required metadata keys) is not valid for the given CSE version
Testing done:
* CSE run with an unsupported template
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/968)
> [VCDA-2195] Print template verification messages on console in CSE run

- container_service_extension/common/constants/server_constants.py
- container_service_extension/common/utils/core_utils.py
- container_service_extension/common/utils/server_utils.py
- container_service_extension/installer/config_validator.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/templates/local_template_manager.py
- container_service_extension/logging/logger.py
- container_service_extension/server/cli/server_cli.py
- container_service_extension/server/service.py
Remove usage of api version from cse install/upgrade/run
Stamp legacy mode flag on CSE extension instead of the api version in use.
Testing Done:
* Installed CSE 3.0.2, upgraded to CSE 3.1 and made sure upgrade goes through successfully.
* Re-upgraded to 3.1 to ensure idempotency of the upgrade
* Ran CSE before and after the upgrade and got correct error messages
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/981)
> [VCDA-2068, 2069, 2184] Remove api version from CSE upgrade/run/install

- container_service_extension/mqi/consumer/constants.py
- container_service_extension/mqi/consumer/mqtt_consumer.py
- container_service_extension/mqi/consumer/mqtt_publisher.py
- container_service_extension/rde/backend/cluster_service_2_x_temp.py
- container_service_extension/rde/behaviors/behavior_model.py
- container_service_extension/security/context/behavior_request_context.py
- container_service_extension/server/behavior_dispatcher.py
- container_service_extension/server/behavior_handler.py
- container_service_extension/server/request_handlers/cluster_handler.py
Enable backend to publish messages to MQTT bus.
1. Backend can now access MQTT publisher object from the BehaviorOperationContext
2. Added support to publish success, error, and update messages on behaviors via MQTT.
3. There is no longer a need for a separate thread pool for behaviors, given we can set the terminal status asynchronously now from the backend. Removed the separate thread pool dedicated for behaviors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/978)
> Enable backend to publish messages to MQTT bus

- container_service_extension/rde/models/rde_1_0_0.py
- container_service_extension/rde/utils.py
- container_service_extension/server/request_handlers/v35/def_cluster_handler.py
- Convert the input based on runtime rde version
- Cluster service based on runtime rde version
- Convert the new entity to input format before returning
- Tested with following endpoints
- Tests done on CSE 3.1, VCD 10.3
vcd cse cluster apply
POST api/cse/3.0/cluster/{cluster_id}/action/upgrade
POST api/cse/3.0/clusters
PUT api/cse/3.0/cluster/{cluster_id}
- TBD : CSE 3.1, VCD 10.2 
@Anirudh9794 @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/984)
> [VCDA-2205] V35 handler - process input and use cluster service based on runtime rde version

- container_service_extension/installer/configure_cse.py
- container_service_extension/server/service.py
- Fixed wrong RDE version stamping on CSE extension information
- Convert extracted CSE version from CSE extension to semantic_version before upgrade procedure
- Tested manually 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/989)
> [VCDA-2294,VCDA-2299] Remove-Wrong-RDE-Version-Stamping-And-Convert-CSE-Version-From-Extension

- container_service_extension/client/cluster_commands.py
- container_service_extension/client/cse_client/api_35/native_cluster_api.py
- container_service_extension/client/de_cluster.py
- container_service_extension/client/de_cluster_native.py
- container_service_extension/client/sample_generator.py
- container_service_extension/client/utils.py
- container_service_extension/rde/common/entity_service.py
- container_service_extension/rde/constants.py
- container_service_extension/rde/models/abstractNativeEntity.py
- container_service_extension/rde/models/rde_1_0_0.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/schema_service.py
* Constructing filters in entity_service.py: filters created in entity_service module supports only snake case. Make changes to change the case of the filter string based on RDE version used.
* Sample generator: Generate sample cluster-apply specification based on server-rde version in use.
* Skip converting the input yaml into NativeEntity object before calling create / update endpoints. Only responses sent from the CSE server should be converted into model objects.
* Make sure responses from cluster list populate all the required fields, even if RDE version changes.
@sahithi @sakthisunda @rocknes @ltimothy7 @arunmk
--- …
> [VCDA-2283] CLI changes to harden against RDE changes

- container_service_extension/installer/configure_cse.py
- container_service_extension/server/cli/server_cli.py
- container_service_extension/server/service.py
- Upgrade path for CSE 3.0 legacy mode to CSE 3.1 legacy mode
- Recreate templates option 
- Update CSE extension
- Removed --password option from CLI 
- Tested upgrade with CSE 3.0.1 api version (33,34) to CSE 3.1 legacy mode=true
- VCDA-2294, 2299 changes are also in this file
@Anirudh9794 @rocknes 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/993)
> [VCDA-2285] Enable cse 3.0 legacy to cse 3.1 legacy upgrade

- container_service_extension/server/service.py
- Fix double conversion of CSE version string.
- Double conversion of CSE version string to semantic version causes `cse run ` failure. 
- Replacing the wrong commit. 
- Manually verified
@Anirudh9794 @rocknes @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1002)
> [PR] Fix double conversion of CSE version string to semantic version

- container_service_extension/server/cli/server_cli.py
Command throws error if `api_version` key is not found in the config file. As of CSE 3.1 the key is not supported in the config file, so we must not be relying on it's presence. This PR removes the hard dependency, and uses the default value of None while creating pyvcloud client, which will choose the highest supported api version.
This problem only occurs if the config file is not validated before use. In case of validated config file, internally CSE sets the correct value of 'api_version' key in the run time config.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1006)
> Fix `cse template list`

- container_service_extension/common/constants/server_constants.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/validators/validator_rde_2_x.py
- container_service_extension/server/request_handlers/v35/def_cluster_handler.py
* Set defaults for k8 template name and revision to None. This enables the user to skip validation on template name and revision by sending empty values if no change in the field is desired.
* Skip validation on workers.sizingClass, workers.storageProfile, nfs.sizingClass and nfs.storageProfile if number of workers or number of nfs nodes in the entity status is 0
@sakthisunda @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1001)
> [VCDA-2314] Skip sizing class and storage profile validation if node count is 0

- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/models/common_models.py
- container_service_extension/rde/schema_service.py
- requirements.txt
1. Included Hooks as part of Entity type schema (Uncommented the hooks portion, for now, to avoid breaking native API endpoints). This must be uncommented when the cluster CRUD with behaviors is fully ready.
2. Tested it.
How to test hooks on your environment:
1. Please uncomment hooks in container_service_extension/rde/models/common_models.py:292
2. Delete the existing Entity type and rerun the 'cse install' command.
3. Create/update/delete RDE and it should hit the behavior_dispatcher.py workflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1012)
> [VCDA-2318] Enabled hooks as part of Entity type registration

- container_service_extension/common/utils/core_utils.py
- container_service_extension/common/utils/server_utils.py
- container_service_extension/installer/config_validator.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/server/service.py
-  Stamp rde version : install and upgrade in non-legacy mode
-  cse run : suggest to upgrade if rde version in extension < runtime rde version to upgrade to
-  Tested with install, upgrade and run command
-  This PR has extra code that is already under review: [VCDA-2285] Enable cse 3.0 legacy to cse 3.1 legacy upgrade. This is required for testing
- Remove old entity types after upgrade
- Testing completed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/999)
> [VCDA-2281] Stamp rde version after install and upgrade in non legacy mode

- container_service_extension/rde/backend/cluster_service_2_x_behaviors.py
Defined entity updates in cluster service should only be done by privileged users
Testing done:
Create cluster to check if update_entity is working fine with sysadmin_entity_svc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1008)
> [VCDA-2312] Entity update only to be done by privileged user

- container_service_extension/mqi/consumer/mqtt_publisher.py
1. Modified the success payload as per the new guidelines from DEF. Success payload can be sent out with the same contentType as for other status' like running and error.
2. Tested it in CSE-VCD environment with hook-based behaviors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1017)
> [VCDA-2322] Modified the success payload as per the new guidelines from DEF

- container_service_extension/mqi/consumer/mqtt_publisher.py
- container_service_extension/rde/backend/cluster_service_2_x_behaviors.py
- container_service_extension/rde/models/common_models.py
…unction
Extract out entity status updates to a separate function to allow future changes to use Optimistic locking
Testing - 
* Create cluster using create cluster behaviors (TODO)
* 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1020)
> [VCDA-2316] Extract out entity status updates to a separate funciton

- container_service_extension/rde/backend/cluster_service_2_x_behaviors.py
- container_service_extension/rde/behaviors/behavior_model.py
- container_service_extension/server/behavior_handler.py
Modify get kube-config operation for behaviors-handler
Testing done:
* Invoke behaviors using the endpoint `https://{{VCD_IP}}/cloudapi/1.0.0/entities/{{CLUSTER_ID}}/behaviors/urn:vcloud:behavior-interface:createKubeConfig:vmware:k8s:1.0.0/invocations`
* See if result.resultContent has the kubeconfig once the task succeeds
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1031)
> [VCDA-2241] Test and update cluster kubeconfig for behaviors

- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/backend/cluster_service_2_x_behaviors.py
- container_service_extension/rde/behaviors/behavior_model.py
- container_service_extension/rde/behaviors/behavior_service.py
- container_service_extension/rde/models/common_models.py
- container_service_extension/security/context/behavior_request_context.py
- container_service_extension/server/behavior_dispatcher.py
- container_service_extension/server/behavior_handler.py
- container_service_extension/server/request_handlers/cluster_handler.py
- container_service_extension/server/request_handlers/v35/def_cluster_handler.py
Testing done:
- invoke behavior using `POST https://{{VCD_IP}}/cloudapi/1.0.0/entities/{{CLUSTER_ID}}/behaviors/urn:vcloud:behavior-interface:deleteNfsNode:cse:k8s:1.0.0/invocations` for valid nfs node name and invalid nfs node name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1037)
> [Vcda 2462] Add behavior and handler for nfs node delete

- container_service_extension/rde/common/entity_service.py
- container_service_extension/server/request_handlers/cluster_handler.py
- Fixed error: RDE_RESTRICTED_FIELDS [ status ]
- Currently, cluster creation fails because the defined entity having status element is prohibited by VCD. This fix resolves by removing status element from defined entity before POSTing defined entity for cloud api endpoint. This is conditional removal required only for cluster creation.
- Tested with CSE CLI cluster creation
@Anirudh9794 @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1045)
> PR-Fix for RDE_RESTRICTED_FIELDS [ status ]

- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/common/entity_service.py
- container_service_extension/rde/models/rde_2_0_0.py
* making a call to PUT /entities/id with entityType field modified to a new entity type should upgrade the RDE to a new entity type.
* Things to note: defined entity ID will no longer contain entity type version string. Example instead of `urn:vcloud:entity:cse:nativeCluster:2.0.0:919bbbc5-3d15-4a1e-99bc-e016647ac896` it will be `urn:vcloud:entity:cse:nativeCluster:919bbbc5-3d15-4a1e-99bc-e016647ac896`. However, the entity can be accessed using former style as well.
Testing done:
* Create an RDE cluster using CSE 3.0.2 and upgrade cse. Made sure that entity upgrade is working, vapp metadata is getting updated and entity type is getting deleted successfully.
@sakthisunda @sahithi
--- …
> [VCDA-2267] Upgrading cluster RDE instead of re-creating them in cse-upgrade

- container_service_extension/rde/constants.py
- container_service_extension/rde/models/rde_1_0_0.py
- container_service_extension/server/request_handlers/v35/def_cluster_handler.py
- Delegate RDE 2.0 operations to right handler 
- Currently, if any version=35.0 call is handled by v35 handler, which is default handler for RDE 1.0. When the runtime RDE supported is RDE 2.0, delegate that to RDE 2.0 handler(cluster_handler). Thus, all RDE 2.0 and above will be directly handled by cluster_service_2x_behavior handler.
- Reject payloads of RDE 2.0 in v35 handler
- Tested using Postman for cluster creation, resize, upgrade and delete
----------------
-----------------------------------
@Anirudh9794 @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1034)
> [VCDA-2410] Redirect v35_handler to 36_handler if runtime_rde >= 2.0

- container_service_extension/common/constants/shared_constants.py
- cse_def_schema/schema_2_0_0.json
RDE 2.0 Schema changes in schema_2_0_0.json to accommodate CSE 3.1 features (CSI, CPI, TKGm integration)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1040)
> [VCDA-2435] Update the RDE schema to accommodate R1

- container_service_extension/installer/config_validator.py
- container_service_extension/installer/sample_generator.py
…on-legacy mode
As CSE 3.1 uses behaviors when configured with VCD 10.3 and behaviors can only work with MQTT, it is not possible to support AMQP with CSE 3.1 and VCD 10.3 vcd.
Changes done:
- Config validator raises error when AMQP is configured and maximum api version is 36.0
Testing done:
- Install CSE with AMQP and vcd 10.3, check for error messages
- Install CSE with MQTT and 10.3, no errors should be thrown
@rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1048)
> [VCDA-2479] prevent AMQP configuration with CSE 3.1 non-legacy mode and 10.3 VCD

- container_service_extension/common/constants/server_constants.py
- container_service_extension/common/utils/server_utils.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/templates/remote_template_manager.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/utils.py
- container_service_extension/rde/validators/validator_rde_2_x.py
- container_service_extension/server/cli/server_cli.py
* Template .yaml should contain a version key which will help identifying the template script structure
* Remove hard coding of script directory path. Use script_directory key in template.yaml
Testing done:
* Install CSE 3.1 using cookbook with version 1.0 -> should fail with proper error message
* Install CSE 3.1 using cookbook with version 2.0 and install a template
@rocknes @sahithi @sakthisunda @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1052)
> [VCDA-2472 & VCDA-2545] Use version key in template yaml instead of depending on naming

- container_service_extension/client/cluster_commands.py
- container_service_extension/client/command_filter.py
- container_service_extension/client/sample_generator.py
On windows, `cse cluster apply -s` fails with the error message "str object has no attribute value"
It seems that click converts all default values to string before passing them to the method as param.
The default value for the type of sample to generate is an Enum, which when passed into the method is getting converted to string, as a result the code downstream that tries to grab the value of the Enum object ends up calling value() on a string object and fails.
As a fix, this PR makes sure that the entire code path is designed to deal with only strings and not Enum objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-s …
> [VCDA-2559] Fix `cse cluster apply -s -n/-t/-m`

- container_service_extension/client/template_commands.py
- container_service_extension/installer/sample_generator.py
- container_service_extension/server/cli/server_cli.py
- Updated Help strings for CLI on install, upgrade, run, template install
- Fixed sample generation depending on api_version: location of template_cookbook_url and legacy mode 
- Manually verified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1057)
> [VCDA-2557] Update help strings install upgrade template install

- container_service_extension/configure_cse.py
- container_service_extension/server_cli.py
While upgrading CSE 3.0.0/1/2 to CSE 3.0.3, update the registered native RDE schema to allow TKGm as a valid value for kind.
Testing done:
Installed CSE 3.0.2.
Created a native cluster
GET on /cloudapi/1.0.0/entityTypes/urn:cse:native:1.0.0 -> verified that TKGm is not an allowed value for kind
Upgraded to CSE 3.0.3 -> Checked the schema update message on console
GET on /cloudapi/1.0.0/entityTypes/urn:cse:native:1.0.0 -> verified that TKGm is an allowed value for kind
Created TKGm cluster, the RDE resolved without any issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1061)
> [VCDA-2560] Update RDE native schema while upgrading CSE from 3.0.0/1/2 to 3.0.3

- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/common/entity_service.py
- container_service_extension/server/request_handlers/cluster_handler.py
* Processing of headers should be done in `entity_service.py` and not in `cluster_handler`. This change-set moves processing of response headers which were in `cluster_handler.py` into `entity_service.py` file
Testing done:
* Create, resize and delete cluster using 3.1 CSE and 10.3 VCD (TODO)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1063)
> [VCDA-2476] Avoid processing headers in cluster_handler layer

- container_service_extension/client/cluster.py
- container_service_extension/client/cluster_commands.py
- container_service_extension/client/command_filter.py
- container_service_extension/client/de_cluster.py
- container_service_extension/client/de_cluster_tkg.py
- container_service_extension/client/ovdc_commands.py
- container_service_extension/client/sample_generator.py
- container_service_extension/client/utils.py
- container_service_extension/configure_cse.py
- container_service_extension/def_/models.py
- container_service_extension/exceptions.py
- container_service_extension/shared_constants.py
Changed the constants and methods dealing with TKG(WCP) to TKG-S. The value of the constant were left intact, only the variable names were changed.
In CSE CLI, certain flags related to TKG+, TKG(WCP) and TKGm were changed to better reflect the marketing strategy around TKG.
TKG: --tkg/-t -> --tkg-s/-k
TKG+: --tkg-plus/-t/-k -> --tkg-plus/-p
TKGm: --tkg-m/-m -> --tkg/-t
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1071)
> [VCDA-2563] Update TKG flags and constant names

- container_service_extension/client/de_cluster_tkg.py
entity details for list entities from TKG swagger client should be accessed using key 'entityDetails'
Testing done
* `vcd cse cluster config`
* `vcd cse cluster apply`
* `vcd cse cluster delete`
@rocknes @sahithi @ltimothy7 @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1073)
> [VCDA-2614] Fix accessing entity details array using 'entityDetails' key

- container_service_extension/installer/config_validator.py
- CSE server commands on missing config legacy_mode raise key error. This is fixed to display the right error message as before.
- Validation of broker section uses 'legacy_mode' key and it happens before validating service section. 
By doing service section validation first, we avoid this KeyError.
- Tested and verified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1077)
> [VCDA-2595] Fixed python key error on missing config legacy_mode

- container_service_extension/client/de_cluster_tkg.py
- container_service_extension/rde/backend/cluster_service_2_x.py
Testing done:
- `vcd cse cluster apply`
- `vcd cse cluster config ...`
for TKG clusters
@sakthisunda @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1075)
> [VCDA-2407 and VCDA-2615] Fix for TKG cli and use 37-alpha when CLI is used with vcd 10.3

- container_service_extension/installer/configure_cse.py
- Fixed RDE resolution error that was caused by deleting `status section` in payload while upgrading CSE 3.0.0 to CSE 3.1.0
- Retain `status section` in payload while creating RDE for upgrades as upgrades are executed by privileged user.
- Tested and verified the RDE thru CLI and postman
----------------------------------------------------------------------------------
----------------------------------------------------------------------------------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1081)
> [VCDA-2596] CSE upgrade: Fix RDE resolution error 

- cluster_scripts/v1_x/control_plane.sh
- cluster_scripts/v2_x/control_plane.sh
- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
Kubeadm init needs to be invoked using --config option for TKG+ clusters.
This change is to make sure that the control-plane.sh invoke kubeadm init with --config if kind is "TKG+"
Testing done:
* Tested if kubeadm init is invoked with --config for TKG+ cluster kind.
* Tested if kubeadm init is NOT invoked with --config option for native cluster kind.
@sahithi @arunmk  @rocknes @ltimothy7 @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1082)
> [VCDA-2626] Run kubeadm init with --config param for TKG+

- container_service_extension/common/constants/server_constants.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/templates/local_template_manager.py
- container_service_extension/installer/templates/remote_template_manager.py
- container_service_extension/installer/templates/template_builder.py
- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/server/vcdbroker.py
… key during cse upgrade
* Create subdirectory under LOCAL_SCRIPTS_DIR to store script cache
* Ignore compute policy key during cse upgrade as it prevents updating template metadata once again after upgrade is complete.
Testing:
* Cse upgrade to check if ignoring keys work fine
* Template install and see if proper directory is created during cluster installation.
@rocknes @sahithi @ltimothy7 @sakthisunda @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1076)
> [VCDA-2601] Create subdirectory under LOCAL SCRIPTS DIR

- container_service_extension/rde/backend/cluster_service_2_x.py
- docs/cse3_1/CLUSTER_MANAGEMENT.md
- requirements.txt
Operation property of the task must say what operation is being performed on the entity, but not necessarily the status of the cluster. Changed the messages accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1087)
> [VCDA-2627] Fixed incorrect in-progress messages even after cluster creation is successful

- container_service_extension/client/cluster_commands.py
- container_service_extension/client/sample_generator.py
- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/models/rde_1_0_0.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/utils.py
- cse_def_schema/schema_2_0_0.json
Added two new fields to RDE 2.0.0 viz. `expose` and `exposed`. Also made associated changes in the model and service files.
Testing done:
Generated a RDE 2.0.0 based cluster spec file and made sure that the new fields are part of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1089)
> [VCDA - 2624] Add `expose` and `exposed` field to RDE 2.0.0

- container_service_extension/rde/backend/cluster_service_2_x.py
- docs/cse3_1/CLUSTER_MANAGEMENT.md
Added a operation message for  (download kubeconfig).
Task messages on UI are always displayed as "Busy (native cluster)" regardless of the operation that is being performed.
Modified the task messages so that UI reflects meaningful messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1092)
> [VCDA-2651] Task operation messages do not show meaninful messages on UI.

- container_service_extension/rde/common/entity_service.py
- Fix for invokeHooks on entity CRUD operations by tenant-user getting Operation denied error 
- Apply invokeHooks query param only for sys admin users 
- Added checks in entity service
Before fix
After Fix
@sahithi @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1095)
> [VCDA-2657] Exclude invokeHooks query param for non-admin user on CSE nativeEntity

- container_service_extension/rde/behaviors/behavior_model.py
- docs/cse3_1/CLUSTER_MANAGEMENT.md
Behavior invocation requests would embed the "actAsToken" only if the corresponding definition had "actAsToken= true"
This is a recent change done by the Extensibility team for security reasons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1096)
> Change the behavior definition to include "actAsToken" property

- container_service_extension/client/cluster_commands.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/templates/remote_template_manager.py
- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/backend/common/network_expose_helper.py
- container_service_extension/rde/models/rde_1_0_0.py
- container_service_extension/rde/models/rde_2_0_0.py
- cse_def_schema/schema_2_0_0.json
Port `cluster expose` feature from cluster_service_1_x.py to cluster_serivce_2_x.py.
Add new field `external_ip` for RDE 2.0.0. Add associated logic to retain the internal control plane ip while exposing the cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1094)
> [VCDA-2640] Port cluster expose feature to Cluster Service 2.x

- docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md
- ubuntu-16.04_k8-1.21_weave-2.8.1 announcement
- 1.17 removed
- 1.18 deprecated
- updated templates with highlighted version
@goelaashima @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1091)
> [VCDA-2647] Announce-Template-1.21.2-On-Github-Template-Announcement-Page

- container_service_extension/rde/backend/cluster_service_2_x.py
- docs/cse3_1/CLUSTER_MANAGEMENT.md
RDE status.phase is not being updated to CREATE:FAILED when rollback is set to True.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1093)
> [VCDA-2655] Set the RDE.status to FAILED on cluster creation failure when rollback=true

- container_service_extension/common/constants/shared_constants.py
- container_service_extension/installer/sample_generator.py
- container_service_extension/rde/common/entity_service.py
- docs/cse3_1/CLUSTER_MANAGEMENT.md
Fixed the typo in the TASK response header.
Updated the sample config file generator with master remote-cookbook-urls
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1100)
> Fixed the typo in response task header & updated the sample config with new remote-cookbook-url

- container_service_extension/rde/backend/cluster_service_2_x.py
- Fixes HTTP 401 error that happens due to token expiry between RDE REST operation(s)
- Always set the VCD behavior task status to SUCCESS or ERROR as the last operation in every cluster operation
- TODO/IN PROGRESS: testing
@sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1099)
> [VCD-2663] Mark terminal state of task to be the last operation on cluster CRUD

- container_service_extension/rde/common/entity_service.py
- Fixed **Error: RDE_RESTRICTED_FIELDS [ status ]** when cluster upgrade/resize.
- This fix prevents the tenant users with as few as or fewer than EDIT and VIEW rights on CSE:NATIVECLUSTER from updating **private** property of RDE **status** section
Before Fix:
After Fix:
@sahithi @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1103)
> [VCDA-2676] Prevent users with <= EDIT/VIEW rights on CSE:NATIVECLUSTER from updating private property of RDE Status

- container_service_extension/common/constants/server_constants.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/templates/remote_template_manager.py
- container_service_extension/installer/templates/template_builder.py
- container_service_extension/rde/backend/cluster_service_2_x.py
Whenever `-t` flag is used with `cse install/upgrade`, warn users that without a valid template in inventory, CSE startup will fail.
Additionally there was a bug in the way templates are updated from v1 to v2, the scripts files are not re-downloaded into proper v2 script directory. This PR fixes that issue too.
Testing done:
Ran `cse upgrade` with -t flag and checked console for the error message.
Ran a proper cse upgrade from 3.0.3 to 3.1.0, output attached below
```
(cse) D:\code\cse\container-service-extension>cse upgrade -c config.yaml -st
Required Python version: >= 3.7.3
Installed Python version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
Validating config file 'config.yaml'
InsecureRequestWarning: Unverified HTTPS request is being made. Adding …
```
> [VCDA-2667] Fix CSE install/upgrade to show better message around template creation/update

- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/common/entity_service.py
- container_service_extension/rde/models/rde_1_0_0.py
- container_service_extension/rde/models/rde_2_0_0.py
- Fixes RDE conversion failure: RDE 1.0 <--> 2.0
- Use cases:  RDE 1.0 cluster workflow on RDE 2.0 supported CSE, VCD 
- While creating new RDE 1.0(api version:35.0) on VCD that supports RDE 2.0(api version 36.0), RDE conversion from 1.0 to 2.0 and RDE conversion from 2.0 to 1.0 need to skip conversion of `status` section as there is no status section available during cluster creation phase.
- Entity update and delete to take requests from sys admin for not invoking hooks, if required
- Logger debug statements in task_update()
- Tested with sys admin workflow create, update and delete
- Tested native API endpoints with Accept:application/*;version=35.0 that uncovered this defect (RDE conversion error:`**'NoneType' object has no attribute 'control_plane'**  `(Using Postman)
-  **Testing in …
> [VCDA-2678]  Fix RDE status conversion error

- container_service_extension/installer/configure_cse.py
- Fix for legacy to RDE cluster upgrade failure
- Fixed failing upgrade from legacy to non legacy by checking the defined entity type in VCD before registering any defined entity schema
- Tested manually and verified the upgrade happened successfully thru CLI 
@rocknes @sahithi 
**Before fix**
**After fix**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1108)
> [VCDA-2693] Fixed legacy to RDE cluster upgrade failure

- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
While parsing the field `kubernetes` from RDE to determine the version of K8s installed on the cluster, CSE code incorrectly picks the second item in the fragmented list as the version. Ideally it should pick the last element in the list. This faulty logic causes cluster upgrade failures if the kubernetes string contains more than 2 words, e.g.
For, kubernetes = "Tanzu Kubernetes Grid 1.17.4"
The current  logic will incorrectly pick version as "Kubernetes".
This PR addresses the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1109)
> Fix K8s version parsing from RDE

- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/common/entity_service.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/utils.py
- container_service_extension/rde/validators/validator_rde_2_x.py
- container_service_extension/server/request_handlers/cluster_handler.py
- container_service_extension/server/request_handlers/request_utils.py
Legacy native K8s clusters are converted to RDE 1.0.0 or RDE 2.0.0 (depending on the VCD) during CSE upgrade. However during this conversion, the `StorageProfile` field in status section is not updated properly. This PR fixes it.
Additionally, this PR also 
1. improves the error message when RDE validation fails during various CSE workflows viz. cluster apply.
2. Refreshes the user context after native entitlement rights are added to roles explicitly by CSE or implicitly by VCD (e.g. built in roles)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1114)
> [VCDA-2703, VCDA-2699] Fix RDE creation/update during CSE upgrade

- container_service_extension/installer/configure_cse.py
- container_service_extension/server/service.py
CSE extension is stamped with CSE specific data to record which version of CSE is being installed, which api version is CSE using etc. This update helps with future CSE upgrades.
The data stamping is generally the last step of CSE upgrade to preserve idempotency of the upgrade process itself.
This also means that if we are upgrading from a CSE system that uses AMQP to one that uses MQTT as the message bus, the MQTT exchange won't be ready until the entire upgrade process is complete.
This poses an issue since the the cluster conversions (creation/update of RDE from cluster data on vapp metadata) will not go through since in VCD 10.3, CSE native RDE operations expect the CSE MQTT exchange to be present in the system.
To solve this problem, we are splitting the AMQP -> MQTT conversion and …
> Split CSE MQTT extension registration and description update as two separate phases

- container_service_extension/lib/telemetry/constants.py
- Move VAC url back to staging
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1129)
> [VCDA-2170] Move VAC url back to staging

- container_service_extension/lib/telemetry/constants.py
- Port the changes from master on `Move VAC url back to staging` for telemetry
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1130)
> [PR] Telemetry - Move VAC url back to staging (#1129)

- container_service_extension/request_processor.py
Cluster list when CSE server is running in api_version 34.0 used to return the following error - 
`Invalid url - not found`
This PR fixes this and error.
Testing done:
* Create cluster and list all the. clusters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1134)
> [VCDA-2724] Fix cluster list when cse server running in api-version 34.0

- container_service_extension/def_/cluster_service.py
- container_service_extension/vcdbroker.py
`kubectl drain ...` command which is executed when upgrading cluster and deleting cluster fails when OLM is present as reported by the issue 
https://github.com/vmware/container-service-extension/issues/1102.
This PR adds `--force` parameter to the `kubectl drain` command so that the node can be drained.
Testing:
cluster upgrade
@rocknes @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1133)
> [VCDA-2691] Fix upgrade failure when OLM pods are present

- container_service_extension/rde/backend/cluster_service_2_x.py
-  Updated the RDE delete failures after resolving entity
-  Verified all the exceptions are logged with `exec_info=True` (exception trace)
-  Verified unlogged exceptions are raised
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1135)
> [VCDA-2700] Update CSE logs for delete entity on resolution error

- container_service_extension/def_/cluster_service.py
Users are unable to add NFS node to TKG clusters based on Ubuntu 20.04. The reason behind the failure is due to how CSE executes the nfsd.sh file on the newly created VM. Typically by the time CSE tries to run the script, the VM guest customization is over and the root password is set properly. However in case of Ubuntu 20.04, guest customization is taking way longer than usual and as a result the root password is not set properly by the time CSE tries to run the script. This leads to a failure in the `vsphere-guest-run` library and CSE can't recover from it.
Addition of worker nodes don't face the same issue, because CSE executes a script on master node to fetch its IP, before it tries to run any script on the worker VM. This gives the guest customization process on the worker VM enough …
> [VCDA-2648] Fix NFS node addition to TKG cluster

- container_service_extension/def_/cluster_service.py
Porting changes made by PR https://github.com/vmware/container-service-extension/pull/1109 to cse_3_0_updates
While parsing the field kubernetes from RDE to determine the version of K8s installed on the cluster, CSE code incorrectly picks the second item in the fragmented list as the version. Ideally it should pick the last element in the list. This faulty logic causes cluster upgrade failures if the kubernetes string contains more than 2 words, e.g.
For, kubernetes = "Tanzu Kubernetes Grid 1.17.4"
The current logic will incorrectly pick version as "Kubernetes".
This PR addresses the issue.
--- …
> Port fix K8s version parsing from RDE to cse_3_0_updates

- setup.cfg
- setup.py
Referenced: https://gist.github.com/althonos/6914b896789d3f2078d1e6237642c35c for setup.cfg variables
Testing:
* validated if `python_requires` field is functional by setting value to `>= 3.8` and used python 3.7 to install the created build
@sakthisunda @rocknes @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1140)
> Remove hyphenated variables in setup.cfg

- setup.cfg
Referenced: https://gist.github.com/althonos/6914b896789d3f2078d1e6237642c35c for setup.cfg variables
Testing:
* validated if `python_requires` field is functional by setting value to `>= 3.8` and used python 3.7 to install the created build
@sakthisunda @rocknes @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1147)
> Port Remove hyphenated variables in setup.cfg to master

- setup.cfg
Referenced: https://gist.github.com/althonos/6914b896789d3f2078d1e6237642c35c for setup.cfg variables
Testing:
* validated if `python_requires` field is functional by setting value to `>= 3.8` and used python 3.7 to install the created build
@sakthisunda @rocknes @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1148)
> Port Remove hyphenated variables in setup.cfg to cse_3_1_updates

- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/server/vcdbroker.py
`kubectl drain ...` command which is executed when upgrading cluster and deleting cluster fails when OLM is present as reported by the issue 
https://github.com/vmware/container-service-extension/issues/1102.
This PR adds `--force` parameter to the `kubectl drain` command so that the node can be drained.
Testing:
cluster upgrade
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1146)
> Port Fix upgrade failure when OLM pods are present to CSE 3-1 updates

- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/server/vcdbroker.py
`kubectl drain ...` command which is executed when upgrading cluster and deleting cluster fails when OLM is present as reported by the issue 
https://github.com/vmware/container-service-extension/issues/1102.
This PR adds `--force` parameter to the `kubectl drain` command so that the node can be drained.
Testing:
cluster upgrade
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1145)
> Port [VCDA-2691] Fix upgrade failure when OLM pods are present to master

- container_service_extension/installer/templates/remote_template_manager.py
porting https://github.com/vmware/container-service-extension/pull/1143 to cse_3_1_updates
Testing done:
* Check if exceptions are caught if incorrect cookbook url is supplied during CSE run
@rocknes @sakthisunda @ltimothy7 @sahithi @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1144)
>  Port [VCDA-2723]Handle exceptions when connecting to remote template cookbook to cse_3_1_updates

- container_service_extension/installer/templates/remote_template_manager.py
Porting https://github.com/vmware/container-service-extension/pull/1137 to master
Testing done:
* Check if exceptions are caught if incorrect cookbook url is supplied during CSE run
@rocknes @sakthisunda @ltimothy7 @sahithi @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1143)
> Port [VCDA-2723]  Handle exceptions when connecting to remote template cookbook to master

- container_service_extension/common/constants/server_constants.py
- container_service_extension/installer/templates/tkgm_template_manager.py
- container_service_extension/server/request_dispatcher.py
- container_service_extension/server/request_handlers/template_handler.py
- container_service_extension/server/service.py
Expose GET /api/cse/template/tkgm endpoint to retrieve TKGm templates in CSE catalog.
Additionally during CSE startup, read all TKGm template into memory.
Testing Done:
Invoked GET /api/cse/template/tkgm from POSTman and made sure that the response received is correct
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1168)
> [VCDA-2768] Expose TKGm template list API endpoint

- cluster_scripts/v2_x/control_plane_customization.sh
- cluster_scripts/v2_x/node.sh
- container_service_extension/common/constants/server_constants.py
- container_service_extension/common/utils/pyvcloud_utils.py
- container_service_extension/exception/exceptions.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/backend/common/network_expose_helper.py
- container_service_extension/rde/common/entity_service.py
- Base 64 encoded value of kubeconfig in vm extra config
- Read kubeconfig from vm extra config and store in RDE 
- Read kubeadm token from vm extra config in RDE, if not found fallback to getting it from control-plane extra config 
- worker node creation, resize use RDE stored values
- Updated kubeconfig based on expose cluster logic stored back in RDE
- Entity update - Replace sysadmin only check with user role with cse:nativeCluster full access rights
- Tested create with and without worker node, resize cluster with worker node, delete cluster
- Testing in progress
@arunmk @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1164)
> [VCDA-2737] store kube config, kubeadm token in rde

- container_service_extension/common/constants/server_constants.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/utils.py
- container_service_extension/rde/validators/validator_rde_2_x.py
CPU and memory fields should be allowed only for native and TKG+
* User cannot specify both  cpu/ memory and sizing class during cluster deployment
* If cluster is created using cpu/memory, it cannot be resized using sizing class and vice-versa
* cse upgrade should add the cpu and memory fields in the spec section if the cluster is upgraded from legacy mode to non-legacy mode.
Testing done:
* create cluster
* resize cluster (up and down)
* cse upgrade with existing clusters
@sakthisunda @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container- …
> [VCDA-2571] Use cpu/mem fields for native cluster operations

- .gitignore
- cluster_scripts/v2_x_tkgm/control_plane.sh
- cluster_scripts/v2_x_tkgm/node.sh
- container_service_extension/common/constants/server_constants.py
- container_service_extension/common/constants/shared_constants.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/rde/backend/common/network_expose_helper.py
- container_service_extension/rde/models/common_models.py
- container_service_extension/rde/utils.py
- cse_def_schema/schema_2_0_0.json
There is a series of changes here geared towards TKGm effort. Since @sakthisunda's changes diverged quite a bit from @ltimothy7 's codebase, I took all of @ltimothy7 's code and overwrote the cluster_service_tkgm file with the cluster_service_2_x file and began to make changes to get things working. While doing that some of @ltimothy7 's changes were re-applied while a few ones were added.
The overall changes made over @sakthisunda 's code are:
1. some isolated locations where the TKGm constants need to be added in order to get basic things like `vcd cse cluster list` working and `cse server run`
2. some changes needed to get template using only name and not revision; additional changes to use template name rather than catalog_item_name while creating a vm
3. removal of upgrade codepaths, …
> TKGm with @sakthisunda changes for removal of guest customization libraries

- container_service_extension/client/template_commands.py
- container_service_extension/common/constants/server_constants.py
- container_service_extension/common/utils/server_utils.py
- container_service_extension/installer/sample_generator.py
- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/rde/utils.py
- container_service_extension/server/cli/server_cli.py
- container_service_extension/server/request_handlers/template_handler.py
- container_service_extension/server/service.py
- container_service_extension/server/vcdbroker.py
Removed code that 
1. Checked for presence of at least one native template as well as default template during CSE server startup
2. Chose default template if none is provided during cluster operations. Now, an error would be thrown instead.
3. Generated default template and revision in sample config
Fixed a bunch of flake8 errors.
Testing:
Was able to successfully startup CSE with no native templates in system.
Tried to deploy a native cluster and verified that it failed with proper error.
```
(cse) D:\code\cse\container-service-extension>vcd task wait 12f5ef7a-d112-4c44-a218-73bde685c7ed
task: 12f5ef7a-d112-4c44-a218-73bde685c7ed, result: error, message: Template 'ubuntu-16.04_k8-1.20_weave-2.6.5' at revision 2 not found.
```
--- …
> [VCDA-2855] Let CSE server startup without a default native template

- cluster_scripts/v2_x_tkgm/control_plane.sh
Remove internal nameserver and keep google's
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1191)
> VCDA-2877: Remove vmware internal nameserver

- container_service_extension/client/cluster.py
- container_service_extension/client/de_cluster_tkg_s.py
- container_service_extension/client/ovdc.py
- container_service_extension/client/utils.py
- container_service_extension/common/constants/server_constants.py
- container_service_extension/common/utils/core_utils.py
- container_service_extension/installer/config_validator.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/lib/cloudapi/cloudapi_client.py
- container_service_extension/mqi/mqtt_extension_manager.py
- container_service_extension/rde/common/entity_service.py
- container_service_extension/rde/constants.py
- container_service_extension/rde/utils.py
- container_service_extension/server/compute_policy_manager.py
- container_service_extension/server/service.py
Using VCDApiVersion object for comparing versions instead of converting to float.
Testing done:
* cse upgrade
* cse run
* cluster create (TODO)
* cluster resize (TODO)
@sakthisunda @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1180)
> [VCDA-2669] Replace float version comparisions with version object comparisons

- cluster_scripts/v2_x_tkgm/control_plane.sh
- cluster_scripts/v2_x_tkgm/node.sh
- container_service_extension/common/constants/server_constants.py
- container_service_extension/installer/config_validator.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/rde/common/entity_service.py
- requirements.txt
VCDA-2670: vcd['host'] should not specify scheme in config file (MQTT does not understand it)
VCDA-2706: RDE should validate site (validates http format and also if the value is same as set in config)
VCDA-2895: Remove DNS related configuration (use VCD setup)
The additional change is that the requirements.txt did not have a few dependencies that were called from source. The PyCharm IDE added them cleanly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1198)
> VCDA-2670, 2706, 2895: DNS and site validations

- container_service_extension/server/cli/server_cli.py
- rename `-d all` option to `-d native` in cse template list
- tested manually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1197)
> [VCDA-2861] rename option all to native of cse template list

- container_service_extension/common/utils/server_utils.py
- container_service_extension/common/utils/vsphere_utils.py
- container_service_extension/installer/config_validator.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/sample_generator.py
- container_service_extension/installer/templates/template_builder.py
- container_service_extension/lib/nsxt/cluster_network_isolater.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/rde/backend/cluster_service_factory.py
- container_service_extension/rde/common/entity_service.py
- container_service_extension/rde/utils.py
- container_service_extension/security/authorization.py
- container_service_extension/security/security.py
- container_service_extension/server/pks/pks_cache.py
- container_service_extension/server/service.py
- container_service_extension/system_test_framework/utils.py
- requirements.txt
* Added a new key in config file under `service` section. viz. `tkgm_only_mode`. This mode allows the provider to omit the entire `vcs` section from the config file, as well as it suppresses any piece of code in CSE that tries to connect to the vSphere server(s) either directly or via guest-run-library.
* Added relevant code in config sample generator, and config validation.
* Added checks in `cse template install`, `cse install` and `cse upgrade` to make sure that these command don't create templates if `tkgm_only_mode` is set to True in config file.
* config validation will remove `vcs` section from server runtime config if the flag `tkgm_only_mode` is set to True. This makes sure that even if the code paths in vcdbroker, cluster_service_1_x or cluster_service_2_x tries to connect to …
> [VCDA-2856] Allow CSE server to function in Only TKGm mode

- container_service_extension/client/sample_generator.py
- container_service_extension/installer/templates/tkgm_template_manager.py
- container_service_extension/rde/models/rde_1_0_0.py
- container_service_extension/rde/models/rde_2_0_0.py
Improve sample cluster spec generation for native and TKGm
1. TKGm - Delete NFS section, Add default cidrs for pod and service. Change default of `expose` value to True.
2. Native - Hide pod and service cidr sections
Make sure that the new TKGm 1.4.0 OVAs are not flagged by the regex matcher.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1206)
> [VCDA-2894, VCDA-2906] Improve sample cluster spec generation, Add support for TKGm 1.4.0 OVA

- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/templates/remote_template_manager.py
During CSE upgrade, clusters are processed and their RDE is created or updated depending on what type of cluster they are viz. legacy or RDE 1.0.0 based. Currently in CSE 3.1.0 the check to determine the cluster type is done at a high level by looking at the registered RDE (or their absence). This logic is vulnerable to changes in RDE registration (done by CSE upgrade/install) and this can lead to situations where clusters can be misclassified as RDE 1.0.0 based while they are legacy style clusters.
To fix this issue, we have changed the logic to be at cluster level. Each cluster is processed individually and the first level of check is to find the corresponding RDE, if RDE is missing it is assumed that the cluster is legacy style. If the RDE is found, it's version is determined and the …
> [VCDA 2849] Make cluster processing during CSE upgrade idempotent

- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/rde/utils.py
- container_service_extension/rde/validators/abstract_validator.py
- container_service_extension/rde/validators/validator_rde_2_x.py
- container_service_extension/server/behavior_handler.py
- container_service_extension/server/request_handlers/cluster_handler.py
* Fill up cpu and memory properties in status section for tkgm clusters
* Validation changes to include cpu and memory validation for TKGm clusters
* If TKGm cluster was created using cpu/memory, Do not ignore sizingClass in validation for resize.
* Remove conditional logic which prevented displaying cpu and memory properties in cluster apply --sample command
Testing done:
* Create TKGm cluster using cpu/memory. Try resizing the cluster with a sizing Class other than system default. (should fail)
* Create TKGm cluster using a sizing Class (other than system default) and resize using cpu/memory (should fail)
* Create TKGm cluster using cpu/memory, resize the cluster using same value for cpu/memory (should succeed)
* Create …
> [VCDA-2902] TKGm to make use of cpu and memory properties for cluster operations

- container_service_extension/client/command_filter.py
- container_service_extension/client/cse_client/cse_client.py
- container_service_extension/client/de_cluster.py
- container_service_extension/client/de_cluster_native.py
- container_service_extension/client/de_cluster_tkg_s.py
- container_service_extension/common/utils/pyvcloud_utils.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/installer/right_bundle_manager.py
- container_service_extension/lib/nsxt/nsxt_backed_gateway_service.py
- container_service_extension/mqi/mqtt_extension_manager.py
- container_service_extension/rde/acl_service.py
- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/rde/backend/common/network_expose_helper.py
- container_service_extension/security/context/operation_context.py
- container_service_extension/server/cli/server_cli.py
- container_service_extension/server/compute_policy_manager.py
- container_service_extension/server/service.py
- container_service_extension/system_test_framework/environment.py
In current CSE code, often CloudApiClient is being used without any loggers, as a result we are losing a lot of valuable logs. This PR addresses all such code flows and adds loggers (both debug and wire) wherever a CloudApiClient is being created from standard pyvcloud client.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1210)
> Improve logging for code paths using CloudApiClient

- container_service_extension/rde/backend/cluster_service_2_x.py
- Fix for native/tkg+ cluster resize failure
- New changes of VCDA-2884 and VCDA-2925 needs flattened RDE status dictionary for RDE update operations for updating status
- Affected operations: cluster resize and node delete
- Verified with creating a new cluster, resize
@Anirudh9794 @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1213)
> [VCDA-2958] fix cluster resize, delete nodes failure

- container_service_extension/lib/telemetry/constants.py
- container_service_extension/lib/telemetry/payload_generator.py
- container_service_extension/lib/telemetry/telemetry_handler.py
- container_service_extension/server/cli/server_cli.py
- container_service_extension/server/request_handlers/template_handler.py
- Telemetry for `cse template import`
- `cse_user_actions`, `cse_template_import`
- Tested and verified creating TKGm template
cse_user_actions:
cse_template_import:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1201)
> [VCDA-2834] telemetry for import template

- container_service_extension/common/constants/server_constants.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/rde/validators/validator_rde_2_x.py
For some fields (pod and svc cidr), the validator functions do not work since they are only present in the spec section and not the status section. For these fields, the ideal way out is to add them to the status section. Until that happens, we bypass them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1215)
> VCDA-2953: Ensure that pod and svc cidrs go through validation

- container_service_extension/installer/config_validator.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/common/entity_service.py
- container_service_extension/rde/models/rde_2_0_0.py
- container_service_extension/server/cli/server_cli.py
- container_service_extension/server/service.py
Fixed sample generation to generate the correct hierarchy for pod and service cidr blocks
With `no_vc_communication_mode`, CSE should disallow users from creating new templates, native clusters or any other operation that requires VCenter communication. In a previous PR, new template creation command viz. `cse template install` has been suppressed whenever the flag in question is set to 'True'. However, users could effectively smuggle native templates via `cse upgrade` and then use them to deploy native clusters which would fail with unpredictable errors since VC communication has been turned off. To prevent these unpredictable errors, CSE will stop loading any native templates during startup if the is_vc_communication_mode flag is set to True.
Signed-off-by: rocknes …
> [VCDA-2944, VCDA-2946] Fix sample generation, Stop loading native templates during CSE startup if `no_vc_communication_mode` flag is turned on

- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- This change fixes the NAT rule creation with the right privilege
- Removed the escalated privilege that happened during refactoring for post boot customization
- Tested TKGm cluster creation with  CSE server startup using **service account**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1222)
> [VCDA-2947] Fix escalated privilege on NAT rule creation

- container_service_extension/installer/configure_cse.py
Because we are checking `tkg` in template name to identify the template as TKG+ while processing clusters in cse upgrade,
TKGm templates, if present, will be identified as TKG+ tempalte.
This PR fixes the string being matched to prevent such upgrade errors
Testing done:
* Created a cluster with TKGm in no_vc_communication_mode: true and successfully upgraded cse to no_vc_communication_mode: false
@rocknes @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1220)
> Fix TKGm template being identified as TKG+ during cluster upgrade

- container_service_extension/rde/backend/cluster_service_2_x.py
- Fixed the unexpose network in native cluster update
- Check for desired and current unexpose and trigger DNAT deletion
- Tested with existing network exposed cluster with DNAT rule 
-  Verified the DNAT gets removed on cluster apply with network.expose:false
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1224)
> [VCDA-2974] Fix unexpose network in native cluster update

- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/validators/validator_rde_2_x.py
- container_service_extension/server/vcdbroker.py
We have introduced new fields to RDE 2.0.0 in CSE 3.1.1 which were not present in RDE 2.0.0 of CSE 3.1.0. Hence, any upgrade from CSE 3.1.0 -> CSE 3.1.1 should update the existing RDEs to have proper value in the new fields viz. status.nodes.[control_plane|worker].[cpu|memory]
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1223)
> [VCDA-2959] Populate cpu/mem fields in status section of RDEs while upgrading from CSE 3.1.0 to CSE 3.1.1

- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/server/request_handlers/cluster_handler.py
- container_service_extension/server/vcdbroker.py
- Fix missing source description, id in telemetry for native and tkgm operations
- Before fix, when recording telemetry CRUD details in service (native, tkgm) code, the thread context looses the source id and description. This is fixed by extracting telemetry details with source information in handler logic before delegation to behavior implementation.  The affected operations are CREATE, DELETE, UPDATE and CONFIG
- Tested and verified manually in staging telemetry tables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1204)
> [VCDA-2783] Fix missing source id in telemetry

- container_service_extension/rde/models/rde_1_0_0.py
In RDE 2.0.0, TKGm clusters have `nfs` section in `status` set to null, as a result while converting to RDE 1.0.0, we need to take care that we don't try to iterate over None object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1226)
> [VCDA-2982] Check presence of NFS section before converting it

- container_service_extension/server/service.py
- Fix `vcd cse template list` when `no_vc_communication_mode` is true
- KeyError got fixed by initializing native template list to empty list
- Tested manually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1231)
> [VCDA-2985] Fix vcd cse template list

- container_service_extension/system_test_framework/environment.py
- system_tests_v2/base_config.yaml
- system_tests_v2/conftest.py
- system_tests_v2/test_cse_client.py
Included 2 flags `should_install_prerequisites` and `is_cse_server_running` to help local testing.
Since the current tests make a lot of API calls to try setting up the environment even if it has already been set up by a previous run or by the developer themself, it takes a long time to even get started with running the tests. This PR fixes the issue by introducing 2 flags `should_install_prerequisites` and `is_cse_server_running`. With this change a developer can run test_cse_client.py by starting a CSE server in parallel.
--- …
> Make local testing easier by skipping creation of prerequisites

- cluster_scripts/v2_x_tkgm/control_plane.sh
- cluster_scripts/v2_x_tkgm/node.sh
- Increase logging level for `kubeadm init `and `kubeadm join`
- Tested and verified by creating a cluster with control-plane and worker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1233)
> [VCDA-2983] Raise logging level for kubeadm init and join

- system_tests_v2/test_cse_client.py
* add expect_failure as an input instead of deriving it from the expected status.
* Wait for RDE to reach UPGRADE:SUCCEEDED state before checking for the presence of nfs node in delete-nfs test
@rocknes @andrew-ni @sakthisunda @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1254)
> [VCDA-3034] Fix for 10.3.1 CToT

- cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
- cluster_scripts/v2_x_tkgm/cloud_init_node.yaml
- container_service_extension/common/constants/server_constants.py
- container_service_extension/common/utils/pyvcloud_utils.py
- container_service_extension/installer/sample_generator.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- Inject http proxy configuration from cse server config file
- New section namely `extra_options` in server config file
- New tkgm only proxy variable in server config:`tkgm_http_proxy, tkgm_https_proxy, tkgm_no_proxy`
- Updated cloud-init control plane and node scripts
- Tested in special testbed setup created using:[NSXT-Setup](https://confluence.eng.vmware.com/display/VCD/NSX-T+Testbed+Outbound+Access+Setup)
- Ref: [TKGm-Squid setup](https://confluence.eng.vmware.com/pages/viewpage.action?spaceKey=VCD&title=Proxy+Configuration+on+TKGm+clusters)
- verified cluster creation with no proxy setup fails with:` Error adding control plane node: failure on creating nodes:/root/control_plane.sh: wget -O $antrea_path https://github.com/vmware-tanzu/antrea/releases/download/v0.11.3/antrea.yml`
- …
> [VCDA-3072] Server-Config-Proxy-Support

- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- Fixed failing cluster creation on empty extra_options in server config
- Explicit verfication of empty extra_options 
- Tested cluster creation successfully
@Anirudh9794 @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1267)
> [VCDA-3161] Handle-Empty-Tkgm-Proxy-Extra-options

- container_service_extension/installer/configure_cse.py
- container_service_extension/lib/telemetry/payload_generator.py
- container_service_extension/lib/telemetry/telemetry_handler.py
- container_service_extension/server/cli/server_cli.py
- system_tests/test_cse_server.py
- system_tests_v2/test_cse_server.py
Removed the option to install K8s templates during CSE install/upgrade.
Associated telemetry payload was modified too.
Additionally, updated the system tests to accommodate the change in behavior of `cse install`.
Testing Done:
Ran `cse install` and `cse upgrade` and made sure that the option to skip templates is gone, and templates are not installed during the command execution anymore.
Pending: Run CToT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1274)
> [VCDA-3191, VCDA-3204] Remove option to install templates during CSE install/upgrade

- container_service_extension/client/de_cluster.py
- container_service_extension/common/constants/shared_constants.py
- container_service_extension/common/utils/core_utils.py
- container_service_extension/rde/common/entity_service.py
- Filter out the capvcd kind clusters for now to unblock CSE native/tkg clusters operations
- Issue noticed when the CLI user persona has both native and CAPVCD clusters created.
- Tested using CLI. Endpoint works fine with POSTMAN testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1272)
> [VCDA-3183] Fix broken CSE cluster commands

- container_service_extension/common/constants/server_constants.py
- container_service_extension/rde/backend/cluster_service_factory.py
- container_service_extension/server/request_handlers/cluster_handler.py
Using cluster service function for getting kubeconfig
Tested getting TKGm and native kubeconfig
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1276)
> [VCDA-3206] Avoid waiting on behavior task in the Native API kubeconfig handler

- container_service_extension/common/utils/server_utils.py
- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- system_tests_v2/base_config.yaml
* Added flag `test_mode` to server config file
* Set `test_mode` to true in system tests
* When test_mode is true, introduce a 1 min wait before executing scripts in the guest OS for the first time
Testing done:
Ran CToTs:
10.2.2: https://sp-taas-vcd-butler.svc.eng.vmware.com/view/CSE/job/CTOT4-CSE/2332/
10.3.2: https://sp-taas-vcd-butler.svc.eng.vmware.com/view/CSE/job/CTOT4-CSE/2329/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1277)
> [VCDA-3083, VCDA-3102] Add wait before cluster creation when creating clusters from CTOTs

- container_service_extension/common/utils/core_utils.py
- container_service_extension/installer/config_validator.py
- container_service_extension/installer/configure_cse.py
- container_service_extension/lib/telemetry/telemetry_handler.py
- container_service_extension/lib/telemetry/telemetry_utils.py
- container_service_extension/server/cli/server_cli.py
* Made the -c/--config param optional
* Added -x/--extra-option new param, this param takes two strings as input (key-value), this param can be repeated
* In case --config option is not provided by user, the -x params are used to create a dummy config dictionary in memory and passed onto the following methods
* Every method in the template import workflow that depends on config has been redesigned to explicitly state the actual fields of config it uses. This helps immensely to narrow down the scope of the dummy config file.
* A minimum set of required fields have been defined, if all of them is not specified by -x option, CSE will prompt the user to enter them interactively.
* Additional care has been taken to make sure that type-casting is done properly to the input key-value (str, str) …
> [VCDA-3192] Remove dependency on config file from the commands `cse template import`

- container_service_extension/server/request_dispatcher.py
After the recent changes to ServerConfig object, `request_dispatcher` is still using index operator to access elements in the config dictionary, and a result of this, any REST call that invoked the `feature_flag` path would fail.
This PR fixes the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1306)
> Fix failing ovdc system tests 

- container_service_extension/installer/configure_cse.py
- container_service_extension/rde/models/common_models.py
- container_service_extension/rde/schema_service.py
Issue : https://github.com/vmware/container-service-extension/issues/1280
Fix : CSE now queries for only nativeCluster RDE types before casting them to CSE specific RDE type model objects. Additionally changed the description field in DefEntityType and DefEntityType2_0 to Optional[str].
Testing done:
Manually added a non CSE RDE type with null description. Ran `vcd cse cluster list` and made sure that the warning is no longer being displayed with the fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1304)
> [VCDA-3247] Fix `vcd cse cluster list` shows JSON warning

- container_service_extension/logging/logger.py
- container_service_extension/server/service.py
- CSE logger support extended for remote Syslog
- In addition to local logging, if there is Syslog server specified in CSE server config, logging happens at Syslog server end
- Supported and tested for server info, debug, server wire, cloud wire
- `Tested with the syslogd in a remote VM`
**rsyslog.conf changes required**
```
Edit /etc/rsyslog.conf : Uncomment the following entries
module(load="imudp")
input(type="imudp" port="514")
Rules to be defined in rsyslog configuration
local0.*                        -/var/log/cse-logs/server-info.log
local1.*                        -/var/log/cse-logs/server-debug.log
local2.*                        -/var/log/cse-logs/server-wire-debug.log
local3.*                        -/var/log/cse-logs/cloudapi-wire.log
local4.* …
```
> CSE Support-For-Syslog

- cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
- container_service_extension/common/constants/server_constants.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- Using TKR bom to get antrea version for R1 TKGm clusters
- R1 RDE should only specify "antrea" as the cni and not the version since we do not currently support the vm to update the cni version
Tested with 1.3.0 (no antrea in bom), 1.4.0 (antrea 0.11.3 in bom ), and 1.4.1 (antrea 0.13.3 in bom) ovas
Verified RDE only shows "antrea"
- @Anirudh9794 @arunmk @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" …
> [VCDA-3237] Using TKR bom for antrea version

- container_service_extension/installer/templates/tkgm_template_manager.py
- Fixes the warning message for the valid TKGm Ova(s) that were shipped recently
- The latest version of the TKGm OVA (shipped with 1.4.2 and 1.5.1) have a different name pattern. CSE server CLI has a check on valid names based on allowed pattern. This pattern has been updated in this fix to include new naming of TKGm as a valid name
- Tested the import with new OVAs. Verfied that no more warning messages on these names
```
cse template import -F ~/Downloads/ubuntu-2004-kube-v1.20.14+vmware.1-tkg.2-5a5027ce2528a6229acb35b38ff8084e.ova 
cse template import -F ~/Downloads/ubuntu-2004-kube-v1.22.5+vmware.1-tkg.2-f838b27ca494fee7083c0340e11ce243.ova 
```
@Anirudh9794 @ltimothy7 @arunmk
--- …
> Fix warning message on importing TKG ova template 

- container_service_extension/rde/backend/cluster_service_1_x.py
- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- container_service_extension/rde/models/common_models.py
Description:
* to suport python3.10, pkg_resources.open_text() should receive string arguments
* `pkg_resources` uses modules which are shipped along with python
* previous versions of python used to work with the existing code because the Enums were converted to a string within the function `pkg_resources.open_text()`.
Testing done:
* Start the server (makes sure the schema is loaded using `load_rde_schema()`)
* Create TKGm cluster with 1 control plane and 1 worker. (makes sure code in cluster_service_2_x_tkgm.py is executed)
* Create cluster with native template and 2.0 RDE (makes sure code in cluster_service_2_x.py is executed)
* Create cluster with native template and 1.0 RDE (makes sure code in cluster_service_1_x.py is …
> [VCDA-3435] update pkg_resources.open_text() calls to be made with string arguments

- container_service_extension/installer/templates/tkgm_template_manager.py
If the underlying catalog item of a TKGm template is renamed in VCD, the metadata on the catalog item goes out of sync, specifically the field `name`. This leads to the issue where CSE is unable to locate the affected template during cluster creation. To fix this issue, CSE will detect such name changes and automatically update the metadata. The operation will be done only for TKGm templates and will be triggered during CSE startup and whenever the template definition held in CSE server's memory is refreshed via REST api.
Testing Done:
Renamed TKGm template in vCD and started up CSE server.
The output on the console during startup.
```Skipping loading k8s template definition from catalog since `No communication with VCenter` mode is on.
Loading TKGm template definition from catalog
Found …
```
> [VCDA-3485] Update TKGm template metadata if it is renamed in VCD

- container_service_extension/client/cluster_commands.py
- Fixed `vcd cse cluster delete ` for legacy cluster
- Force delete is not supported for legacy cluster. Since this option is made hidden, the handler method in CLI needs to set defult value for --force option. 
- Error message: `TypeError: cluster_delete() missing 1 required positional argument: 'force'`
- Tested for both legacy, native and tkgm cluster delete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1334)
> Fix vcd cse cluster delete for legacy cluster

- cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
- cluster_scripts/v2_x_tkgm/cloud_init_node.yaml
- container_service_extension/common/constants/server_constants.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
Tanzu-cli on the worker node needs the tkr k8s version to use. Previously, this version was retrieved in the control plane node, but it was not written to the control plane extra config to be used in the worker node when installing tanzu cli.
This issue fixes the cluster creation failure seen in the TKGm 1.5.1 k8s 1.22 ova.
@arunmk @sakthisunda
--- …
> Fix for using tkr k8s version in node script

- container_service_extension/lib/nsxt/nsxt_backed_gateway_service.py
- container_service_extension/rde/backend/common/network_expose_helper.py
If multiple exposed clusters are being deployed by CSE is parallel, they can easily run into a state where DNAT rule creation for one cluster, puts the gateway in BUSY state and as a result the other DNAT rule creation operation fails. In this PR we have added few retries while adding the DNAT rule to potentially alleviate the gateway lock-up state.
Testing Done:
Wrote a script that calls the method nsxt_gateway_svc.add_dnat_rule() from two different threads simultaneously to create two DNAT rules on the same edge gateway. Verified from logs that the second operation fails because of BUSY gateway and is retried by the fixed code. Both DNAT rules were created successfully after a small delay.
22-03-30 22:35:25 | nsxt_backed_gateway_service:175 - add_dnat_rule | ERROR :: Error creating dnat …
> [VCDA-3410] Retry creation of DNAT rule on failure

- container_service_extension/rde/backend/cluster_service_2_x.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- Remove DNAT rule unconditionally
- Force deleting a cluster should not check status of `exposed` on the cluster. Often, cluster failures do not set the RDE status to the actual values. This causes missed DNAT rule deletion and IP address consumption and blocks and require manual deletion of DNAT to release the IP
- Tested on TKGm and verified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1339)
> [VCDA-3458] remove conditional check for DNAT rule removal on Force Delete

- container_service_extension/common/constants/server_constants.py
- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- Fix cpu,memory size defaults to Tkgm node size; 
- Fix vm update to change cpu, memory
- VCDA-3565,VCDA-3569
- Tested with defaults 
- Tested with memory, cpu in cluster specifction
- Tested with sizingClass in cluster specification
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1344)
> Fix cpu,memory size defaults to Tkgm node size; Fix vm update issues

- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- Fix for futureWarning for not checking the task for none
- Error message:`FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1345)
> FutureWarning fix

- container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
- Fix for `Error:Status code: 403/ACCESS_TO_RESOURCE_IS_FORBIDDEN, [ dd88ceaa-47f2-46c1-a158-0fb9072d28ad ] Either you need some or all of the following rights [Base] to perform operations [VAPP_VIEW] for 75b5b162-35a4-444b-bdab-faab5d71cd6b or the target entity is invalid. (request id: dd88ceaa-47f2-46c1-a158-0fb9072d28ad)
`
- Power on operation on a vm is a special operation where authorization check to access the vm is done multiple times. Since in our case the security context is getting wiped out during the power on operation, the secondary authorization checks are failing and that results in the 403 error.
- Fix description: CSE service account to its absolute minimum during cluster deployment. Use service account client and vapp only for accessing and updating extra config for post …
> [VCDA-3509] Tkgm cluster create fix for vapp view forbidden error 

- system_tests_v2/test_cse_client.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1369)
> disable nfs test for ctots

- docs/cse3_1/KNOWN_ISSUES.md
- If there is an error in getting API token for a TKGm cluster, the cluster create task will run forever.
- This should be documented as a known issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1407)
> [VCDA-3455] Document known issue - cluster create task running forever due to failure to get API token

- Pipfile
- Pipfile.lock
- requirements.txt
Certifi is a carefully curated list of trusted root certificate authorities that Mozilla maintains. These are essential for computers to trust hosts who have certificates issued by one of these trust authorities. Recently TrustCor was removed from the list, and as a result we should update certifi package in CSE. This PR changes the requirement on certifi to pull the latest version always, this will automatically help us to keep our systems up to date.
Testing done:
Installed CSE with the changes. Ran `cse template list -s -d remote` and verified that it worked properly
Signed-off-by: Aritra Sen <sena@sena0MD6R.vmware.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container …
> [VCDA-5114] Update certifi to the latest version to address TrustCor root certificate revocation

- docs/cse3_1/RELEASE_NOTES.md
- docs/cse3_1/TEMPLATE_ANNOUNCEMENTS.md
- updated template announcements on containerd for ubuntu-20.04_k8-1.23_weave-2.8.1  
- Existing ubuntu-20.04_k8-1.23_weave-2.8.1 uses containerd 1.4 that reached end of support. 
- Template customization requires a force recreate of the template. 
- @rocknes @Anirudh9794 @ltimothy7 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1418)
> [VCDA-5294] Template update announcement

- system_tests_v2/test_cse_client.py
-  Disable delete-nfs test 
-  This unblocks ctot failure that fails on delete-nfs in test environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1423)
> VCDA-6112 Disable delete-nfs test
