vmware/container-service-extension

cse/template_automation_scripts/README.md
cse/template_automation_scripts/ansible_hosts
cse/template_automation_scripts/kub.json
cse/template_automation_scripts/kub_master.sh
cse/template_automation_scripts/kub_minion.sh
cse/template_automation_scripts/kubernetes_cluster.yaml
cse/template_automation_scripts/template.sh
cse/template_automation_scripts/vcd_vapp.yaml

Signed-off-by: Anshima Gupta <anshima123@gmail.com>

Packer scripts for kub master and worker template creation

---

container_service_extension/processor.py
setup.cfg

Signed-off-by: auppunda <auppunda@github.com>

allow client to fetch swagger files, packaged swagger with cse

---

ChangeLog
container_service_extension/processor.py

Signed-off-by: auppunda <auppunda@gmail.com>

added ability to fetch yaml swagger file

---

container_service_extension/client/cse.py
docs/README.md

Signed-off-by: Timo Sugliani <timo.sugliani@gmail.com>

Markdown cosmetic/doc fixes

---

container_service_extension/broker.py
container_service_extension/client/cluster.py
container_service_extension/client/cse.py
container_service_extension/cluster.py
container_service_extension/config.py
container_service_extension/consumer.py
container_service_extension/cse.py
container_service_extension/processor.py
container_service_extension/service.py
cse.sh
docs/README.md
test-requirements.txt
tox.ini

- added `node create/list/delete` commands
- improved installation

towards 0.3.0

---

.travis.yml
container_service_extension/broker.py
container_service_extension/config.py
container_service_extension/cse.py
format-code.sh
requirements.txt
test-requirements.txt
tests/cluster.py

- validates settings before creating template
- updated requirements version
- added format-code.sh script

VCDA-415: validate settings before creating template

---

ChangeLog
container_service_extension/broker.py
container_service_extension/cluster.py
container_service_extension/service.py
container_service_extension/utils.py
requirements.txt
scripts/cust-ubuntu-16.04.sh
tests/add-nodes.sh
tests/create-clusters.sh
tests/info-clusters.sh

- fix #67 Ubuntu template preparation
- fix #68 node list
- mask password in debug logging
- set password using guest operations

template preparation fix and cluster info

---

LICENSE.txt
NOTICE.txt
container_service_extension/broker.py
container_service_extension/client/cluster.py
container_service_extension/cluster.py
container_service_extension/config.py
container_service_extension/consumer.py
container_service_extension/service.py
docs/README.md
requirements.txt
scripts/cust-photon-v2.sh
scripts/cust-ubuntu-16.04.sh
scripts/mstr-ubuntu-16.04.sh
setup.cfg

- wait for network to be available
- fix issue when creating Ubuntu template and DHCP is not available
- installation of go, glide and download of harbor is commented out until future usage
- fixed amqp connection issue
- create amqp exchange during the install if necessary
- upgrade to kubernetes 1.9.3 in ubuntu
- improved guest password configuration. It is recommended to set new password in the templates in `config.yaml` and re-create the templates
- updated dependencies
- this version of the PhotonOS template doesn't upgrade the OS to the latest version, since there is a problem with the latest version of `open-vm-tools`
- updated license files
- improved installation and validation of the AMQP settings
Signed-off-by: Paco Gomez <contact@pacogomez.com>

Vesion 0.4.2

---

ChangeLog
requirements.txt
scripts/cust-photon-v2.sh
scripts/cust-ubuntu-16.04.sh

- fixes #72 updated weave download parameter, ubuntu and photon
- fixes #73 upgrades ubuntu without upgrading vmtools
- updated dependencies
- removed unused download steps

Fix template preparation

---

CODE_OF_CONDUCT.md
PULL_REQUEST_TEMPLATE.md

Added documents to meet recommended Github community standards.
Reviewers: @pacogomez , @sahithi

VCDA-356: Add code of conduct and pull request template

---

AUTHORS
ChangeLog
container_service_extension/config.py
container_service_extension/utils.py
docs/README.md

1. Force users to provide vCenter service account
2. Documentation on minimum privileges required for vCenter service account.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/91)

[VCDA-566] Force users to provide vCenter service account

---

docs/README.md
docs/nfs_static_pv.md

Documentation on Known Issues
1. NFS protection
2. Ubuntu template creation failures
3. Template clean up
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/104)

VCDA-611: Documentation on Known issues

---

container_service_extension/client/cse.py
container_service_extension/config.py
container_service_extension/processor.py

Ran basic cse installation and commands to make sure nothing broke
@rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/102)

[VCDA-710] Replace yaml.load() with yaml.safe_load()

---

container_service_extension/config.py

Before this fix, if specified catalog already existed, it wouldn't
be shared with other orgs. If specified catalog did not exist,
it would be created, but would not be shared. CSE installation
would crash because we did not reload the org representation after
the POST call.
This fix creates the catalog if needed, always shares the catalog
to other orgs, and properly reloads the org representation
Tested with all CSE commands
@sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/108)

[VCDA-755] Ensure templates catalog is always shared

---

container_service_extension/config.py

Minor refactoring to configure_amqp_settings() to make settings display more consistent, when showing the user current settings and the settings listed in their config file. Also added a redundancy check, so that user is only prompted to configure amqp if current settings are different than desired settings.
@sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/110)

Skip AMQP configuration if current settings are same as config file settings

---

docs/README.md
docs/nfs_static_pv.md

Documentation on below two items:
1. Minimum privileges required to create a VCD service account
2. CSE-vCD compatibility matrix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/109)

[Doc] Privileges required for VCD service account & CSE-VCD compatibility matrix

---

AUTHORS
ChangeLog
LICENSE.txt
NOTICE.txt
open_source_license_container-service-extension_1.2.0_GA.txt
setup.cfg

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/116)

Upload License files for CSE

---

container_service_extension/config.py

Commit 6fca204 caused a
regression where if the vCD and config AMQP settings were the same,
CSE installation would skip AMQP configuration. However, just
because the settings were the same, doesn't mean the AMQP exchange
exists. The workaround for this was to change the name of the vCD
AMQP exchange to trigger the AMQP configuration option during
CSE install.
Now, if settings are the same, AMQP exchange will still be
checked/created unless the user says 'no' during the prompt
Tested CSE install and all `--amqp` options.
- When user specifies `--amqp skip`, amqp settings are not configured and exchange is not created.
- When user specifies `--amqp config`, amqp settings are configured and exchange is created
- When default option `--amqp prompt` is used and user specifies 'no', amqp is not …

Fix amqp setup

---

container_service_extension/client/cse.py
container_service_extension/cluster.py

Added a 'status' column for `vcd cse cluster list` command, so
users can see if all VMs in the cluster are turned on and
running properly
Fixes vmware/container-service-extension#58
@sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/117)

Add `status` display for `vcd cse cluster list`

---

AUTHORS
ChangeLog

Updated change log for cse after pushing version 1.2.2 to pypi.

Updated ChangeLog after push to pypi

---

README.md
docs/CONTRIBUTING.md
docs/NFS_STATIC_PV.md
docs/README.md
docs/RELEASE_NOTES.md

Fix for documentation rendering errors.
@sahithi @pacogomez
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/140)

Fix CSE Documentation

---

container_service_extension/broker.py
container_service_extension/cluster.py
container_service_extension/exceptions.py

- Custom exception handling implemented for create cluster
- By raising custom exception on each step of create cluster, it helps in rollback and better client side processing. Manual testing done to verify the custom message as part of the create cluster failure information.
- @andrew-ni  @harshneelmore @sahithi @sompa @rocknes 
Signed-off-by: Sakthi Sundaram <sakthis@vmware.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/151)

[VCDA-809] Exception handling implementation for create cluster

---

container_service_extension/broker.py
container_service_extension/config.py
container_service_extension/service.py
container_service_extension/utils.py

Created general use functions in utils.py. Functions in
config.py are specific to either CSE installation or config
file processing.
Split up template creation phase into independent functions.
create_template() handles '--update' option, and decides when
to create vapp, customize vapp, capture vapp, and delete vapp.
create_temp_vapp() handles the temp vapp creation and
customization phase of CSE installation. This function calls
create_vapp_from_config() and customize_vm().
create_vapp_from_config() initializes the vapp specifically for
CSE installation, using the initialization script.
customize_vm() customizes the vapp's vm using the customization
script.
capture_vapp_to_template() captures the vapp as a vapp template
to vcd catalog.
Simplified control flow and exception handling. …

[VCDA-789] Refactor CSE Installation - template creation

---

docs/README.md

Signed-off-by: Harshneel <moreh@vmware.com>
- Following is the list of minimum user rights required to install CSE. Tested by creating a user in VCD with the following Rights and then did a successful installation of CSE.
- @andrew-ni @sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/152)

[VCDA-806] Full list of required rights for limited account for CSE

---

docs/README.md
docs/RELEASE_NOTES.md

@goelaashima @sahithi @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/165)

Update Release Notes for 1.2.4

---

ChangeLog
docs/RELEASE_NOTES.md
scripts/cust-photon-v2.sh
scripts/cust-ubuntu-16.04.sh
scripts/mstr-photon-v2.sh
scripts/mstr-ubuntu-16.04.sh

Signed-off-by: Harshneel More <moreh@vmware.com
- Upgraded packages for Ubuntu and Photon templates in installation scripts 
- Tested the above changes by doing the fresh install of CSE templates, creating clusters and running a Redis Master deployment on the Kubernetes cluster(
- @sahithi @andrew-ni @sakthisunda @yilmi-vmw
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/169)

[VCDA-828 K8s upgrade packages 

---

container_service_extension/broker.py
container_service_extension/client/cluster.py
container_service_extension/exceptions.py
container_service_extension/utils.py

-  Include exception short, long and stacktrace in error message 
-  pass detailed error message from the server 
Output-1:  Error: Cluster 'cluster-xxxx' not found.
Output-2: task: 75a949d0-a4f6-4b8f-ae48-f4fc4097b2e6, result: error, message:
{ "**message**": {"reason": "('Error while adding master node:'",
"**description**": "('Error while adding master node:', 'VcdTaskException; 
500/INTERNAL_SERVER_ERROR: error ([ f0369c72-81d6-4e5a-ba48-a289ddb66123 ] Unable to 
perform this action. Contact your cloud administrator.)')", 
"**stacktrace**": [" more than 500 character long stacktrace not included here"]}}
@andrew-ni @sahithi @harshneelmore @rocknes @sompa
---
This …

[VCDA-798] Create cluster server exception enhancement

---

container_service_extension/broker.py
container_service_extension/cluster.py
container_service_extension/exceptions.py

- Implemented rollback for node creation failures.
- Refactored rollback_decorator to combine cluster creation and node creation.
- Tested the above implementation manually by creating faulty clusters and nodes.
- @sakthisunda @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/172)

[VCDA-817] Implement rollback for node creation failure

---

container_service_extension/broker.py
container_service_extension/client/cluster.py
container_service_extension/config.py
container_service_extension/exceptions.py
container_service_extension/utils.py

Client side exception handling
Processing of all http responses on synchronous requests; Handles both system and cluster commands. 
Manually tested all the vcd cse cluster system commands and cse install to verify amqp connection exception.
@andrew-ni @harshneelmore @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/179)

[VCDA-825] client side exception handling

---

container_service_extension/broker.py
container_service_extension/utils.py

- Gets the ovdc resource pool of org-vdc
-  For a given org-vdc name and an optional org-name, this function gets the ovdc resource pool name and id.
- @sahithi @sompa @rocknes @andrew-ni @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/197)

[VCDA-852] Get ovdc resource pool

---

container_service_extension/abstract_broker.py
container_service_extension/authorization.py
container_service_extension/broker.py
container_service_extension/cluster.py
container_service_extension/config.py
container_service_extension/cse.py
container_service_extension/exceptions.py
container_service_extension/logger.py
container_service_extension/processor.py
container_service_extension/server_constants.py
container_service_extension/service.py
container_service_extension/utils.py

* Added abstract_broker that enforces the interface required to implement the authorization framework
* Introduced a new decorator 'secure' that checks for specified rights in the user role who invokes the CSE command.
* refactored broker.py to adhere to abstract_broker's contract.
* broker now gets the header and body of the request as params during initialization.
* made changes to processor to account for change in broker.
* fixed flake8 errors.
Testing : 
1. Registered a new right viz. Right1 to CSE extension via REST.
2. Added the right to a new org
3. Created a two roles, Role1 which contains Right1 and Role2 which doesn't contain Right1
4. Created two users, User1 with Role1 and User2 with Role2.
5. Cluster create operations succeed for User1, while it fails for User2 with …

[VCDA-856] Authorization framework in CSE

---

container_service_extension/ovdc_cache.py

- Flake8 errors fixed
- All docstring fixes to comply with flake8 requirements

[VCDA-853-B] Flake8 validated

---

container_service_extension/authorization.py
container_service_extension/broker.py
container_service_extension/configure_cse.py
system_tests/base_config.yaml

Introduced a new config key value pair under the service section. This config element can be used to intruct  CSE to either enforce authorization checks on incoming requests or skip the check.
Testing Done:
1. Ran server withe the config entry set to false
2. A user without the deploy right can deploy a cluster
3. Restarted the server with the config entry set to true
4. A user without the right cannot deploy a cluster
5. A user with the right can deploy a cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/210)

[VCDA-871] Implement toggle switch for CSE authorization

---

container_service_extension/configure_cse.py
container_service_extension/server_constants.py

Signed-off-by: Harshneel More <moreh@vmware.com>
- Add new right for CSE and PKS for authorization.
- If the right exists then we just move on, duplicate rights with the same name are not registered.
- Tested manually to register new right at cse install, along with cse install -u.
- @rocknes @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/211)

[VCDA-843] Update CSE install method to add rights for CSE and PKS authorization

---

docs/CSE_ADMIN.md
docs/INSTALLATION.md
docs/INTRO.md
docs/NFS_STATIC_PV.md

No content changes, just spelling. My editor automatically
removes trailing spaces, so those are also removed.
Signed-off-by: Glenn McElhoe <gmcelhoe@vmware.com>

Fix minor spelling and spacing issues

---

container_service_extension/configure_cse.py
container_service_extension/utils.py
system_tests/test_cse_server.py

Adjusts rights registration attempt to occur only if CSE is registered to vCD
@rocknes @harshneelmore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/213)

Fix rights registration bug

---

requirements.txt

Running system tests for validation. Will edit once they finish.
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/217)

Update pyvcloud>=20.0.3, vcd-cli>=21.0.2

---

docs/KNOWN_ISSUES.md
docs/RBAC.md
docs/RELEASE_NOTES.md
docs/TROUBLESHOOTING.md
docs/_data/navigation.yml

* Added public documentation for the new feature Role Based Access Control.
* Added release notes for the new version of CSE.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/218)

[VCDA-864] Add documentation for RBAC, update release notes.

---

docs/RELEASE_NOTES.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/238)

Add release notes for 1.2.7

---

docs/RELEASE_NOTES.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/239)

Fix formatting in release notes

---

container_service_extension/configure_cse.py

@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/245)

[VCDA-892] Fix bad sample values

---

container_service_extension/configure_cse.py
system_tests/base_config.yaml

Forgot to update Docker and Kubernetes version descriptions for vApp templates. This PR fixes those descriptions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/254)

Update Docker and Kubernetes version descriptions

---

container_service_extension/broker_manager.py
container_service_extension/client/cluster.py
container_service_extension/pksbroker.py

- Optimize List Cluster 
- Add more properties from pks list clusters result set that helps in extracting ovdc name for each cluster in a single pks api call. Also fixed request spec passing the vdc value correctly. Manual test completed on latest code from master.
@sahithi @rocknes @sompa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/282)

[VCDA-869] Enhance Cluster List - Optimization 

---

container_service_extension/broker_manager.py
container_service_extension/client/cse.py
container_service_extension/client/ovdc.py
container_service_extension/ovdc_cache.py
container_service_extension/pksbroker.py
container_service_extension/processor.py

Client and server side implementation of 'vcd cse ovdc list' command.
Testing done as sys-admin, org-admin and non-admin.
Output looks something like below:
> vcd cse ovdc list
container_provider    name       org
============================ 
pks                   ovdc-PKS   pepsi
vcd                   ovdc-vCD   pepsi
none                  ovdc-coke  coke
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/281)

[VCDA-931] Implementation of ovdc list command

---

container_service_extension/client/cluster.py
container_service_extension/client/cse.py

-This CL includes changes to enhance create cluster command in CSE to accommodate PKS cluster creation for both server and client.
-Manually tested the command vcd cse cluster create with the new options for creation of clusters on PKS
E.g. vcd cse cluster create delhi --pks-external-hostname api.pks.local --pks-plan 'Plan 1'
- @sahithi @sakthisunda @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/278)

VCDA-933: Enhance create cluster command

---

container_service_extension/abstract_broker.py
container_service_extension/broker_manager.py
container_service_extension/client/cluster.py
container_service_extension/client/cse.py
container_service_extension/exceptions.py
container_service_extension/pksbroker.py
container_service_extension/processor.py
container_service_extension/vcdbroker.py

- This PR enhances the `vcd cse cluster config` command to include an optional `vdc` param on the client side to efficiently retrieve the configs of the cluster. On the server side, added a new method to broker manager to get cluster configs based on the broker returned. 
Added a method to retrieve cluster config for pks clusters in PKSBroker.
- Tested all the following commands to ensure we get the expected output : 
vcd cse cluster config 'my-vcd-cluster' 
vcd cse cluster config 'my-vcd-cluster' -v 'vcd-vdc'
vcd cse cluster config 'my-pks-cluster' 
vcd cse cluster config 'my-pks-cluster' -v 'pks-vdc'
- @sahithi @sakthisunda @rocknes
--- …

VCDA-937: Enhance Cluster config command to accomodate PKS config command.

---

container_service_extension/exceptions.py

Missed exceptions.py file as part of previous submit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/298)

[VCDA-947] Bugfix (update pks bits)

---

container_service_extension/client/ovdc.py

Fixing disable ovdc operation.
Disable ovdc operation currently fails looking for a particular key.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/306)

Fixing disable ovdc operation.

---

container_service_extension/configure_cse.py
system_tests/base_config.yaml
system_tests/scripts/CUST-UBUNTU.sh
system_tests/scripts/cust-ubuntu-16.04.sh

- Updated Ubuntu 16.04 description for Docker and Kubernetes versions
- Updated system-test base-config description and ubuntu scripts.
- @rocknes @andrew-ni @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/305)

Update ubuntu 16.04 description and system test template

---

container_service_extension/broker_manager.py

Today on CSE upgrade CSE falls back to vCD for deploying clusters if the oVDC isn't enabled.
We want to have support for oVDCs that don't support deploying Kubernetes cluster on them at all.
To address this behavior. CSE will now look for PKS configuration, if it finds one, it will expect the provider to enable the oVDCs explicitly for the K8 provider to use. If the such an enable has not been made, CSE will simply raise an error.
However if PKS configuration is missing from the system, CSE will use only vCD to deploy containers on all oVDCs.
Testing done:
Tried to deploy clusters on non enabled oVDC in a PKS aware setup, received the correct error message. 
The tests were performed on two different oVDC, one of them being backed by PKS VC and the other one being backed by vanilla vCD VC. …

[VCDA-981] Updated logic to determine fallback broker to preserve CSE behavior on upgrade

---

docs/_data/navigation.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/319)

Documentation fix to add Enterprise PKS page to main document.

---

docs/ENT-PKS.md
docs/_data/navigation.yml

[Doc] Fixing comptibility matrix of Enterprise PKS enablement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/320)

[Doc] Fixing comptibility matrix of Enterprise PKS enablement

---

docs/RBAC.md

Updated RBAC doc page with new PKS related rights
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/313)

[VCDA-990] Update RBAC doc page with PKS operation rights.

---

docs/ENT-PKS.md
docs/_data/navigation.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/321)

[Doc] Fixing web links in Enterprise PKS enablement

---

docs/ENT-PKS.md

[Doc] Cosmetic edits on Enterprise PKS enablement.

---

docs/CSE_ADMIN.md
docs/ENT-PKS.md

[Doc] Fix weblinks in Enterprise PKS enablement

---

docs/ENT-PKS.md

[Doc] Added vCD-Enterprise PKS vCenter connection as a known issue and the workaround.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/327)

[Doc] Added vCD-Enterprise PKS vCenter connection as a known issue and the workaround.

---

container_service_extension/broker_manager.py
container_service_extension/cluster.py
container_service_extension/pksbroker.py
container_service_extension/pyvcloud_utils.py
container_service_extension/vcdbroker.py

Added org_name column to be displayed in vcd cse cluster list command. 
-Tested manually with native-vcd and pks-ent
-Tested with different personas - Sysadmin, org-admin and vappauthor
- @rocknes @sahithi @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/315)

[VCDA 974] List clusters need to have org_name column

---

LICENSE.txt
NOTICE.txt
open_source_license_container-service-extension_2.0_GA.txt
setup.py

Updated the license and notice files with their updated versions.
Testing done:
With the new files in place, created a whl distribution of CSE and installed it via pip. No errors were observed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/341)

[VCDA-1029] Updated OSL file 2.0.0 GA release.

---

container_service_extension/configure_cse.py
docs/CLUSTER_ADMIN.md
docs/CSE_ADMIN.md
docs/ENT-PKS.md
docs/KNOWN_ISSUES.md
docs/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/340)

Documentation updates for CSE 2.0

---

container_service_extension/client/cse.py
container_service_extension/cse.py

- Updated  **cse.py** and **client/cse.py** cli help strings
- Removed `--save option` from `vcd cse cluster config`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/336)

[VCDA-1016] Update CLI help strings

---

docs/KNOWN_ISSUES.md

Documentation updates to CSE 2.0 GA

---

docs/KNOWN_ISSUES.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/360)

Add DNS suffix bug info to known issues doc

---

docs/ENT-PKS.md

Added doumentation for below two items:
Why OIDC has to be disabled?
Why Pay-as-you-model for org-vdc(s) must be avoided?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/362)

Documentation on OIDC and Pay-as-you-go models for ovdc

---

container_service_extension/install_utils.py
system_tests/test_cse_client.py
system_tests/test_cse_server.py

Revert unintentionally checked in code related to
* check_file_permission in install_utils.py
* system tests - subprocess related changes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/379)

Revert unintentionally checked in code in file_permission_check and subprocess .

---

container_service_extension/configure_cse.py
scripts/cust-photon-v2.sh
scripts/cust-ubuntu-16.04.sh
system_tests/test_cse_server.py

Photon and Ubuntu customization scripts now upgrade packages to latest version (linux kernel and others)
Removed unnecessary steps in customization scripts
Also added a necessary reboot step to _customize_vm()
Jenkins job 109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/376)

Upgrade packages in template vApps to address vulnerabilities

---

container_service_extension/broker_manager.py
container_service_extension/client/cluster.py
container_service_extension/client/cse.py
container_service_extension/client/ovdc.py
container_service_extension/client/system.py
container_service_extension/cluster.py
container_service_extension/ovdc_manager.py
container_service_extension/ovdc_request_handler.py
container_service_extension/pks_cache.py
container_service_extension/pksbroker.py
container_service_extension/processor.py
container_service_extension/pyvcloud_utils.py
container_service_extension/server_constants.py
container_service_extension/service.py
container_service_extension/shared_constants.py
container_service_extension/utils.py
container_service_extension/vcdbroker.py

- Replace node type constants with NodeType enum
- Replace http method strings with RequestMethod enum
- Replace server action constants with ServerAction enum
- Replace bare request key strings with RequestKey enum
To start refactoring client/server communication and request handling, we need an interface that defines request data. These enums act as that interface for CSE client and server.
Tests have passed locally. Currently running test builds #149 and #150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/386)

Organize constants/bare strings into enums for data consistency

---

container_service_extension/system_test_framework/environment.py
system_tests/test_cse_client.py

Added persona support to system test framework. Replaced existing System_Toggle test for enable/disable the system with new framework tests using batch processing.
- Manually tested the tests.
- @rocknes @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/384)

[VCDA-1098] Add persona support for system test framework

---

.travis.yml
container_service_extension/abstract_broker.py
container_service_extension/broker_manager.py
container_service_extension/pksbroker.py
container_service_extension/pksbroker_manager.py
container_service_extension/request_handlers/cluster_handler.py
container_service_extension/request_processor.py
container_service_extension/vcdbroker.py
container_service_extension/vcdbroker_manager.py
system_tests/test_cse_client.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/392)

Add cluster request handler and refactor brokers to use request dictionary

---

container_service_extension/cluster.py
container_service_extension/sample_generator.py
container_service_extension/service.py
container_service_extension/template_rule.py
container_service_extension/vcdbroker.py
system_tests/test_cse_client.py

* Added code to generate new optional section in configuration file that represents template override rules.
* Added code to process the rules during server startup and modify the template definition held in memory.
* Added code to honor the modified tempalte deinfition during cluster creation.
* Refactored cluster.py and vcd_broker.py to streamline the cluster creation process and default admin password management.
Testing done:
cse client system test - Passed
As sys admin, rant the following workflows manually:
1. create a cluster 
2. add a node in the cluster
3. delete a node in teh cluster
4. delete the cluster
pending : nfs node testing
--- …

[VCDA-1084, VCDA-1085] Introduction of template default over-ride rules 

---

container_service_extension/server_cli.py
container_service_extension/server_cli/cse.py
container_service_extension/service.py
setup.cfg

* Implemented cse template list command with all it's parameters. The command can run without a running CSE server.
* Moved the server cli module (cse.py) into a new package viz. server_cli
Testing done:
Ran the command with different param combinations, checked that no errors were reported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/401)

[VCDA-1060, VCDA-1063, VCDA-1064] - Implemented cse template list command

---

requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/400)

Update pyvcloud dependency to 20.1.1.dev73

---

container_service_extension/system_test_framework/environment.py
container_service_extension/system_test_framework/utils.py
system_tests/test_cse_client.py

Added persona-based test support for cse create cluster and list clusters.
Additionally, refactored cse system enable/disable.
_ Tested the changes locally waiting tests run on Jenkins pipeline 
- @rocknes @andrew-ni @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/396)

[VCDA-1093] Add persona based tests for cluster create and list

---

system_tests/test_cse_client.py

Added system test support for different personas[sys_admin, org_admin and vapp_author] for cluster info and config.
Tested manually
@rocknes @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/406)

[VCDA-1096] Add persona support for cluster info and config

---

container_service_extension/configure_cse.py
container_service_extension/server_cli.py

* Implemented cse template install command
* refactored cse install command to reuse template installation code
Testing Done:
Created both (ubuntu and photon) template using cse template install command.
Tried creating non existent template, got appropriate error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/407)

[VCDA-1066, VCDA-1068] Implement cse template install command

---

container_service_extension/system_test_framework/environment.py
system_tests/test_cse_client.py

Added persona support for node operations - create/list/info/delete.
Tested manually
Jenkins test in-progress
- @rocknes @andrew-ni @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/409)

[VCDA-1095] Add persona support for node operation

---

container_service_extension/system_test_framework/environment.py
requirements.txt
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/417)

Update requirement pyvcloud >= 20.1.1.dev90

---

container_service_extension/authorization.py
container_service_extension/client/cluster.py
container_service_extension/client/cse.py
container_service_extension/compute_policy_manager.py
container_service_extension/service.py
container_service_extension/vcdbroker.py

- Fix RBAC code bug in authorization.py
- Enable implementation of removing policy when policy is empty during compliance check
- Fix client-side cluster config accept type
- Update docstrings and command help strings to include --template-name and --template-revision option information for cluster create, cluster resize, and node create
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/419)

Add template name and resize to cluster resize

---

container_service_extension/sample_generator.py
requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/423)

Update pyvcloud and vcd-cli requirement for CSE 2.5.0

---

container_service_extension/vcdbroker.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/424)

Add todo hack to fix how default values are handled

---

docs/CSE_ADMIN.md
docs/ESS-PKS.md
docs/INSTALLATION.md
docs/RELEASE_NOTES.md
docs/_data/navigation.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/422)

CSE 2.5.0beta1 docs

---

container_service_extension/cluster.py

Put in checks to validate VM customization scripts runs to make sure that there are no errors while running the script on the VM.
Tested manually by create/delete/list/info on nodes.
- @andrew-ni @rocknes @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/427)

[VCDA-1193] Check VM customization script runs for errors

---

container_service_extension/template_builder.py
system_tests/test_cse_server.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/428)

Add debug messages to server tests

---

container_service_extension/service.py

vCD has a bug where api version 33.0 cannot remove a compute policy from a template (compute policy gets reassigned automatically).
There is another error case in template compute policy replacement during template compliance check. To do this replacement, we do a GET on the template resource, update the `VdcComputePolicy` element, and do a PUT on the same resource. This results in a conflict between the `VdcComputePolicy` element and the `ComputePolicy` element.
Using api version 32.0 circumvents these error cases because the 32.0 GET call does not contain a `ComputePolicy` element.
This PR adds a workaround by forcing the template compute policy compliance check to use api version 32.0 during the compliance check at server startup if the config file api version is 33.0+.
using api …

[VCDA-1195] Force template compute policy removal client to api version 32.0

---

docs/TROUBLESHOOTING.md

- Updated log file names.
- Troubleshooting section has information about log files. This fix updated the names of the log files that are in use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/446)

[VCDA-1231] Updated Log file names

---

container_service_extension/sample_generator.py
requirements.txt

pyvcloud version revised to 21.0.0
vcd-cli version revised to 22.0.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/451)

Bump up version requirement for pyvcloud and vcd-cli

---

container_service_extension/sample_generator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/453)

Fix typos in CSE sample text

---

docs/CSE_SERVER_MANAGEMENT.md
docs/TEMPLATE_MANAGEMENT.md
docs/_data/navigation.yml

Fixed navigation bar for pages with only 1 sub topic
Fixed few of the sample CSE commands to exclude [OPTIONS]

Navigational edits in CSE 2.5.0 docs

---

docs/KNOWN_ISSUES.md

Added a new issue found in CSE 2.5 and workaround for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/460)

Update Known Issues for CSE 2.5

---

docs/KNOWN_ISSUES.md

For PR #461
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/462)

Update known issues

---

docs/KNOWN_ISSUES.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/464)

Fix duplicated heading in known issues

---

container_service_extension/template_builder.py
system_tests/base_config.yaml
system_tests/test_cse_server.py
test-requirements.txt

- Removed the unnecessary reboot step for ubuntu template creation
- Removed unnecessary system test check where we ssh into VMs to check for installed packages
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/468)

Remove unnecessary reboot in template creation

---

docs/CSE_CONFIG.md
docs/KNOWN_ISSUES.md
docs/RELEASE_NOTES.md
docs/TEMPLATE_ANNOUNCEMENTS.md
docs/TROUBLESHOOTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/465)

Update known issues and release notes for CSE 2.5.1

---

container_service_extension/config_validator.py
container_service_extension/configure_cse.py
container_service_extension/encryption_engine.py
container_service_extension/sample_generator.py
container_service_extension/server_cli.py
container_service_extension/service.py
container_service_extension/utils.py
requirements.txt
system_tests/test_cse_server.py

- CSE supports encrypted configuration file
- As part of security requirements, this commit includes changes for the following
* Encryption of configuration file
* Decryption of configuration file
* cse install, run, template, check, convert-cluster handling encrypted configuration
* Option for skipping encryption
* Exception handling for failed encryption/decryption
- Manual testing completed successfully
cse encrypt, cse decrypt, cse run, cse install, cse template, cse convert-cluster, cse check
@andrew-ni @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/474)

[VCDA-1268] CSE support for encrypted configuration file

---

container_service_extension/request_handlers/request_utils.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/484)

[VCDA-1305] Fix bad error message when required key is missing

---

container_service_extension/vcdbroker.py

Fixes #471 
Tested
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/485)

[VCDA-1286] Allow 0 worker node cluster creation

---

container_service_extension/config_validator.py
container_service_extension/sample_generator.py
system_tests/base_config.yaml

- Config changes to support telemetry by default. 
- Added necessary changes to `cse sample and cse check` to support config file key/value 
under ervice->telemetry
- Tested and verified
cse sample
cse check
@andrew-ni  @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/488)

[VCDA-1317] config key added to support telemetry

---

container_service_extension/configure_cse.py
container_service_extension/local_template_manager.py
container_service_extension/request_handlers/cluster_handler.py
container_service_extension/sample_generator.py
container_service_extension/server_cli.py
container_service_extension/server_constants.py
container_service_extension/vcdbroker.py
system_tests/base_config.yaml

Upgraded cse cluster convert command to update pre-existing clusters with
appropriate software version metadata
Updated any metadata processing to better handle this new metadata
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/487)

[VCDA-1293], [VCDA-1294] Add cluster/template metadata to track software versions

---

container_service_extension/client/cluster.py
container_service_extension/client/cse.py
container_service_extension/local_template_manager.py
container_service_extension/request_handlers/cluster_handler.py
container_service_extension/request_processor.py
container_service_extension/server_constants.py
container_service_extension/vcdbroker.py

Add client and server implementation for upgrade-plan operation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/492)

[VCDA-1311], [VCDA-1312] Add functionality to display upgrade plans for a cluster

---

container_service_extension/client/cse.py
container_service_extension/sample_generator.py
container_service_extension/server_cli.py

Increased default number of consumer threads from 5 to 10.
Updated help string for most of the CSE server CLI and client CLI.
Testing done : Flake8 passes without any errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/499)

[VCDA-1329,1343] Fix default number of consumer thread. Update help strings of CSE CLI commands

---

container_service_extension/config_validator.py
container_service_extension/configure_cse.py
container_service_extension/request_handlers/cluster_handler.py
container_service_extension/request_handlers/ovdc_handler.py
container_service_extension/request_handlers/system_handler.py
container_service_extension/server_cli.py
container_service_extension/telemetry/constants.py
container_service_extension/telemetry/payload_generator.py
container_service_extension/telemetry/telemetry_handler.py
container_service_extension/telemetry/telemetry_utils.py
container_service_extension/vcdbroker.py

- Record data for telemetry for all CSE operations
- Following telemetry data captured in this PR
- User action 
- User action details 
- All cluster operations
- All Node operations
- oVDC operations ( including compute policy )
- Server CLI ( Template, Install, Run, Config, encrypt, decrypt )
- System     
- Tested by executing all the CSE commands 
@andrew-ni @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/501)

[VCDA-1321] Telemetry workflow for CSE operations

---

requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/503)

Add version info for semantic-version dependency

---

container_service_extension/server_cli.py

The REST endpoint on vCD (/vapp/vm-id/guestcustomizationstatus) that indicates that Guest Customization is finished on a vm is broken. The status never changes to anything other than GC_PENDING. As a result of this broken monitor, CSE keeps perpetually waiting on the status to change and the convert-cluster operation never finishes.
As a workaround, in this PR we have changed the waiting mechanism. Instead of waiting on the REST endpoint, we straight up look in the guest customization section of the VM, to determine if the vm representation has changed or not. This still doesn't guarantee that Guest Customization is actually complete on the vm, but it is a step in the right direction. With this change convert cluster operation will end as soon as the VM model is updated in vCD. We can …

Fix indefinite wait on Guest Customization during convert-cluster operation

---

container_service_extension/sample_generator.py
requirements.txt

Update pyvcloud and vcd-cli library versions in requirements.txt
Also update cse sample command to point to vmware template repository and not Andrew's forked repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/509)

Update pyvcloud and vcd-cli library versions in requirements.txt

---

docs/CLUSTER_MANAGEMENT.md
docs/CSE_CONFIG.md
docs/CSE_SERVER_MANAGEMENT.md
docs/CSE_UI_PLUGIN.md
docs/ENT_PKS.md
docs/INSTALLATION.md
docs/KNOWN_ISSUES.md
docs/RBAC.md
docs/RELEASE_NOTES.md
docs/TEMPLATE_ANNOUNCEMENTS.md
docs/_data/navigation.yml

Update docs for CSE 2.6.0 beta
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/513)

Update docs for CSE 2.6.0 beta

---

docs/CSE_UI_PLUGIN.md

Fixing some small mistakes in CSE_UI_PLUGIN doc page

Fixing some small mistakes in CSE_UI_PLUGIN doc page

---

container_service_extension/client/cse.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/517)

Fix CSE client cli docstring consistency

---

requirements.txt

* Updated versions of pyvcloud and vcd-cli in requirements.txt
* Capped the versions to next major version for all dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/531)

[VCDA-1384] Update dependency for CSE 2.6.0

---

docs/TEMPLATE_ANNOUNCEMENTS.md

Updated template anouncement page to anounce the release of k8s 1.17 templates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/537)

Update Template anouncemnet page

---

container_service_extension/request_processor.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/543)

[VCDA-1423] Fix bug where auth token can be referenced before assignment

---

container_service_extension/client/cse.py
container_service_extension/client/pks.py
container_service_extension/client/pks_cluster.py
container_service_extension/configure_cse.py
container_service_extension/request_processor.py
container_service_extension/server_constants.py

- Separate Commmand group for PKS commands. Client side command implementation
- Command format: vcd cse pks-cluster <create|config|delete|info|list|resize>
-  Unique REST endpoints registered during CSE install. 
-  Invalid URL exception raised at server request processor, until server implementation is complete. Updated CSE command doc and help.
- Tested manually with all the supported PKS options and existing CSE commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/550)

Separate-Command-Group-For-PKS(Client Side Changes)

---

container_service_extension/configure_cse.py
container_service_extension/server_constants.py
container_service_extension/template_builder.py

- Changed temporary VM name to '<OS>-vm'
`cse install -c ~/test/config.yaml -s -f   ` ( Checked the name of the vm created for each template)
- `vcd cse cluster create mycluster -o myorg -v myorgvdc -n mynet `
- `vcd cse cluster list`
- `vcd cse cluster config mycluster -o ~/myclusterConfig `
- `kubectl get pods -A`
@sakthisunda @andrew-ni @rocknes
--- …

[VCDA-1270] Change Temp vm name to meaningful one

---

docs/CLUSTER_MANAGEMENT.md
docs/CONTRIBUTING.md
docs/CSE_CONFIG.md
docs/CSE_INSTALL_PREREQUISITES.md
docs/CSE_SERVER_MANAGEMENT.md
docs/CSE_UI_PLUGIN.md
docs/ENT_PKS.md
docs/INSTALLATION.md
docs/INTRO.md
docs/KNOWN_ISSUES.md
docs/RBAC.md
docs/RELEASE_NOTES.md
docs/TEMPLATE_MANAGEMENT.md
docs/TROUBLESHOOTING.md

Updated the docs for CSE 2.6.0 GA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/538)

[VCDA-1378] Update docs for 2.6.0 GA

---

container_service_extension/ovdc_utils.py

- multiple API calls are made to fetch metadata for each ovdc for ovdc list operation
- make use of typed query to decrease the number of API calls being made
- Before:
- After:
- @rocknes @andrew-ni @sakthisunda @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/562)

[VCDA-1272] Optimize ovdc list from server

---

container_service_extension/__init__.py
container_service_extension/authorization.py
container_service_extension/client/cse.py
container_service_extension/client/pks.py
container_service_extension/client/response_processor.py
container_service_extension/cloudapi/cloudapi_client.py
container_service_extension/compute_policy_manager.py
container_service_extension/config_validator.py
container_service_extension/configure_cse.py
container_service_extension/logger.py
container_service_extension/nsxt/nsxt_client.py
container_service_extension/pksbroker.py
container_service_extension/pyvcloud_utils.py
container_service_extension/remote_template_manager.py
container_service_extension/request_handlers/ovdc_handler.py
container_service_extension/server_cli.py
container_service_extension/service.py
container_service_extension/telemetry/telemetry_handler.py
container_service_extension/telemetry/telemetry_utils.py
container_service_extension/telemetry/vac_client.py
container_service_extension/template_builder.py
container_service_extension/template_rule.py
container_service_extension/utils.py
container_service_extension/vsphere_utils.py

- Logger changes for service clients as per [confluence page](https://confluence.eng.vmware.com/pages/viewpage.action?spaceKey=VCD&title=%5BDraft%5D+Proposal+-+Logging+for+CSE)
- created loggers:` CLIENT_WIRE_LOGGER, SERVER_CLI_LOGGER, SERVER_NSXT_WIRE_LOGGER, SERVER_PKS_WIRE_LOGGER, SERVER_CLOUDAPI_WIRE_LOGGER, NULL_LOGGER`
- initialization of loggers done in `container_service_extension/__init__.py`
- changed initialization for loggers
- passing Loggers to NSXT_client, PKS_broker and CloudAPI based on config and passed wire loggers too.
- all log files moved to `~/.cse-logs`
- All log files: 
- Enable client wire logging by setting the environment variable …

[VCDA-1481, 1482, 1483] Change logging strategy

---

container_service_extension/abstract_broker.py
container_service_extension/authorization.py
container_service_extension/compute_policy_manager.py
container_service_extension/ovdc_utils.py
container_service_extension/pksbroker.py
container_service_extension/pksbroker_manager.py
container_service_extension/pyvcloud_utils.py
container_service_extension/request_context.py
container_service_extension/request_handlers/native_cluster_handler.py
container_service_extension/request_handlers/ovdc_handler.py
container_service_extension/request_handlers/pks_cluster_handler.py
container_service_extension/request_handlers/system_handler.py
container_service_extension/request_handlers/template_handler.py
container_service_extension/request_processor.py
container_service_extension/service.py
container_service_extension/user_context.py
container_service_extension/vcdbroker.py
system_tests/test_cse_client.py
tox.ini

Write up: https://confluence.eng.vmware.com/pages/viewpage.action?pageId=614902423
- RequestContext is an abstraction for vcd api clients, and user-specific details.
- This abstracts away details involving user/sysadmin client creation/logout, obtaining user details (username, role, rights, id)
Based on https://github.com/vmware/container-service-extension/pull/571
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/584)

[VCDA-1477] Implement request context

---

container_service_extension/pksbroker.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/586)

Fix client in pksbroker

---

system_tests/test_cse_client.py

- Fix flake8 errors in CI
@rocknes @andrew-ni @sakthisunda @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/593)

Fix flake8 errors in system tests

---

system_tests/test_cse_client.py
tox.ini

Resolve flake8 errors in system tests
@rocknes @andrew-ni @sahithi @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/594)

Resolved flake8 errors for system tests

---

container_service_extension/cloudapi/cloudapi_client.py
container_service_extension/cloudapi/constants.py
container_service_extension/def_modules/entity_svc.py
container_service_extension/def_modules/models.py
container_service_extension/def_modules/schema_svc.py
container_service_extension/request_context.py
container_service_extension/user_context.py

1. Implemented _entity_svc.py_ - Methods to perform CRUD on entities.
2. Changed _models.py_  - Modified models to use _dataclasses_ instead of _NamedTuples_
3. Changed cloud API client to take new param _is_sysadmin_. This is to avoid redundant code in modules to restrict non-admin usage. Made some changes in _request_context.py_ and _user_context.py_ to accomodate cloudapi client changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/596)

VCDA-1497 Implement Defined Entity Service

---

container_service_extension/compute_policy_manager.py
container_service_extension/request_handlers/ovdc_handler.py

- Temporary fix for ovdc compute policy remove
- Testing:
`vcd cse ovdc compute-policy remove ..`
@rocknes @andrew-ni @sakthisunda @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/595)

Temporary fix for OVDC compute policy remove

---

container_service_extension/request_processor.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/612)

Fixing the (bug) method params of new def_cluster_handler.py

---

container_service_extension/client/cse.py
container_service_extension/compute_policy_manager.py
container_service_extension/configure_cse.py
container_service_extension/server_cli.py
container_service_extension/service.py
container_service_extension/utils.py
requirements.txt

- Implement functionality to insert CSE server version and VCD API version data to the CSE extension XML object
- Implement functionality for `cse run` to check for versioning compatibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/609)

[VCDA-1549] Add version tracking to CSE server

---

container_service_extension/configure_cse.py
container_service_extension/server_constants.py
container_service_extension/template_builder.py

- Tag templates with placement policies referenced in "type" of the template.
create a template and make sure it is tagged with the compute policy referenced in the "type" of the template.
@rocknes @sakthisunda @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/621)

[VCDA-1534] Tag templates with placement policies during template install

---

container_service_extension/template_builder.py
container_service_extension/vcdbroker.py

GC fix has been submitted in vCD, hence reverting the temporary fix that was checked in via #618. This also means that the regression for photon template with older vCD builds will be fixed with this PR.
However photon templates with current vCD (10.2) are still broken due to another bug in vCD. So they will remain defunct for the time being.
Testing done:
Created a ubuntu based template successfully using latest CSE code and vCD 10.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/629)

Revert Pull#618 - Since GC fix is in vCD

---

container_service_extension/def_/cluster_service.py
container_service_extension/def_/utils.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/631)

Change the ID format of the interface and entity type.

---

container_service_extension/def_/cluster_service.py
container_service_extension/def_/models.py
cse_def_schema/api_v35/schema.json

Include kubernetes, cni, docker and os sections in schema, make changes in cluster create.
Testing done:
Created a CSE installation with the updated schema, created cluster using postman and checked if the above mentioned fields are populated
@rocknes @sahithi @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/630)

[VCDA-1571] update schema with k8s, cni, docker and os info

---

container_service_extension/client/command_filter.py
container_service_extension/configure_cse.py
container_service_extension/def_/entity_service.py
container_service_extension/def_/schema_service.py
container_service_extension/exceptions.py
container_service_extension/request_handlers/request_utils.py
container_service_extension/request_handlers/v35/def_cluster_handler.py
container_service_extension/service.py

- Exception handler added  for Entity_service and schema service
-  Exception handler for invalid input : Def cluster handler.py
-  Cse Install and Run throwing detailed error message on def schema related failure
- Cluster create command hidden for API version 35
- Manually tested for entity service, schema service CRUD with Postman for exception conditions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/628)

[VCDA-1568] Exception-Handler For Defined Entity Services and Cluster Handler

---

system_tests/base_config.yaml
system_tests/test_cse_client.py
system_tests/test_cse_server.py

Revert changes to system tests to run for photon templates as well.
@rocknes @sahithi @sakthisunda @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/633)

Reverting system tests after photon gc bug fix

---

system_tests/test_cse_client.py
system_tests/test_cse_server.py

- Fix failing CTOT cse tests
- Comment out the tests that don't need to be run temporarily in test_cse_server.py
- Include CSE upgrade as part of CSE install in test_cse_client.py 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/639)

PR- Fix CTOT failure

---

container_service_extension/client/cluster.py
container_service_extension/client/command_filter.py
container_service_extension/client/cse.py
container_service_extension/client/def_entity_cluster.py
container_service_extension/client/native_cluster.py
container_service_extension/def_/cluster_service.py
container_service_extension/def_/entity_service.py
container_service_extension/def_/schema_service.py

- CLI to support vcd cse cluster apply <input_yaml_path>
- Necessary code to complete client side support : cse.py, native_cluster.py, cluster.py
- Def API to check existence of DEF instance at client side
- POST input.yaml for cluster create
- Helper method in entity_service.py to get entity_type
- Removed duplicate declaration from command_filter.py and reuse ClusterEntityKind from def_/utils.py
- Maually tested with the yaml in the attchment
[input.txt](https://github.com/vmware/container-service-extension/files/4860680/input.txt)
--- 
**prerequisite**
- sizing_class in the input.yaml needs to be created and assigned to ovdc before executing the command ( Else master node creation fails with sizing policy not found error)
- storage_profile: '*' works fine 
-----
Testing completed with …

[VCDA-1547] Implement vcd cse cluster apply for create cluster

---

container_service_extension/compute_policy_manager.py

Fixing errors introduced in removing operation context from compute policy manager
Testing done:
`vcd cse ovdc compute-policy remove policy1 -o myorg -v myorgvdc -f`
@rocknes @sakthisunda @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/643)

fix remove_compute_policy_sync errors

---

container_service_extension/client/cse.py
container_service_extension/client/def_entity_cluster.py
container_service_extension/client/legacy_native_cluster.py
container_service_extension/def_/cluster_service.py
container_service_extension/def_/entity_service.py
container_service_extension/request_handlers/v35/def_cluster_handler.py

- Cluster list and info implementation for Defined Entity
- For API version >= 35, cluster list and info uses DEF API to fetch the desired result 
- Manually tested and verified for: API version >= 35 uses DEF API and version < 35 works with CSE server
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/642)

[VCDA-1548] Cluster List and Info for Defined Entity

---

container_service_extension/def_/cluster_service.py
container_service_extension/request_handlers/v35/def_cluster_handler.py
container_service_extension/server_constants.py
container_service_extension/vcdbroker.py

Implement server side cluster config for def clusters
Testing done:
Created a def cluster and checked if `https://{{VCD_IP}}/api/cse/internal/clusters/{{CLUSTER_IP}}/config` is returning the cluster config.
@sahithi @sakthisunda @andrew-ni @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/646)

[Vcda 1605] implement server side get cluster config

---

container_service_extension/def_/cluster_service.py
container_service_extension/vcdbroker.py

- Cluster create and resize support for 0(zero) worker node
- supports `vcd cse cluster create -N 0` and `vcd cse cluster resize -N 0`
- Tested vcd cse create with -N 0 ; resize -N 0 scale down;  
- verified  scale up after the change
- TODO() Future testing for resize on new endpoints as it requires node operations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/644)

[VCDA1590] Cluster create and resize support to handle 0 worker nodes

---

container_service_extension/client/cse.py
container_service_extension/client/def_entity_cluster_api.py
container_service_extension/client/native_cluster_api.py

-  Def native cluster upgrade-plan CLI implementation
-  Supports `vcd cse cluster upgrade-plan` with optional --k8-runtime flag for >= v35
-  Manually tested  and verified ( screenshot below ) 
----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/654)

[VCDA-1611] CLI implementation cluster-upgrade-plan 

---

container_service_extension/def_/models.py
cse_def_schema/api_v35/schema.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/657)

Model and Schema changes to include nfs

---

container_service_extension/client/command_filter.py
container_service_extension/client/cse.py
container_service_extension/client/def_entity_cluster_api.py
container_service_extension/client/native_cluster_api.py

-  Def Native cluster upgrade CLI implementation
- Supports vcd cse cluster upgrade with optional --k8-runtime flag for >= v35
----
----
After resolving merge conflict:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/660)

[VCDA-1610] Cluster upgrade CLI implementation for Defined Entity

---

container_service_extension/def_/cluster_service.py
cse_def_schema/api_v35/schema.json

- Cluster resize should support scale down
* Also includes changes for: 
- Delete cluster to delete unresolved clusters
- Upgrade should read node details from the defined entity.
- Tested using 
reduced the cluster worker count to 0 in the input spec and ran `vcd cse cluster apply`
Testing TODO
upgrade cluster testing to check upgrade node name chages
delete cluster for unresolved entity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/661)

[VCDA-1594& VCDA-1604]: Implement scale down for clusters

---

container_service_extension/client/command_filter.py
container_service_extension/client/cse.py
container_service_extension/client/def_entity_cluster_api.py
container_service_extension/client/native_cluster_api.py

- Cluster config CLI for Defined Entity Cluster
- Hide -k option for < version 35
- Tested with Def entity cluster
- Docstring fix
-----
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/664)

[VCDA-1608] Cluster config CLI implementation

---

container_service_extension/def_/models.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/674)

[VCDA-1672] Include Org and Owner as part of the defined entity model

---

container_service_extension/client/def_entity_cluster_api.py
container_service_extension/request_processor.py
container_service_extension/server_constants.py

-  Fix for broken vcd cse template list (screenshot attached). 
-  All required CSE operation and implementation is part of this fix.
-  This error was also noticed while testing telemetry. So posting this as separate PR  
-  Manually tested and verified.
------------------------------------
Before fix
After fix
-----------------------------------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/692)

[TestFest] Fix for broken vcd cse template list for api version 35

---

requirements.txt

Added the requirement installing the paho mqtt library in requirements.txt
Installed the current requirements.txt file and paho-mqtt 1.5.0 along with other packages in the requirements file were present
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/700)

[VCDA-1677] added paho-mqtt to requirements.txt

---

container_service_extension/client/cse.py
container_service_extension/configure_cse.py
container_service_extension/def_/cluster_service.py
container_service_extension/def_/models.py
cse_def_schema/api_v35/schema.json

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/691)

VCDA-1644 Add description for the schema

---

container_service_extension/configure_cse.py

Currently CSE upgrade paths are hardcoded, as a result it becomes impossible to do the following upgrades
supported : X.Y.Z to X'.Y'.Z'
not supported : X.Y.Z+ to X'.Y'.Z'
In this PR, we relax the patch version checks while determining the validity of an upgrade path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/696)

[VCDA-1698] Allow upgrade from arbitrary patch version in a supported upgrade path

---

container_service_extension/compute_policy_manager.py
container_service_extension/def_/cluster_service.py

* Avoid adding the cse---- prefix before searching for the sizing policy during adding nodes
* Testing done:
* create a cluster with no sizing policy
* create a cluster with with sizing policy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/698)

[VCDA 1653] Avoid using prefix while creating/ updating clusters

---

requirements.txt

Update pyvcloud requirement in requirements.txt to track the correct dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/703)

Update pyvcloud version in requirements.txt

---

container_service_extension/configure_cse.py

Checking if the API version meets the minimum MQTT API version before checking if there is an existing MQTT extension.
Tested cse install with API version 33 without failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/712)

[bug fix]checking API version before checking for MQTT extension

---

container_service_extension/def_/cluster_service.py
container_service_extension/vcdbroker.py

* Changed the CSE cluster name validation to match UI regex
* newly used regex: `^[a-zA-Z][A-Za-z0-9-]*$`
@rocknes @andrew-ni @sahithi @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/715)

Changed name validation regex for cluster name

---

container_service_extension/client/def_entity_cluster_api.py

* Avoid showing native clusters if CLI is enabled only for TKG
* If CSE server is not running, the CLI is assumed to be configured only for TKG clusters. Hence showing Native clusters in `cluster list` operation doesn't makes sense.
Testing done:
* Checked if only TKG clusters are shown in when CLI is enabled only for TKG.
* In the below screenshot, I am changing the profiles.yaml file to have `cse_server_running: false`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/723)

[VCDA-1773] Avoid showing Native clusters if CLI is enabled only for TKG

---

container_service_extension/client/cse.py
container_service_extension/client/sample_generator.py
container_service_extension/utils.py

- Sample cluster config file generation for tkg kind
- Help text on sample yaml properties
- Tested manually with options --native, --tkg, --tkg-plus
-------------------------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/718)

[VCDA-1712,VCDA-1740] sample generation for tkg and help text for sample file

---

container_service_extension/client/cse.py
container_service_extension/server_cli.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/721)

Fix help strings in CLI

---

container_service_extension/def_/cluster_service.py
container_service_extension/request_handlers/v35/def_cluster_handler.py
container_service_extension/vcdbroker.py

Refactored cluster_service and vcdbroker to 
1. Hide non public methods
2. Remove references to non existent methods
3. Added additional log statements
4. Fixed an issue where async tracker task was never marked as failed on encountering errors.
5. Fixed an issue where the defined entity lingered around even if the vApp backing the cluster couldn't be deployed.
Testing done:
Ran all cluster operations from cli and POSTman to make sure that the functionality is working as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/724)

[VCDA-1781,1803, 1735] - Fix missing references to missing methods in cluster_service.py

---

container_service_extension/cloudapi/constants.py
container_service_extension/def_/entity_service.py

Modified _entities by type_ endpoint.
Deleted _/entities_ endpoint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/732)

VCDA-1808: Update "list entities by type" endpoint

---

container_service_extension/client/command_filter.py
container_service_extension/client/cse.py
container_service_extension/client/def_entity_cluster_api.py
container_service_extension/client/native_cluster_api.py

- CLI support for`vcd cse cluster remove-nfs <cluster-name> <nfs-node-name>` for native Kubernetes cluster
- Manually tested and verified (screenshot below)
-------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/731)

[VCDA-1612] vcd cse cluster remove-nfs CLI

---

container_service_extension/configure_cse.py
container_service_extension/server_cli.py

- `cse pks-configure
Usage: cse pks-configure [OPTIONS] PKS_CONFIG_FILE_PATH
Try "cse pks-configure -h" for help.
`
- Configure nsxt servers for CSE using the information provided in configuration file
- Manually tested and verified with PKS testbed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/726)

[VCDA-1777] CLI for cse configure-pks

---

container_service_extension/client/def_entity_cluster_api.py
container_service_extension/client/tkgclient/api/tkg_cluster_api.py

* Fix tkg list endpoint for TKG clusters
* Fix error message when list TKG clusters throws an error.
* Testing done:
* Ran `vcd cse cluster list` to check if there are any errors
* Checked if the error messages are proper when TKG list fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/747)

Fix entities endpoint for tkg client

---

container_service_extension/configure_cse.py
container_service_extension/def_/cluster_service.py
container_service_extension/def_/models.py
container_service_extension/exceptions.py
container_service_extension/local_template_manager.py
container_service_extension/pksbroker.py
container_service_extension/server_constants.py
container_service_extension/vcdbroker.py
cse_def_schema/api_v35/schema.json
docs/CLUSTER_MANAGEMENT.md
docs/KNOWN_ISSUES.md
docs/RELEASE_NOTES.md

Replaced below terms
master -> control_plane
abort -> cancel
kill -> stop
Script names, node names and cluster metadata are yet to be changed. Changing them would affect backward compatibility of Zeus release. Hence, these changes will be done post-zeus.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/735)

Removed offensive terminology

---

container_service_extension/request_processor.py

* Fix cluster query parameters.
* Testing done: Checked if query parameters for /api/3.0/clusters endpoints are working fine
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/746)

[VCDA-1736] Fix filter parameters for cluster list

---

container_service_extension/client/cse.py
container_service_extension/client/legacy_native_cluster_api.py

- Fixed CTOT failure (CTOT4-CSE - #1160-Daily-VCD-10.1.2 Failed)  due to missing CLI options for selective commands. Fixed by providing default values on options that are not part of the command with API versions (<35)
- Manually tested and verfied in API versions < 35
Before fix
After fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/753)

[PR] Fix CTOT failure due to CLI

---

container_service_extension/cloudapi/cloudapi_client.py
container_service_extension/def_/cluster_service.py
container_service_extension/def_/entity_service.py
container_service_extension/def_/schema_service.py
container_service_extension/vcdbroker.py

* Exception handling to handle raw vsphere exceptions in vcdbroker and cluster_service
* Fetch entity ID from the header instead of making additional call to get entity by name in create cluster
* remove delete cluster comment suggesting recreation of entity if delete fails
* Avoid sending response status code as minor error code in entity_service.py and schema_service.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/755)

[VCDA-1825] Fix Minor error codes and add exception handling to cluster_service

---

container_service_extension/cloudapi/cloudapi_client.py
container_service_extension/def_/cluster_service.py
container_service_extension/def_/entity_service.py

* reverted wait on task for entity creation in create entity
Testing done:
* created an entity to see if cluster id is picked up properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/759)

reverting wait on task for create entity in create cluster

---

docs/cse3_0/CLUSTER_MANAGEMENT.md
docs/cse3_0/CSE_CONFIG.md
docs/cse3_0/CSE_SERVER_MANAGEMENT.md
docs/cse3_0/ENT_PKS.md
docs/cse3_0/RELEASE_NOTES.md
docs/cse3_0/TEMPLATE_MANAGEMENT.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/773)

[Github docs] Fixed broken links under "Upcoming" tab

---

docs/cse2_6/CLUSTER_MANAGEMENT.md
docs/cse2_6/KNOWN_ISSUES.md
docs/cse2_6/RELEASE_NOTES.md
docs/cse3_0/CLUSTER_MANAGEMENT.md
docs/cse3_0/CSE30.md
docs/cse3_0/CSE_SERVER_MANAGEMENT.md
docs/cse3_0/KNOWN_ISSUES.md
docs/cse3_0/RELEASE_NOTES.md
docs/cse3_0/TEMPLATE_MANAGEMENT.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/775)

Removed offensive terminology from Docs

---

container_service_extension/def_/cluster_service.py
container_service_extension/user_context.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/766)

[VCDA-1860] Change DE deletion on cluster creation rollback to use sysadmin context

---

container_service_extension/sample_generator.py
docs/cse2_6/TEMPLATE_ANNOUNCEMENTS.md
docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md
system_tests/base_config.yaml

- Updated template announcement page for CSE 2.6 and CSE 3.0  
- New templates
- Existing templates with updated version
- NOTE: Placeholder value for Date ( will be replaced as per the recommendation )
@rocknes @sahithi @Anirudh9794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/776)

[VCDA-1875] Update template announcements page

---

docs/cse3_0/TROUBLESHOOTING.md

* Update log bundle information with new log information and where to find them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/778)

[VCDA-1874] Update log bundle information for cse 3.0

---

container_service_extension/def_/cluster_service.py

Remove warning statements being logged into console.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/782)

Fix warning statement thrown when checking if element is not None

---

docs/cse3_0/CLUSTER_MANAGEMENT.md
docs/cse3_0/CSE30.md
docs/cse3_0/CSE_SERVER_MANAGEMENT.md
docs/cse3_0/KNOWN_ISSUES.md
docs/cse3_0/NFS_STATIC_PV.md
docs/cse3_0/RBAC.md
docs/cse3_0/RELEASE_NOTES.md
docs/cse3_0/TEMPLATE_MANAGEMENT.md
docs/cse3_0/TROUBLESHOOTING.md

[Docs] Edits to CSE 3.0 documentation

---

docs/_data/navigation.yml
docs/cse2_6/CSE_UI_PLUGIN.md
docs/cse3_0/CSE30.md
docs/cse3_0/CSE_UI_PLUGIN.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/779)

[VCDA-1876] Update documentation for Container UI Plugin

---

docs/_data/navigation.yml
docs/_includes/navigation.html
docs/cse3_0/CSE30.md

[Docs] Work in progress docs

---

container_service_extension/client/response_processor.py
container_service_extension/server_constants.py

Logging request/response headers in client wire logging, even if there are errors.
I reviewed the logs during errors and without errors. The response/request headers and other fields were logged.
@sakthisunda @Anirudh9794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-e …

[VCDA-1883] Improve client wire logging

---

docs/cse3_0/CSE_SERVER_MANAGEMENT.md
docs/cse3_0/CSE_UI_PLUGIN.md
docs/cse3_0/ENT_PKS.md
docs/cse3_0/KNOWN_ISSUES.md
docs/cse3_0/NFS_STATIC_PV.md

Remove old content from CSE 3.0 docs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/799)

[Docs] Remove old content from CSE 3.0 docs

---

docs/cse3_0/CONTRIBUTING.md
docs/cse3_0/CSE_CONFIG.md
docs/cse3_0/CSE_INSTALL_PREREQUISITES.md
docs/cse3_0/CSE_SERVER_MANAGEMENT.md
docs/cse3_0/INTRO.md
docs/cse3_0/RELEASE_NOTES.md

Adding release notes for CSE 3.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/830)

Release notes for CSE 3.0.1

---

container_service_extension/system_test_framework/environment.py
system_tests/test_cse_client.py

- Run system tests in org context that is different from org that hosts the catalog 
- Default values for org context and vdc :  test-org, test-vdc
- Override these values with development environment in test section of base_config.yaml
- Update all test cases that use broker org and vdc with test org and test vdc
- Automate the creation of test org and vdc 
- Tested with both default and override values
- Executed all system tests - PASSED
------------
-------------
Tests passed with all changes completed:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/824)

[VCDA-1906] system-tests-in-test-org-context

---

container_service_extension/server_cli.py

> Take care of ambigious error messages in case of :
1. SSL cert validate error
2. CSE service role already exists
3. Wrong username/password
> Change CLI arguments to make SSL Verification switch consistent across
VCD CLI and CSE Server CLI
> Change CLI arguments to accept VCD Host as a mandatory argument
instead of switch
Signed-off-by: Chintan Shah <schintan@vmware.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/841)

[VCDA-1937] Fix minor issue in `cse create-service-role`

---

docs/cse2_6/TEMPLATE_ANNOUNCEMENTS.md
docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md

- Document changes for new template (`Ubuntu 1.19`) announcement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/850)

[VCDA-1926] Ubuntu 1.19 template announcement

---

requirements.txt

Based on Github warning, this PR upgrades the cryptography library.
I have tested installing this requirements.txt and running the server with an encrypted file (this encryption uses the cryptography library).
@Anirudh9794 @sakthisunda @andrew-ni @ChintanShahVMware @arunmk
--- …

[VCDA-1970] updated cryptography library

---

container_service_extension/consumer/utils.py
container_service_extension/request_id_formatter.py
container_service_extension/security.py
container_service_extension/server_constants.py
container_service_extension/thread_local_data.py
container_service_extension/utils.py

- Currrenty thread local data has accessor method exist only for request id. This enhancement gives flexibility to store and access any number of values for future requirement(s). Example: Telemetry data has a similar requirement to use thread local to store UserAgent. 
- Methods added to thread local to support accessors for any data. 
- Tested the changes with request_id in thread local.
- Verfied debug log that logs request id works as expected
@Anirudh9794 @rocknes @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/854)

[VCDA-1950] Thread local data handling enhancement  

---

container_service_extension/client/cluster_commands.py
container_service_extension/client/command_filter.py
container_service_extension/client/constants.py
container_service_extension/client/de_cluster.py
container_service_extension/client/de_cluster_native.py
container_service_extension/client/de_cluster_tkg.py
container_service_extension/client/utils.py
container_service_extension/def_/acl_service.py

Implemented cluster share-list command
Tested listing shared users for a TKG and a native cluster.
- @sakthisunda @ChintanShahVMware @andrew-ni @Anirudh9794 @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/856)

[VCDA-1987] Cluster share list

---

container_service_extension/def_/ovdc_service.py
container_service_extension/pyvcloud_utils.py
container_service_extension/request_handlers/ovdc_handler.py

Porting changes from master:
* Instead of making multiple calls to get ovdc list, we can optimize the output by using a typed query.
* changed ovdc_service and ovdc_handler to make use of a common function to get all the ovdcs
Testing done:
* checked if the changes increased the speed for the query to get `ovdc list`
@sakthisunda @sahithi @rocknes @ltimothy7 @ChintanShahVMware
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/861)

[VCDA-1669] Optimize list vdc query using typed query

---

container_service_extension/def_/cluster_service.py
container_service_extension/pksbroker.py
container_service_extension/request_handlers/pks_cluster_handler.py
container_service_extension/request_handlers/pks_ovdc_handler.py
container_service_extension/telemetry/constants.py
container_service_extension/telemetry/payload_generator.py
container_service_extension/telemetry/telemetry_handler.py

- PKS telemetry changes to include source id and description of the cluster CRUD
- Implemented all PKS detailed table for PKS cluster operations
- Include source and description in addition to pks metrics
- Minor runtime error on LOGGER 
- Updated acl list and update telemetry payload to include source id and description
- PKS ovdc telemetry changes to include source id
- Manually tested all the changes using a working PKS testbed
------------------------------------------------------------------------
@Anirudh9794 @rocknes @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/864)

[VCDA-1958] update PKS telemetry with source

---

container_service_extension/authorization.py
container_service_extension/client/cluster.py
container_service_extension/client/cse_client/api_33/native_cluster_api.py
container_service_extension/client/cse_client/cse_client.py
container_service_extension/client/cse_client/pks_cluster_api.py
container_service_extension/client/cse_client/pks_ovdc_api.py
container_service_extension/client/de_cluster_tkg.py
container_service_extension/client/ovdc.py
container_service_extension/cloudapi_utils.py
container_service_extension/compute_policy_manager.py
container_service_extension/consumer/constants.py
container_service_extension/def_/cluster_service.py
container_service_extension/def_/models.py
container_service_extension/ovdc_utils.py
container_service_extension/pyvcloud_utils.py
container_service_extension/request_handlers/native_cluster_handler.py
container_service_extension/request_handlers/v35/def_cluster_handler.py
container_service_extension/request_handlers/v35/ovdc_handler.py
container_service_extension/server_utils.py

Fixed code re-organization errors to fix the broken CTOTs
Testing done:
(TODO) - run system tests
* create cluster (v35)
* list cluster (v35)
* cluster info (v35)
* cluster config (v35)
* ovdc list
* ovdc update
@ltimothy7 @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/874)

Fix code reorg errors

---

requirements.txt

n/a
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/886)

Port updated cryptography library (#855) to cse_3_0_updates

---

container_service_extension/def_/cluster_service.py

Testing done:
Ran flake8 and no errors were reported
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/885)

Port [VCDA-1955] Update and resolve entity with correct status before syncing def entity (#845) to cse_3_0_updates

---

container_service_extension/server_cli.py

Testing done:
Ran flake8 and made sure no errors were reported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/884)

Port [VCDA-1937] Fix minor issue in `cse create-service-role` (#841) to cse_3_0_updates

---

container_service_extension/configure_cse.py
container_service_extension/telemetry/telemetry_utils.py

Testing done:
Ran flake8 and made sure no errors were there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/883)

Port [VCDA-1908] Reorder CSE installation steps, to make `creation of extension` the last step. (#840) to cse_3_0_updates

---

container_service_extension/consumer/amqp_consumer.py
container_service_extension/consumer/constants.py
container_service_extension/consumer/utils.py
requirements.txt

Testing done :
Checked that flake8 is reporting no errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/882)

Port [VCDA-1909] Add logic in AMQP consumer to reject redelivered messages (#851) from cse_3_0_updates

---

container_service_extension/config_validator.py
container_service_extension/configure_cse.py
container_service_extension/consumer/amqp_consumer.py
container_service_extension/consumer/consumer.py
container_service_extension/sample_generator.py
requirements.txt

Port [VCDE-986]: Migrate to pika 1.1.0 (#847) from cse_3_0_updates to master.
Testing done:
Checked that no errors were reported by flake8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/881)

Port [VCDE-986]: Migrate to pika 1.1.0 (#847) from cse_3_0_updates

---

container_service_extension/def_/cluster_service.py

-  Exclude NFS node from upgrading k8 cluster nodes
------------------
@andrew-ni @Anirudh9794 @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/894)

[VCDA 2082] Fix cluster upgrade with nfs node 

---

container_service_extension/def_/cluster_service.py

-  Exclude NFS node from upgrading k8 cluster nodes
------------------
@andrew-ni @Anirudh9794 @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/896)

[VCDA 2082] Fix cluster upgrade with nfs node (Port)

---

container_service_extension/def_/cluster_service.py

Testing done:
* `vcd cse cluster apply input_config.yaml` (create, resize up and resize down)
* `vcd cse cluster upgradel`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/877)

[VCDA-2002] Avoid resolving defined entities after every update

---

container_service_extension/cloudapi/constants.py
container_service_extension/mqtt_extension_manager.py
container_service_extension/nsxt_backed_gateway_service.py
container_service_extension/server_constants.py
container_service_extension/utils.py

Nsxt edge gateway class. For updates branch
- tested quick ip allocation and creating a DNAT rule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/900)

[VCDA-2040 and VCDA-2043] Nsxt edge gateway (updates branch)

---

container_service_extension/def_/cluster_service.py

Update exception handling code to correctly report the error for Script execution error.
@arunmk @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/911)

[VCDA-2129] Report exception for Script execution error

---

container_service_extension/common/utils/pyvcloud_utils.py

- There was an incorrect import statement for pyvcloud utils that prevented cluster sharing. This import is now corrected.
Successfully shared a cluster.
- @sakthisunda @arunmk @sahithi @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/907)

fixed incorrect import for pyvcloud utils

---

container_service_extension/client/cse_client/api_35/native_cluster_api.py
container_service_extension/request_handlers/v35/def_cluster_handler.py

Errors fixed -
1. Change ClusterEntity -> NativeEntity
2. Remove unused variable from api_35/native_cluster_api.py
@ltimothy7 @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/910)

[VCDA-2143] Fix merge errors

---

container_service_extension/installer/configure_cse.py
container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/entity_service.py
container_service_extension/rde/models/common_models.py
container_service_extension/rde/models/rde_2_0_0.py

Use version string in entity type urn to dynamically figure out the destination Native entity type class
Testing done:
vcd cse cluster list
to check if entity parsing is happenning successfully
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/919)

[VCDA-2149] Dynamically determine the enitity class to use

---

container_service_extension/installer/templates/remote_template_manager.py

Signed-off-by: Arun M. Krishnakumar <arunmk@gmail.com>
There was a regression that I introduced. One of the codepaths (from vcdbroker) dornloads the k8s cluster creation scripts and runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/924)

VCDA-1995: fix regression in test that uses vcdbroker.py

---

container_service_extension/rde/constants.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/930)

Minor enhancements to RDE constants

---

container_service_extension/rde/common/entity_service.py

- vcd cse cluster apply command with the recent master failed with error message 
- Error message: `'DefEntityType' object has no attribute 'VENDOR'`
- Fixed the list entities method with right defined entity type attributes
- Tested manually
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/938)

PR-Fix-DefEntityType-object-has-no-attribute-VENDOR

---

container_service_extension/exception/exceptions.py
container_service_extension/installer/configure_cse.py
container_service_extension/rde/behaviors/behavior_service.py

Added Exception handling to behavior_service.py
Handled behavior exceptions in configure_cse.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/942)

[VCDA-2200] Exception handler for behavior_service.py

---

container_service_extension/cloudapi/constants.py
container_service_extension/nsxt_backed_gateway_service.py
container_service_extension/server_constants.py

Added helped for nsxt backed gateway service to get an available ip.
Successfully retrieved available ip.
@Anirudh9794 @rocknes @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/937)

[VCDA-2188] ipam solution for getting available ip

---

container_service_extension/cloudapi/cloudapi_client.py
container_service_extension/cloudapi/constants.py
container_service_extension/nsxt_backed_gateway_service.py
container_service_extension/server_constants.py
container_service_extension/shared_constants.py

Added helper in nsxt_backed_gateway_service to delete dnat rule by name. Tested that this is able to successfully delete a dnat rule.
@Anirudh9794 @sakthisunda @arunmk @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/936)

[VCDA-2187] Nsxt gateway delete dnat rule

---

container_service_extension/rde/backend/cluster_service_1_x.py

Update exception handling code to correctly report the error for Script execution error.
@arunmk @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/916)

Port [VCDA-2129] Report exception for Script execution error (#911) to master

---

container_service_extension/cloudapi/constants.py
container_service_extension/def_/cluster_service.py
container_service_extension/def_/models.py
container_service_extension/nsxt_backed_gateway_service.py
container_service_extension/server_constants.py
requirements.txt

-Allow cluster to be exposed when specifying intent_to_expose flag to true
Added logic to expose the cluster, checking if the gateway is NSX-T backed, routed network, and the user has enough rights to update the NAT and gateway. If so, an ip for the edge gateway is allocated and a dnat rule is created, mapping the control plane ip to the allocated ip.
The spec and status section of the schema have new fields: intent_to_expose and expose. …

[VCDA-2132] Expose cluster in cluster create workflow

---

container_service_extension/rde/backend/cluster_service_2_x.py

Commit missed out in #916 (Port [VCDA-2129] Report exception for Script execution error (#911) to master)
Forgot to add the changes made locally after rebase.
@rocknes @sakthisunda @sahithi @ltimothy7 @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/946)

A Fix for changing e to E in cluster-2-x

---

container_service_extension/common/constants/server_constants.py
container_service_extension/common/constants/shared_constants.py
container_service_extension/lib/cloudapi/cloudapi_client.py
container_service_extension/lib/cloudapi/constants.py
container_service_extension/lib/nsxt/constants.py
container_service_extension/lib/nsxt/nsxt_backed_gateway_service.py

Tested deleting dnat rule by name.
@arunmk @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/948)

Port [VCDA-2187] [Nsxt gateway delete dnat] (#936) to master

---

container_service_extension/cloudapi/cloudapi_client.py
container_service_extension/cloudapi/constants.py
container_service_extension/def_/cluster_service.py
container_service_extension/nsxt_backed_gateway_service.py
requirements.txt

Update exposing cluster logic to use ipam solution
@arunmk @Anirudh9794 @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/949)

[VCDA-2207] Update exposing cluster logic to use ipam solution

---

container_service_extension/def_/cluster_service.py
requirements.txt

-Upon cluster delete, if the cluster is exposed, the dnat rule is deleted.
-Tested dnat rule successfully being deleted upon cluster delete for an exposed cluster.
@arunmk @rocknes @Anirudh9794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/951)

[VCDA-2189] Update cluster delete to handle exposed cluster

---

container_service_extension/client/de_cluster.py
container_service_extension/client/de_cluster_native.py
container_service_extension/exception/exceptions.py
container_service_extension/installer/configure_cse.py
container_service_extension/rde/backend/cluster_service_2_x_temp.py
container_service_extension/rde/backend/cluster_service_factory.py
container_service_extension/rde/behaviors/behavior_model.py
container_service_extension/rde/constants.py
container_service_extension/rde/utils.py
container_service_extension/rde/validators/abstract_validator.py
container_service_extension/rde/validators/validator_factory.py
container_service_extension/rde/validators/validator_rde_1_x.py
container_service_extension/rde/validators/validator_rde_2_x.py
container_service_extension/security/context/behavior_operation_context.py
container_service_extension/security/context/behavior_request_context.py
container_service_extension/server/behavior_dispatcher.py
container_service_extension/server/behavior_handler.py
container_service_extension/server/request_handlers/v36/def_cluster_handler.py
container_service_extension/server/service.py

1. Added Exception handling to the behavior_handler.py
2. Made the validator more generic so that it can be used by behavior handlers and enhanced the validate method to perform more checks.
3. Refactored v36_handler to accommodate the above changes in validators.
4. Added new method in rde/utils.py to get_rde_version_introduced_at_vcd_version; renamed get_rde_version_by_vcd_api_version -> get_runtime_rde_version_by_vcd_api_version
5. Modified BehaviorOperationContext- float(api_version).
6. End to end (dummy) cluster creation workflow tested.
7. Return payloads (success and error) tested and made some changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-exten …

[VCDA-2197] Framework to connect behavior processor to the backend.

---

container_service_extension/installer/configure_cse.py
container_service_extension/rde/models/abstractNativeEntity.py
container_service_extension/rde/models/rde_1_0_0.py
container_service_extension/rde/models/rde_2_0_0.py

- Upgrade for CSE 3.1.0
- Upgrade CSE code from CSE 3.0.x to 3.1.0
- Tests done
- 33/34 native cluster upgrade to v36/RDE 2.0
- 33/44 native cluster upgrade to v35/RDE 1.0
- v35/RDE 1.0 upgrade to v35/RDE 2.0
- TODO : CSE 3.1/v34 upgrade to CSE 3.1 v35/v36 legacy_mode=True
- Fobidden upgrade checks, user tests
@Anirudh9794  @rocknes @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/956)

[VCDA-2168] Upgrader for CSE 3.1

---

docs/cse3_0/CSE_UI_PLUGIN.md

Signed-off-by: Andrew Ni <niandrew7@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/963)

[VCDA-2004] Add known issue to UI plugin 1.0.3 docs

---

container_service_extension/rde/constants.py
container_service_extension/rde/models/rde_2_0_0.py
cse_def_schema/schema_2_0_0.json

Introduce payload versioning in the schema and model 2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/964)

[VCDA-2249]Introduce payload versioning in the schema and model 2.0

---

container_service_extension/installer/configure_cse.py

Made overriding behavior operation idempotent during install/upgrade
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/967)

[VCDA-2261] Made overriding behavior operation idempotent during install/upgrade

---

cluster_scripts/1_x/mstr.sh
cluster_scripts/2_x/mstr.sh
container_service_extension/installer/templates/remote_template_manager.py

* The cluster scripts should use versioned weave.yml
Testing done:
* cluster create, resize, upgrade
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/969)

[VCDA-2192] Fix cluster scripts and CTOT failure

---

container_service_extension/right_bundle_manager.py
container_service_extension/server_cli.py
container_service_extension/server_constants.py

Port the fix from masters to cse_3_0_updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/971)

Port '[VCDA-2274] Fix upgrade issue related to missing rights in `cse service account` (#965)' to cse_3_0_updates

---

container_service_extension/server/behavior_handler.py
container_service_extension/server/request_handlers/cluster_handler.py

Process payload version in the behavior handler
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/976)

Process payload version in the behavior handler

---

requirements.txt

Update requirement txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/977)

update requirements txt

---

container_service_extension/client/cluster_commands.py
container_service_extension/client/de_cluster_native.py
container_service_extension/client/sample_generator.py
container_service_extension/common/constants/server_constants.py
container_service_extension/installer/configure_cse.py
container_service_extension/lib/telemetry/payload_generator.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_temp.py
container_service_extension/rde/constants.py
container_service_extension/rde/models/abstractNativeEntity.py
container_service_extension/rde/models/common_models.py
container_service_extension/rde/models/rde_1_0_0.py
container_service_extension/rde/models/rde_2_0_0.py
container_service_extension/rde/utils.py
container_service_extension/rde/validators/validator_rde_2_x.py
cse_def_schema/schema_2_0_0.json

* Change all fields in snake_case to camelCase
* Include fields `site` and `uid` in the schema
Testing done:
* create cluster (RDE 2.0)
* resize cluster (RDE 2.0)
* upgrade cluster (RDE 2.0)
* cluster config (RDE 2.0)
* cluster upgrade-plan
* cse install
* cse run
* cse upgrade
@rocknes @sahithi @sakthisunda @arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/983)

[VCDA-2272] Update rde 2.0.0 schema

---

requirements.txt

Update requirements.txt
Testing done:
cse run
@rocknes @sakthisunda @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/980)

update requirements for cse_3_0_updates

---

container_service_extension/security.py

Tested that logs no longer show Bearer token. Also checked that single quote keys have redacted tokens
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/987)

[VCDA-2238] edited regex pattern to redact headers with double quote (updates)

---

container_service_extension/security/security.py

Tested that authorization token is redacted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/988)

[VCDA-2238] edited regex pattern to redact headers with double quote (main)

---

container_service_extension/mqi/consumer/mqtt_consumer.py
container_service_extension/mqi/consumer/mqtt_publisher.py
container_service_extension/mqi/consumer/utils.py
container_service_extension/rde/utils.py

Fix cluster operations giving unauthorized exception when control switches to the async method.
@ltimothy7 @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/992)

Fix MQTT Location header

---

container_service_extension/rde/models/rde_1_0_0.py

Fix error `attribute not found task_href` when converting rde 2.0.0 to 1.0.0
@sakthisunda @sahithi @rocknes @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/997)

Fix task_href error when converting rde 2.0 to rde 1.0

---

container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/validators/validator_rde_2_x.py

Update spec portion of the defined entity during resize cluster and upgrade cluster.
Testing(TODO)
Check if resize and upgrade operations change spec portion of the defined entity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1000)

VCDA-2313: Fix spec rde update

---

container_service_extension/client/de_cluster_native.py

Incorrect reference for cluster name in CLI
@rocknes @sakthisunda @sahithi @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1003)

Fix cluster apply cli referencing incorrect key

---

container_service_extension/installer/configure_cse.py
container_service_extension/server/service.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1005)

Fix cse run/install/upgrade for cse 3.1 beta

---

container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_behaviors.py

RDE model module (rde_2_0_0) sshould be dynamically retrieved so that cluster_service_2_x uses the right RDE classes for processing cluster operations.
Added TODO explaining the above.
Fixed imports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/954)

[VCDA-2209] Change imports, add TODO for dynamically picking the rde moel module

---

docs/cse3_0/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1004)

3.1 beta - release notes

---

container_service_extension/developer_guide.md

Added a developer-guide file.
Created placeholders for all the areas we would need to touch at the beginning of each release. Tagged the feature owners to do further updates.
Filled in RDE section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/995)

[VCDA-2217]Release check-list

---

docs/cse3_0/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1007)

Correction in the Release notes for 3.1 Beta

---

container_service_extension/rde/models/common_models.py
container_service_extension/rde/schema_service.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1010)

Temporary fix for hooks in the entity type

---

container_service_extension/client/cse_client/api_35/native_cluster_api.py
container_service_extension/client/de_cluster.py
container_service_extension/client/de_cluster_native.py
container_service_extension/client/sample_generator.py
container_service_extension/installer/configure_cse.py
container_service_extension/lib/telemetry/payload_generator.py
container_service_extension/mqi/consumer/utils.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_behaviors.py
container_service_extension/rde/common/entity_service.py
container_service_extension/rde/models/abstractNativeEntity.py
container_service_extension/rde/models/common_models.py
container_service_extension/rde/models/rde_1_0_0.py
container_service_extension/rde/models/rde_2_0_0.py
container_service_extension/rde/schema_service.py
container_service_extension/rde/utils.py
container_service_extension/rde/validators/validator_rde_2_x.py
container_service_extension/server/request_handlers/cluster_handler.py
container_service_extension/server/request_handlers/v35/def_cluster_handler.py
container_service_extension/server/request_handlers/v36/def_cluster_handler.py

* Include changes to use dataclasses_json
* Changed rde_1_0_0 to also use dataclasses_json
Testing done
* Cluster list
* cluster create
* cluster resize 
* cluster upgrade
* cluster info
@rocknes @arunmk @sakthisunda @sahithi @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/990)

[VCDA-2304] change model classes to use snake case instead of camel case

---

container_service_extension/rde/backend/cluster_service_2_x_behaviors.py
container_service_extension/rde/common/entity_service.py

Suppress hooks while updating RDEs.
Tested in a CSE-VCD environment with hook-based behaviors for native entity type 2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1016)

[VCDA-2319]Allow conditional firing of the hooks

---

container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_behaviors.py

* Testing done
Cluster create
check GET /cse/3.0/cluster/id response
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1019)

[VCDA-2144] Avoid querying vapp if defined entity doesn't have external ID

---

container_service_extension/developer_guide.md

Updated contribution guide for CSE
@sakthisunda @sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1013)

[VCDA-2320] updated contributor docs

---

system_tests/test_cse_server.py

Fixed some tests that were failing because the config file read from file was not being augmented with some key value pairs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1023)

Fix server tests

---

container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/rde/backend/cluster_service_2_x_behaviors.py
container_service_extension/rde/models/common_models.py
container_service_extension/security/context/user_context.py
requirements.txt

* Update pyvcloud to 23.0.2.dev1
* change cluster_service_1_x.py and cluster_service_2_x_behaviors.py to have proper check for storage profile
* fix user context org_href access
@rocknes @ltimothy7 @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1025)

Update pyvcloud, and fix storage profile checks

---

docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1022)

docs added 1.20 template announcement

---

container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_behaviors.py
container_service_extension/rde/common/entity_service.py
container_service_extension/rde/models/common_models.py
container_service_extension/server/behavior_handler.py

* Update cluster_service_*_behaviors.py
* Delete entity if create fails in the sync portion
Testing done
* Create entity
* Update entity
* Delete entity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1027)

[VCDA-2282] Test and Fix CRUD operations via behaviors

---

container_service_extension/developer_guide.md

Filled in the sections related to CSE API support and maintenance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1033)

[VCDA-2321] Update developer notes with instructions for maintaining CSE API

---

container_service_extension/rde/models/common_models.py

Checked if behaviors are successfully invoked for
`vcd cse cluster *` commands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1043)

Enable  create, update and delete hooks

---

setup.py

* flake8 error fixes for CTOTs
Testing done:
* flake8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1049)

Flake8 fix for the CTOTs

---

container_service_extension/def_/cluster_service.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1054)

[VCDA-2549] Added sleep for tkgm cluster creation workflow

---

container_service_extension/client/cluster.py
container_service_extension/client/cluster_commands.py
container_service_extension/client/constants.py
container_service_extension/client/ovdc_commands.py
container_service_extension/def_/cluster_service.py
container_service_extension/shared_constants.py
container_service_extension/utils.py
cse_def_schema/api_v35/schema.json

-Testing done:
-ovdc enable/disable
-cluster creation (1 control plane, 1 worker)
-template list
-cluster config, info, upgrade plan (no valid upgrade targets), delete
@arunmk @andrew-ni @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1055)

[VCDA-2371] Tkgm client

---

container_service_extension/def_/cluster_service.py

Tested resizing the cluster, and the cluster info shows the external ip.
@Anirudh9794 @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1056)

[VCDA-2542] preserving external ip during resize

---

container_service_extension/client/sample_generator.py
container_service_extension/rde/models/rde_2_0_0.py
cse_def_schema/schema_2_0_0.json

RDE changes to accommodate Telefonica needs for cpu and memory.
Hide the changes in Andromeda sample.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1059)

[VCDA:2550] RDE changes to accommodate Telefonica needs for cpu and memory.

---

container_service_extension/server/service.py

Fix incorrect Enum usage in CSE run code to fix CTOTs
Testing done:
* Started CSE server successfully with a template installed
@sakthisunda @sahithi @rocknes @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1064)

Use correct enum for template rule processing

---

container_service_extension/def_/cluster_service.py
requirements.txt

* Fix if check for storage policy
* change pyvcloud version used to 23.0.2.dev1
Testing done
* Create a cluster using a storage profile other than the storage profile on the template. -> success
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1062)

[VCDA-2566] Storage profile check fix

---

docs/_data/navigation.yml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1066)

[Docs] Rename CSE 3.1 to Work_in_progress 

---

container_service_extension/rde/backend/cluster_service_2_x.py

settings.network -> settings.ovdc_network
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1067)

Regression fix (network -> ovdc_network)

---

container_service_extension/client/sample_generator.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/models/abstractNativeEntity.py
container_service_extension/rde/models/rde_1_0_0.py
container_service_extension/rde/models/rde_2_0_0.py

Fix sample help strings
Testing done:
* `vcd cse cluster apply -sn` when CSE is running against VCD 10.2 and VCD 10.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1072)

[VCDA-2297] Fix stale sample help strings

---

container_service_extension/client/policy_based_ovdc.py

Error message fix for ovdc enable/disable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1078)

Fix OVDC enable/disable error messages

---

container_service_extension/common/constants/shared_constants.py
container_service_extension/developer_guide.md
container_service_extension/rde/models/common_models.py
container_service_extension/server/behavior_dispatcher.py

1. Enable 37 alpha requests in behavior_handler
2. Relax the DefEntity parsing by ignoring the unknown properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1074)

Fixes to accommodate multiple changes in VCD 

---

container_service_extension/server_cli.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1080)

[VCDA-2623] Fix CLI help strings

---

container_service_extension/client/policy_based_ovdc.py

OVDC enable/disable error msg fix
@sakthisunda  @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1079)

Fix incorrect error message during ovdc enable/disable

---

container_service_extension/server/request_handlers/legacy/native_cluster_handler.py

Testing done:
call /cse/nativecluster endpoint
@sakthisunda  @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1084)

[VCDA-2297] Fix /nativeclusters endpoint when no query params are set

---

docs/cse3_0/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1069)

Release notes for CSE 3.0.3

---

container_service_extension/lib/nsxt/nsxt_backed_gateway_service.py

The code was previously not waiting for the dnat rule creation to complete, not allowing the code to detect a failed dnat rule creation. 
Tested creating dnat rule while waiting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1088)

[VCDA-2631] waiting for dnat rule creation

---

container_service_extension/lib/telemetry/constants.py

- New collector id for CSE 3.1 telemetry 
@rocknes @goelaashima @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1101)

[VCDA-2635] telemetry collector id for andromeda

---

container_service_extension/client/cluster.py
container_service_extension/client/cluster_commands.py
container_service_extension/client/command_filter.py
container_service_extension/client/de_cluster.py
container_service_extension/client/de_cluster_tkg.py
container_service_extension/client/de_cluster_tkg_s.py
container_service_extension/client/legacy_cluster_native.py
container_service_extension/client/ovdc_commands.py
container_service_extension/client/sample_generator.py
container_service_extension/client/utils.py
container_service_extension/common/constants/shared_constants.py
container_service_extension/exception/exceptions.py
container_service_extension/installer/configure_cse.py
container_service_extension/rde/acl_service.py
container_service_extension/rde/common/entity_service.py
container_service_extension/rde/constants.py
container_service_extension/rde/models/common_models.py

Constant name change TKG -> TKG_S
Flag changes :
TKG flag -t -> -k
TKG Plus flag -t/-k -> -p
Additionally fixed a lot of warning in the affected files, mostly typos and missing docstring, wrong docstring etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1097)

[VCDA-2662] Change flag and code constant names for TKG, TKG+

---

container_service_extension/client/cluster_commands.py
container_service_extension/client/sample_generator.py

Tested TKG-S, native, and TKG+ sample confi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1111)

Fix for native cluster apply

---

container_service_extension/client/cluster_commands.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1113)

edit apply help string

---

docs/cse3_1/CSE31.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1120)

Updated the latest VCD links in the Andromeda docs

---

docs/cse3_1/CLUSTER_MANAGEMENT.md
docs/cse3_1/CSE_CONFIG.md
docs/cse3_1/TEMPLATE_MANAGEMENT.md

Edits to cse apply command description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1121)

More edits to the Andromeda docs

---

docs/_data/navigation.yml
docs/_includes/navigation.html

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1123)

Making CSE 3.1 as main page

---

docs/cse3_1/CSE31.md
docs/cse3_1/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1124)

Final edits to the Andromeda docs

---

container_service_extension/lib/telemetry/constants.py

- Move VAC to production
@rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1125)

[VCDA-2643] Move to VAC production for telemetry

---

docs/cse3_1/CLUSTER_MANAGEMENT.md
docs/cse3_1/KNOWN_ISSUES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1127)

Edits to the Andromeda docs

---

docs/cse3_1/CLUSTER_MANAGEMENT.md
docs/cse3_1/KNOWN_ISSUES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1128)

Edits to Andromeda docs

---

container_service_extension/remote_template_manager.py

…ook url
Testing done:
- Check if exceptions are caught if incorrect cookbook url is supplied during CSE run
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1137)

[VCDA-2723] Handle exceptions when connecting to remote template cookbook

---

container_service_extension/configure_cse.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1138)

Open self upgrade path in 3.0.4

---

setup.py

Testing done:
```
> twine check dist/*               
Checking dist/container_service_extension-3.0.3.dev21-py3-none-any.whl: PASSED
Checking dist/container-service-extension-3.0.3.dev21.tar.gz: PASSED
```
@sakthisunda @rocknes @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1139)

Fix README.md rendering in pypi

---

container_service_extension/vcdbroker.py

Sometimes script execution in CSE begins before the VM deployed completes guest customization. This leads to failures such as - 'Failed to authenticate with the guest OS' This PR adds sleep in vcd broker code to prevent such failures when cse server is running with legacy settings.
Testing done:
* Create cluster,
* Resize cluter (add worker node and nfs node)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1142)

Add sleeps in vcdbroker to prevent authentication failures

---

docs/cse3_0/RELEASE_NOTES.md

@goelaashima @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1141)

Docs for CSE 3.0.4

---

container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/server/vcdbroker.py

Fix flake8 in cse_3_1_updates branch
@sakthisunda @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1154)

Fix flake8

---

container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/server/vcdbroker.py

@sakthisunda @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1153)

Flake8 errors to fix unstable CTOT

---

container_service_extension/common/constants/server_constants.py
container_service_extension/common/utils/core_utils.py
container_service_extension/common/utils/pyvcloud_utils.py
container_service_extension/common/utils/server_utils.py
container_service_extension/installer/configure_cse.py
container_service_extension/installer/templates/local_template_manager.py
container_service_extension/installer/templates/remote_template_manager.py
container_service_extension/installer/templates/template_builder.py
container_service_extension/installer/templates/tkgm_template_manager.py
container_service_extension/lib/cloudapi/cloudapi_client.py
container_service_extension/server/cli/server_cli.py
container_service_extension/server/service.py

Implemented `cse template import` command to import TKGm OVA into CSE catalog.
Testing Done:
* Uploaded a proper TKGm OVA and checked that the VApp template is in the CSE catalog, and the catalog item has correct metadata.
* Tried to upload a directory. Received proper error message.
* Tried to upload an existing VApp template, received proper error message.
* Tried to upload an existing VApp template with -f flag, the operation was successful.
* Tried uploading random OVA. Was prompted correctly for confirmation and additional questions were asked by CSE to construct the metadata correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1166)

[VCDA-2739] Implement 'cse template import` command

---

cluster_scripts/v2_x_tkgm/control_plane.sh
cluster_scripts/v2_x_tkgm/node.sh
container_service_extension/client/cluster.py
container_service_extension/common/constants/server_constants.py
container_service_extension/installer/templates/template_builder.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
container_service_extension/rde/backend/cluster_service_factory.py

- cluster service for TKGm ova based cluster
deployed clusters
@arunmk @rocknes @Anirudh9794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1167)

[VCDA-2758] Cluster service tkgm

---

container_service_extension/installer/configure_cse.py
container_service_extension/system_test_framework/environment.py
system_tests_v2/test_cse_client.py

Breaking up the review https://reviewable.io/reviews/vmware/container-service-extension/1161#-
This PR only contains non-cluster tests
- vcd cse version
- vcd cse system info
- vcd cse ovdc enable
- vcd cse ovdc disable
- vcd cse system stop
Testing done:
- executed the system tests
@arunmk @sakthisunda @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1172)

[VCDA-2530] Part 1 non cluster client tests

---

container_service_extension/common/utils/core_utils.py
container_service_extension/server/cli/server_cli.py

@sakthisunda @sahithi @rocknes 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1173)

Port [VCDA-2752] Add cse version in cse run  to master

---

container_service_extension/common/utils/core_utils.py
container_service_extension/server/cli/server_cli.py

Addressed comments for addition of CSE version in CSE run output
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1175)

[VCDA-2752] Address comments for addition of CSE version

---

container_service_extension/rde/common/entity_service.py
container_service_extension/system_test_framework/utils.py
system_tests_v2/test_cse_client.py

Added tests for the following:
* cluster apply
* cluster delete nfs
* cluster delete
* cluster info
* cluster list
@rocknes @sakthisunda @sahithi
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1177)

[VCDA-2530] Add cluster tests for RDE based tests

---

container_service_extension/rde/backend/cluster_service_factory.py
container_service_extension/server/request_handlers/cluster_handler.py

@sakthisunda @rocknes @andrew-ni
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1188)

[VCDA-2875] fix for getting entity in cluster service factory

---

container_service_extension/system_test_framework/environment.py
system_tests_v2/test_cse_client.py

Breaking up the review https://reviewable.io/reviews/vmware/container-service-extension/1161#-
This PR only contains non-cluster tests
- vcd cse version
- vcd cse system info
- vcd cse ovdc enable
- vcd cse ovdc disable
- vcd cse system stop
Testing done:
- executed the system tests
@arunmk @sakthisunda @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1184)

Port [VCDA-2530] Part 1 non cluster client tests to cse_3_1_updates

---

cluster_scripts/v2_x_tkgm/control_plane.sh
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
requirements.txt

- Use beta images from CSE
- Some of the CSE review comments
- Fix pyvcloud version at `23.0.3.dev12`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1189)

Changes for Beta

---

container_service_extension/client/cluster_commands.py
container_service_extension/rde/utils.py
container_service_extension/server/request_handlers/cluster_handler.py

- Disallow cluster share operation for TKGm
- Server side handling 
- Client side handling if cluster kind is explicitly provided by the user
- Tested with RDE with cluster kind TKGm
- Tested with newly created TKGm cluster using tip of CSE_3_1_UPDATES
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1183)
@Anirudh9794 @ltimothy7

[VCDA-2525] Disallow cluster sharing for TKGm clusters

---

docs/cse3_1/CSE31.md
docs/cse3_1/ENT_PKS.md
docs/cse3_1/RELEASE_NOTES.md

Signed-off-by: Andrew Ni <niandrew7@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1192)

Add notice for TKGI deprecation

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

-  Fix flake8 errors that causes CTOT failure 
@Anirudh9794 @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1196)

PR - Fix CTOT failure

---

cluster_scripts/v2_x_tkgm/control_plane.sh
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

- Took in remaining CR comments of the clusterservice_2_x_tkgm.py
- There was a slight issue while testing unexpose of exposed cluster. Fixed it for TKGm. Same issue lies in native as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1195)

VCDA-2786: remaining CR of Aritra and Sakthi

---

docs/cse3_1/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1200)

Add release notes for CSE 3.1.1 beta 2

---

cluster_scripts/v2_x_tkgm/control_plane.sh
container_service_extension/lib/cloudapi/constants.py
container_service_extension/lib/oauth_client/oauth_constants.py
container_service_extension/lib/oauth_client/oauth_service.py
container_service_extension/lib/tokens_client/tokens_service.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

Create clients for /oauth and /token api endpoints
During creation of cluster - create machine user tokens, supply machine user token to control plane
During deletion - revoke the created machine user tokens
Testing done:
Check if the file in /root/vcloud-basic-auth.yaml of the created control plane node has the right content
@arunmk @sakthisunda @ltimothy7 @rocknes 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1193)

[VCDA-2847] Machine token changes in CSE

---

cluster_scripts/v2_x_tkgm/control_plane.sh

@arunmk @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1203)

Fix incorrect github path in control-plane.sh

---

container_service_extension/common/utils/server_utils.py
container_service_extension/installer/config_validator.py
container_service_extension/installer/configure_cse.py
container_service_extension/installer/sample_generator.py
container_service_extension/server/service.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1209)

Rename `tkgm_only_mode` to `no_vc_communication_mode`

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

This will help limit control-plane traffic to within the cluster.
Signed-off-by: Arun M. Krishnakumar <arunmk@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1214)

VCDA-2951: use internal ip for kubeadm join

---

container_service_extension/rde/common/entity_service.py
container_service_extension/system_test_framework/environment.py
container_service_extension/system_test_framework/utils.py
system_tests/base_config.yaml
system_tests_v2/base_config.yaml
system_tests_v2/test_cse_client.py

Added tests for the following:
* cluster apply
* cluster delete nfs
* cluster delete
* cluster info
* cluster list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1194)

Porting [VCDA-2530] RDE cluster tests to cse_3_1_updates

---

container_service_extension/installer/configure_cse.py
container_service_extension/rde/common/entity_service.py
cse_def_schema/schema_2_0_0.json

Update schema when upgrading from CSE 3.1.0
Testing done:
* Check if upgrading from cse 3.1.0 updates CPU description in the schema
@sakthisunda @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1212)

[VCDA-2690] Change CPU description in schema and upgrade schema when CSE is 3.1.0

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

Split add_control_plane function as exposed IP won't be propagated to _create_cluster_async() if there is an error during cluster creation.
Testing done:
* Tested DNAT rule deletion by simulating an error during cluster creation
* Tested if TKGm cluster is created successfully if there is no error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1218)

[VCDA-2956]Fix DNAT rule not being deleted during rollback

---

container_service_extension/client/cluster_commands.py
container_service_extension/client/command_filter.py
container_service_extension/client/node_commands.py
container_service_extension/client/ovdc_commands.py
container_service_extension/client/pks.py
container_service_extension/client/system_commands.py
container_service_extension/client/template_commands.py
container_service_extension/installer/configure_cse.py
container_service_extension/lib/nsxt/nsxt_backed_gateway_service.py
container_service_extension/lib/telemetry/telemetry_handler.py
container_service_extension/lib/telemetry/telemetry_utils.py
container_service_extension/lib/telemetry/vac_client.py
container_service_extension/mqi/consumer/amqp_consumer.py
container_service_extension/mqi/mqtt_extension_manager.py
container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
container_service_extension/rde/backend/common/network_expose_helper.py
container_service_extension/rde/common/entity_service.py
container_service_extension/rde/schema_service.py
container_service_extension/security/context/operation_context.py
container_service_extension/server/cli/server_cli.py
container_service_extension/server/request_handlers/legacy/ovdc_handler.py

Log stack trace wherever we raise a different exception or not raise the original exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1219)

Improve Logging

---

container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
container_service_extension/rde/common/entity_service.py

changes for native workflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1221)

VCDA-2952: Fix private section getting deleted, and other small

---

container_service_extension/server/cli/server_cli.py

Testing done:
* ran `cse install` to see if there is any error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1225)

Fix incorrect parameter in cse install

---

container_service_extension/installer/templates/template_rule.py

Install cse in legacy mode, create template and add template rule.
Start server 
Create cluster
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1229)

Fix template rules in cse legacy mode

---

container_service_extension/rde/models/rde_2_0_0.py

- Fixed cluster apply sample for tkgm
- Tested manually
@rocknes @Anirudh9794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1228)

[VCDA-2981] Fix cluster apply sample for tkgm

---

docs/cse3_1/CSE31.md

Update the CSE 3.0z -> CSE 3.1.z section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1249)

Update CSE 3.1.1 docs

---

container_service_extension/common/utils/server_utils.py

- Fix for breaking pagination
- Prepend scheme and hostname while forming nextpage and previous page uri
- Affected operations: vcd cse cluster list, vcd cse ovdc list
- Tested and verfied CLI and REST endpoints
- Legacy mode: true and legacy mode: false  
- Tested:api/cse/3.0/orgvdcs?page=&pageSize=
- api/cse/nativeClusters, api/cse/3.0/nativeClusters
@Anirudh9794 @rocknes @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1252)

[VCDA-3070] Pagination fix for list clusters and list ovdcs

---

container_service_extension/system_test_framework/utils.py
system_tests/test_cse_client.py

- Add template name and revision for all cluster calls
- Fix cluster list output
@andrew-ni @sakthisunda @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1253)

[Vcda-3033] Fix for 10.1.3 CToT

---

container_service_extension/installer/configure_cse.py
container_service_extension/rde/constants.py
container_service_extension/rde/models/common_models.py
cse_def_schema/capvcd_schema_1_0_0.json
docs/cse3_1/CLUSTER_MANAGEMENT.md
docs/cse3_1/KNOWN_ISSUES.md

1. Added a new CAPVCD schema json file (copied the TKGm 2.0 content and removed irrelevant items like NFS, rollback)
2. CSE registers CAPVCD schema if and only if _register_capvcd_schema_ is set to True in the Config file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1251)

Let CSE register CAPVCD schema

---

container_service_extension/common/utils/server_utils.py
container_service_extension/server/request_handlers/cluster_handler.py
container_service_extension/server/request_handlers/legacy/native_cluster_handler.py
container_service_extension/server/request_handlers/v35/def_cluster_handler.py
container_service_extension/server/request_handlers/v35/ovdc_handler.py
container_service_extension/server/request_handlers/v36/def_cluster_handler.py

- Fixed root caused pagination defect on cluster list
- Reverted the old local adhoc fix
- CLI testing completed
- Postman testing on /cse/nativeclusters, /cse/3.0/nativeclusters
- Tested on VCD 10.2, 10.3
- Tested for Upgrade 33,34 -> legacy_mode = true
- Tested for api version:36 based handler  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1256)

[VCDA-3070] Fixed the regression that caused the pagination defect on cluster list

---

container_service_extension/installer/configure_cse.py
cse_def_schema/capvcd_schema_1_0_0.json

- Include 3.1.2 in range of accepted versions for upgrade
- Tested and verified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1265)

[VCDA-3129] Support upgrade path for cse version 3.1.2

---

cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

- update CSE to use latest CPI and CSI
- Testing completed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1266)

[VCDA-3104] Update-cpi-csi-version

---

cse_def_schema/capvcd_schema_1_0_0.json

Copied updated schema in CAPVCD codbase to CSE
@sahithi @arunmk @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1268)

Update CAPVCD schema

---

docs/cse3_1/KNOWN_ISSUES.md
docs/cse3_1/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1271)

Update RELEASE NOTES and KNOWN ISSUES pages

---

container_service_extension/rde/constants.py

Change NSS for CAPVCD entity type
@sahithi @ltimothy7 @arunmk
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1261)

Change NSS for Capvcd entity type

---

system_tests/test_cse_client.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1278)

Fix client tests for failing CToTs

---

container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
container_service_extension/rde/backend/common/network_expose_helper.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1279)

[VCDA-3162] Update gateway fetching to allow for datacenter group networks

---

system_tests_v2/test_cse_client.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1282)

Fix failing v2 system tests on CToT

---

container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1285)

Fix flake8 warnings

---

container_service_extension/client/cluster_commands.py
container_service_extension/client/command_filter.py
container_service_extension/client/cse_client/api_35/native_cluster_api.py
container_service_extension/client/de_cluster.py
container_service_extension/client/de_cluster_native.py
container_service_extension/common/constants/server_constants.py
container_service_extension/common/utils/pyvcloud_utils.py
container_service_extension/rde/acl_service.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
container_service_extension/rde/common/entity_service.py
container_service_extension/rde/models/common_models.py
container_service_extension/rde/utils.py
container_service_extension/server/request_dispatcher.py
container_service_extension/server/request_handlers/cluster_handler.py

- Force delete cluster - implementation with no regression for the existing code base
- Implementation makes sure the persona has required rights and ACL to execute with no behaviour hooks
- CLI implementation
- Personas tested with missing rights
- Persona tested with missing entityType access controls
- Tested with partially created as well as fully created cluster (Native & TKGm)
- TBD : In progress : More testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1287)

[VCDA-3147] Force delete cluster

---

container_service_extension/common/constants/config_constants.py
container_service_extension/common/utils/config_utils.py
container_service_extension/installer/config_validator.py
container_service_extension/installer/sample_generator.py
container_service_extension/server/cli/server_cli.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1288)

[VCDA-3248] Add extra options to `cse sample` command

---

container_service_extension/installer/sample_generator.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1292)

Update `cse sample` to generate cleaner `extra_options` section

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1290)

[VCDA-3178] updated csi and cpi to 1.1.0

---

docs/cse2_6/RELEASE_NOTES.md
docs/cse3_0/RELEASE_NOTES.md
docs/cse3_1/CLUSTER_MANAGEMENT.md
docs/cse3_1/CSE31.md
docs/cse3_1/CSE_CONFIG.md
docs/cse3_1/CSE_SERVER_MANAGEMENT.md
docs/cse3_1/CSE_UI_PLUGIN.md
docs/cse3_1/KNOWN_ISSUES.md
docs/cse3_1/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1291)

Documentation for CSE 3.1.2

---

container_service_extension/lib/telemetry/constants.py

- VAC url updated to staging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1289)

[VCDA-3259] update VAC url back to staging

---

cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
cluster_scripts/v2_x_tkgm/cloud_init_node.yaml

Signed-off-by: Arun Krishnakumar <akrishnakuma@vmware.com>
Sometimes due to https://github.com/vmware/photon/issues/1110, vcenter may run cloud-init cleanup which will lead to files not getting created when we need to run our code. In those cases, run cleanup and restart the node.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1293)

VCDA-3255: retry cloud-init when files are missing

---

cluster_scripts/v2_x/control_plane.sh
cluster_scripts/v2_x/node.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1298)

[VCDA-2186] Update cluster scripts to use containerd cri-socket

---

docs/cse3_0/RELEASE_NOTES.md
docs/cse3_1/CSE31.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1301)

Remove plugin download page links

---

container_service_extension/common/utils/pyvcloud_utils.py
container_service_extension/common/utils/server_utils.py
container_service_extension/config/server_config.py
container_service_extension/installer/config_validator.py
container_service_extension/installer/configure_cse.py
container_service_extension/installer/templates/remote_template_manager.py
container_service_extension/lib/telemetry/telemetry_handler.py
container_service_extension/lib/telemetry/telemetry_utils.py
container_service_extension/mqi/consumer/consumer.py
container_service_extension/mqi/consumer/consumer_thread_pool_executor.py
container_service_extension/rde/backend/cluster_service_1_x.py
container_service_extension/rde/backend/cluster_service_2_x.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py
container_service_extension/rde/backend/common/network_expose_helper.py
container_service_extension/rde/ovdc_service.py
container_service_extension/security/authorization.py
container_service_extension/security/context/operation_context.py
container_service_extension/server/cli/server_cli.py
container_service_extension/server/pks/pks_cache.py
container_service_extension/server/pks/pksbroker.py
container_service_extension/server/request_handlers/legacy/ovdc_handler.py
container_service_extension/server/request_handlers/template_handler.py
container_service_extension/server/service.py
container_service_extension/server/vcdbroker.py

Introduced a new object `ServerConfig` that encapsulates the configuration dictionary of Service object and makes access to the configuration thread safe.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1303)

[VCDA-3194] Make accessing CSE server runtime config thread safe

---

container_service_extension/client/cse_client/system_api.py
container_service_extension/client/system.py
container_service_extension/client/system_commands.py
container_service_extension/common/constants/server_constants.py
container_service_extension/mqi/mqtt_extension_manager.py
container_service_extension/server/request_dispatcher.py
container_service_extension/server/request_handlers/system_handler.py
container_service_extension/server/service.py

Exposed  GET `/api/cse/system/config`
Added new command `vcd cse system config`
These are only sys admin level operation.
Testing done:
Made the REST call and ran the command as sys admin. Verified the config is returned properly and the password/tokens are redacted properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1305)

[VCDA-3271] Expose REST api and CLI command to fetch CSE server's runtime config

---

cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
container_service_extension/common/constants/server_constants.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

* added tkr changes and removed 0.11.3 constant from tkgm
* using open and close bracket constants in cloud init cp script
* fixed sed bug
* removed unneeded bracket strings
- (Optional) Names of reviewers using …

port from main: [VCDA-3237] Using TKR bom for antrea version (#1308)

---

container_service_extension/common/constants/shared_constants.py

* Fix constant value for CAPVCD cluster entity type
* Tested by executing `vcd cse cluster list` when cse  server is running
@sakthisunda @ltimothy7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1312)

[VCDA-3353]Fix constant value for CAPVCD cluster entity type

---

cluster_scripts/v2_x/control_plane.sh
cluster_scripts/v2_x/node.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1309)

Move set -e command so script does not fail on lsb_release

---

cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

- Cloud init script accepting parameters for default storage class, and cni
Note: thorough testing will be done for following tasks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1315)

[VCDA-3341] Parameterize the cloudinit script to take default storage class, csi, cni, cpi as inputs

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1318)

Rde 2.1 backend not modifying input entity

---

system_tests_v2/test_cse_client.py

* Update required_rde_version for cluster apply tests to 2.1.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1319)

Update RDE version in cluster apply system tests

---

provenance/provenance.sh

- Usage
```
cse) sakthis ~/container-service-extension/provenance [provenance] $ ./provenance.sh 
Usage: ./provenance.sh <BRANCH>
BRANCH: Branch from which provenance data should be generated
```
- `provenance.sh cse_3_1_updates`
-  TODO: Change pipeline script to get provenance.sh from CSE master
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1321)

Automate CSE Provenance data generation 

---

system_tests_v2/test_cse_client.py

- enable nfs delete test
- Locally verfied nfs delete works fine. Reenabling to verify if it works also in CTOT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1322)

Enable nfs delete

---

cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1323)

fix for checking csi

---

container_service_extension/common/constants/server_constants.py
container_service_extension/common/utils/core_utils.py
container_service_extension/rde/models/rde_2_1_0.py
container_service_extension/rde/validators/validator_rde_2_x.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1324)

[VCDA-3346] fail PUT operations for cni/csi/cpi update

---

container_service_extension/common/constants/config_constants.py
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

Added override option in "extra_options" section of server config
Tested successful override
@Anirudh9794 @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1327)

[VCDA-3401] supporting cni/cpi/csi override in cse config

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

* Fix parameters to `get_cluster_script_file_contents`  function
Testing done:
* Deploy a cluster with 1 control plane and 1 worker
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1332)

Update missed .value invocations for python 3.10 support

---

container_service_extension/rde/models/rde_2_1_0.py

Tested upgrading 3.1.2->3.1.3 and successfully deployed a cluster with no changes needed for right bundles.
More testing will be done during testfest
- @sahithi @rocknes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1330)

[VCDA-3345] CSE Upgrade to 3.1.3

---

container_service_extension/common/constants/config_constants.py
container_service_extension/common/constants/server_constants.py
container_service_extension/rde/models/rde_2_1_0.py
container_service_extension/rde/utils.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1335)

[VCDA-3508 and VCDA-3534] updated CSI/CPI constants to 1.1.1 and fix cluster delete when no default storage class

---

cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1340)

remove metrics server version in control plane script

---

container_service_extension/rde/backend/common/network_expose_helper.py

- Fix Native cluster with network->settings->expose:true does not have exposed-ip in cluster config
- Check and replace all occurrences of kubadm init with right control plane end point in the control-plane script. Currently, it happens only for first occurence. 
- control_plane.sh has been undergoing more changes to handle kubernetes versions with multiple entries of kubeadm init. This fix handles right changes for every condition for future changes
- Reproduced the bug and tested the fix with new native cluster creation 
----------------------------------------
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1341)

Fix exposed native cluster config that has interal server address 

---

cluster_scripts/v2_x_tkgm/cloud_init_node.yaml
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

@arunmk @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1342)

[VCDA-3555] cluster resize fix and cloud init code fix

---

cluster_scripts/v2_x_tkgm/cloud_init_node.yaml
container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

@arunmk @sakthisunda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1343)

lint check for node script

---

requirements.txt

Update vcd-cli version to `24.1.0`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1346)

update vcd-cli version to support python 3.10

---

container_service_extension/common/constants/config_constants.py
container_service_extension/common/constants/server_constants.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1347)

[VCDA-3508] updated csi version to 1.2.0

---

container_service_extension/rde/models/rde_2_1_0.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1350)

added description for rde 2.1 csi/cpi/cni fields for TKG clusters for cluster spec sample

---

cluster_scripts/v2_x_tkgm/cloud_init_node.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1352)

[VCDA-3585] pull kapp from harbor

---

container_service_extension/lib/telemetry/constants.py

- VAC url to production
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1348)

Change VAC url to production

---

docs/cse3_0/RELEASE_NOTES.md
docs/cse3_1/CLUSTER_MANAGEMENT.md
docs/cse3_1/CSE31.md
docs/cse3_1/CSE_CONFIG.md
docs/cse3_1/CSE_SERVER_MANAGEMENT.md
docs/cse3_1/INSTALLATION.md
docs/cse3_1/KNOWN_ISSUES.md
docs/cse3_1/RELEASE_NOTES.md
docs/cse3_1/TEMPLATE_ANNOUNCEMENTS.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1349)

[VCDA-3558, VCDA-3553, VCDA-3560, VCDA-3570, VCDA-3571]CSE 3.1.3 Docs

---

docs/cse3_1/CSE31.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1353)

[docs] added 3.1.2 as valid upgrade to 3.1.3

---

docs/cse3_1/CSE_SERVER_MANAGEMENT.md
docs/cse3_1/KNOWN_ISSUES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1354)

known issue: workaround for CSE 3.1.3 to 3.1.3 failing

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

- wrong import order fixed
- tested with flake8 and verified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1355)

[PR] ctot failure fix

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

- fixed flake8 error that blocks CTOT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1356)

[PR] port ctot fix from master 

---

container_service_extension/client/de_cluster_tkg_s.py
container_service_extension/common/constants/shared_constants.py
container_service_extension/server/behavior_dispatcher.py
requirements.txt

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1361)

[VCDA-3810] Fix `vcd cse cluster info/config` command with VCD 10.4 due to 37-alpha version

---

cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml

Fixed the TKGm script to count down from the current TKG version if the tkr is not initially found.
Tested successful cluster creation on 1.5.3 and 1.5.4 ova's
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1363)

[VCDA-3743] Fix for TKGm 1.5.3 Ubuntu OVA 

---

container_service_extension/client/de_cluster.py
container_service_extension/common/constants/shared_constants.py
container_service_extension/developer_guide.md
container_service_extension/rde/common/entity_service.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1362)

[VCDA-3567] include list for cluster list

---

provenance/provenance_v2.sh

- provenance_v2.sh - the script which generates and uploads provenance data using srp-cli
- the script will be picked up by https://sp-taas-vcd-butler.svc.eng.vmware.com/job/cse-provenance/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1366)

Add provenance_v2.sh which uses srp-cli

---

container_service_extension/installer/configure_cse.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1368)

[VCDA-3745] supporting upgrade to cse 3.1.4

---

cluster_scripts/v2_x_tkgm/cloud_init_control_plane.yaml
cluster_scripts/v2_x_tkgm/cloud_init_node.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1371)

[VCDA-3986] added cloud init clean for reboot issue

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1373)

[VCDA-4061] core package installation: reading kubeconfig from rde

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1372)

[VCDA-4074] comparing lowercase sites

---

container_service_extension/rde/backend/cluster_service_2_x_tkgm.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1374)

[VCDA-4083 and VCDA-4085] requiring TKG clusters to have at least 1 worker and no core packages installed on upgraded clusters with 0 workers

---

docs/cse3_1/KNOWN_ISSUES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1375)

[VCDA-3948] Document token expiration known issue in CSE 3.1.1 line prior to CSE 3.1.3

---

docs/cse3_1/CSE31.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1376)

[VCDA-3993] Documentation updated TKG compatibility for CSE 3.1.3

---

requirements.txt

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1377)

[VCDA-3876] consume pyvcloud 23.0.4

---

docs/_data/navigation.yml
docs/cse3_1/CSE31.md
docs/cse3_1/KNOWN_ISSUES.md
docs/cse3_1/RELEASE_NOTES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1380)

3.1.4 release notes and known issues that are fixed in CSE 3.1.4

---

docs/cse3_1/CSE31.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1382)

updated native matrix and TKG version in release notes

---

system_tests/base_config.yaml

The current default template no longer exists, so this update is to update the existing revision in the base_config.yaml
@Anirudh9794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1383)

updated default template in base_config

---

docs/cse3_1/KNOWN_ISSUES.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1385)

added CSE 3.1.3 known issue for resizing upgraded cluster

---

docs/cse3_1/CSE_SERVER_MANAGEMENT.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1384)

updated server management upgrade notes for CSE 3.1.4

---

container_service_extension/rde/backend/common/network_expose_helper.py
system_tests/test_cse_client.py

- fix failing flake8 in ctots
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1387)

Fix failing flake8 for tests

---

system_tests/test_cse_client.py

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1388)

flake8 fix

---

container_service_extension/def_/cluster_service.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1389)

[VCDA-4174] getting control plane ip through vapp without sleep

---

container_service_extension/configure_cse.py

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1390)

[VCDA-4207] allow self-upgrade to CSE 3.0.5

---

docs/cse3_0/KNOWN_ISSUES.md
docs/cse3_0/RELEASE_NOTES.md
docs/index.html

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1391)

[VCDA-4216] release 3.0.5 notes

---

docs/cse3_0/CLUSTER_MANAGEMENT.md
docs/cse3_1/CLUSTER_MANAGEMENT.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1396)

[VCDA-4375] general statement for network access

---

docs/cse3_1/KNOWN_ISSUES.md

@rocknes @goelaashima 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1400)

known issue for missing hooks section after upgrade from CSE 3.1.0

---

docs/cse3_0/RELEASE_NOTES.md
docs/cse3_0/TEMPLATE_ANNOUNCEMENTS.md
docs/cse3_1/RELEASE_NOTES.md
docs/cse3_1/TEMPLATE_ANNOUNCEMENTS.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1402)

General and Template announcement updated in light of cloud.weave.works being shut down.

---

container_service_extension/rde/backend/common/network_expose_helper.py
system_tests/test_cse_client.py

Signed-off-by: ltimothy7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1404)

shortened summary statements for flake8

---

container_service_extension/rde/backend/common/network_expose_helper.py
system_tests/test_cse_client.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1405)

[Port] Shortened summary statements for flake8

---

test-requirements.txt

Signed-off-by: ltimothy7 <ltimothy@vmware.com>
Testing: successfully installed test-requirements.txt and requirements.txt with no issues. Will trigger CTOT with this branch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1408)

[VCDA-4967] capped test-requirements.txt versions

---

test-requirements.txt

Signed-off-by: ltimothy7 <ltimothy@vmware.com>
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
(cherry picked from commit 6be6b104d0b2187a87fa88eab63f74a19db65478)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1409)

[port] [VCDA-4967] capped test-requirements.txt versions

---

test-requirements.txt

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vmware/container-service-extension/1410)

Fix flake8 package version

---

test-requirements.txt

* test flake8 pkg
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* testing import-lib-metadata
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* restricting flake8 to not depend on import-lib-metadata
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
* restricting importlib-metadata
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
Signed-off-by: ltimothy7 <ltimothy@vmware.com>
(cherry picked from commit ccc01b891f923559ed69d32b9cc7d8b14ccf320a)
- …

[port] Fix flake8 package version
